### ISSUE TITLE
GetCurrentLocation

### ISSUE THREAD

**Issue by rufisayev** [lelandrichardson/react-native-maps#10]
Hello,how can i get current location automatically?

**Comment by lelandrichardson** [comment]
are you talking about the maps location (ie the lat/lng that the map is centered on) or the current location of the user?

**Comment by rufisayev** [comment]
i am talking about current location of user..

**Comment by lelandrichardson** [comment]
That's not really in the scope of this library. please see https://facebook.github.io/react-native/docs/geolocation.html
