### ISSUE TITLE
.addPackage missing in Android

### ISSUE THREAD

**Issue by karolbarkowski** [lelandrichardson/react-native-maps#105]
Hi,
in install instructions for Android, on step 3, it is said to add this line 

` .addPackage(new AirPackage()) // <---- and This!`

to the onCreate method of MainActivity class along with the corresponding import statement.

But my MainActivity.java class looks like this one below and I can't find any usage of that "ReactInstanceManager.builder()" method in my project.

I'm using react 0.21. Can this be related to this? Any ideas how can I add that package?
Currently my app is building but all I can see is white background (yeah, I tried to add dimensions to the MapView styles).

```java
public class MainActivity extends ReactActivity {

    @Override
    protected String getMainComponentName() {
        return "sample";
    }

    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage()
      );
    }
}
```

**Comment by heydabop** [comment]
Change
```
return Arrays.<ReactPackage>asList(
    new MainReactPackage()
);
```
to
return Arrays.<ReactPackage>asList(
    new MainReactPackage(),
    new AirPackage()
);
```
