### ISSUE TITLE
In debug mode the map is not loaded? (WhiteScreen)

### ISSUE THREAD

**Issue by BigPun86** [lelandrichardson/react-native-maps#109]
Hey there. Module works fine with release apk (signed), but when i am using the debug.apk on emulator as well as on real device i don´t see any Map...Any ideas?

Running on Mac / ReactNative 0.20 / GenyMotion emulator / Sony Xperia Z5

**Comment by 3LP** [comment]
Same Problem

**Comment by benvium** [comment]
You need to make sure that your debug keystore SHA1 has been added to the Google API console.

To find it use Terminal.app and type:
```
keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android
```

Add the SHA1 shown here, and it should then work.

**Comment by BigPun86** [comment]
@benvium Great job thanks!!! Works. I had it for release apk but of course not for debug.keystore. I thought it would have the same SHA1 key

**Comment by privateOmega** [comment]
@BigPun86 @benvium  I tried using the debug.keystore I generated inside my app,but had no luck. How is the debug keystore in .android and my app folder different?
