### ISSUE TITLE
onRegionChange gives wrong location if map is tilted

### ISSUE THREAD

**Issue by heydabop** [lelandrichardson/react-native-maps#119]
If the map is in a tilted perspective, the coordinates returned by `onRegionChange` no longer line up with the center of the screen, or to coordinates the map programmatically gets navigated to.
To test this just call `animateToCoordinate` on a titled MapView and then check the values returned by `onRegionChange` or `onRegionChangeComplete`, and they won't be equal.

**Comment by christopherdro** [comment]
@heydabop Could you try using to the `pitchEnabled` prop to disable tilting on that specific view?

**Comment by heydabop** [comment]
This was fixed in my PR [#128](https://github.com/lelandrichardson/react-native-maps/pull/128)
