### ISSUE TITLE
How can get Map zoom level?

### ISSUE THREAD

**Issue by osungjin** [lelandrichardson/react-native-maps#122]
I couldn't find from docs.

1. How can I get current map zoom level?
2. How can I set initial map zoom level?

Plz reply to me.

**Comment by osungjin** [comment]
Sorry. I solved.

**Comment by mohamedpsx** [comment]
@osungjin how did you solve this ? did you use latitudeDelta and longitudeDelta ?

**Comment by osungjin** [comment]
Right. I use delta values. and calculating level from sever.

**Comment by brgarciarivas** [comment]
Would you mind going a little more in depth on how you were able to get the zoom level. I understand the delta values are just the difference from the coordinates and full view of the map. But I'm stumped when moving forward.

**Comment by gaguirre** [comment]
We faced the same problem and we ended up using [geo-viewport](https://github.com/mapbox/geo-viewport). It's simple and very useful.

**Comment by ararog** [comment]
@gaguirre but you managed to use geo-viewport with only one coordinate and deltas?

**Comment by ararog** [comment]
log2(360 * ((screenWidth/256) / region.longitudeDelta)) + 1

**Comment by gaguirre** [comment]
@ararog we get the bounds using the _center_ coordinate and the delta and the viewport from `Dimensions`.

Considering you get the **latitude**, **longitude** and **deltas** from somewhere this snippet should work
```javascript
import geoViewport from 'geo-viewport'
import { Dimensions } from 'react-native'

const { height, width } = Dimensions.get('window')

const bounds = [
    longitude - longitudeDelta,
    latitude - latitudeDelta,
    longitude + longitudeDelta,
    latitude + latitudeDelta,
]

geoViewport.viewport(getBounds(region), [height, width])
```

**Comment by avspeed** [comment]
@gaguirre what is getBounds in your code? Can you show its definition?

**Comment by gaguirre** [comment]
@avspeed sorry, it was no need of the function (it was already simplified for the example).
I just edited the snippet and should works now. Thanks!

**Comment by avspeed** [comment]
Thank you @gaguirre!

**Comment by fozhao** [comment]
> log2(360 * ((screenWidth/256) / region.longitudeDelta)) + 1

Man, this saves me life.

**Comment by stanislav-sidorov-empeek** [comment]
const { zoom } = await mapRef.current.getCamera();

**Comment by KumareshZ** [comment]
> const { zoom } = await mapRef.current.getCamera();

Awesome Man
