### ISSUE TITLE
Java compilation error for getPackages()

### ISSUE THREAD

**Issue by Pocket-titan** [lelandrichardson/react-native-maps#138]
Hi,

In Installation.md, it states that (when manually installing), the following code should be added to MainActivity.java: 
```
...
@Override
 protected List<ReactPackage> getPackages() {
   return Arrays.<ReactPackage>asList(
     new MainReactPackage()
     new AirPackage() // <---- and This!
   );
 }
```

However, for me, this results in a compileDebugJavaWithJavac error when building.
Adding a "," after MainReactPackage() fixes the error, so:

```
...
new MainReactPackage()
new AirPackage() 
```

would become:

```
...
new MainReactPackage(),
new AirPackage()
```

If this is an error others also experience, I can make a quick pull request to Installation.md for the missing colon.

**Comment by christopherdro** [comment]
@Pocket-titan Good catch!

Can you submit a PR for that? Thanks!

**Comment by Pocket-titan** [comment]
@christopherdro Sure! Pull request is here: #145
