### ISSUE TITLE
onMarkerPress event is bubbled up to parent components onPress events

### ISSUE THREAD

**Issue by priithaamer** [lelandrichardson/react-native-maps#14]
Hi! I'm using MapView inside one of the views that is inside TabBar. It looks something like this:

```jsx
<TabBarIOS>
  <TabBarIOS.Item onPress={this.handleTabBarItemPress}>
    <View>
      <Mapview>
        <MapView.Marker></MapView.Marker>
      </Mapview>
    </View>
  </TabBarIOS.Item>
</TabBarIOS>
```

Now when pressing on MapView.Marker, `handleTabBarItemPress` method gets called, even without adding any event handlers to marker element itself. The `event.nativeEvent.action` has `"marker-press"` as value. Luckily, this is my current workaround how i can bypass handling this event handler :)

Also i'd like to take a chance and thank you guys for converting this repository into library. I seriously needed working map view for Android this week and it could not come at a better time than it is. I hope i get a chance to contribute to this repository as well. Cheers!

**Comment by lelandrichardson** [comment]
Hey @priithaamer,

This behavior is because the `onPress` event is a bubbling event by default in iOS, and will propogate up the render tree.

I agree though that this isn't exactly the behavior you're expecting... especially with a TabBar item...

In the near term, you can terminate the bubbling by calling `event.stopPropogation()`.  We should consider removing this though.

**Comment by priithaamer** [comment]
Thanks! I haven't seen `onPress` being bubbled up elsewhere, e.g with `TouchableOpacity`, that's why i raised the question. If it is still the case, i think onPress should not be used as it may cause lot of confusion for others as well.

I believe this issue may be closed for now.

**Comment by lelandrichardson** [comment]
@priithaamer i agree. I'll dive deeper into what other RN components are doing and try to follow whatever is "idiomatic". Thanks for bringing the issue up!
