### ISSUE TITLE
Android : Error while updating property 'region' of a view managed by : AIRMap

### ISSUE THREAD

**Issue by ghamaide** [lelandrichardson/react-native-maps#140]
While everything works fine on iOS, I get this error when running on Android : 

![screenshot_2016-03-16-14-09-48](https://cloud.githubusercontent.com/assets/6986811/13813619/c7a4764a-eb82-11e5-8d30-7715122a9a8f.png)

My MapView component : 

```
<MapView
            ref='map view'
            rotateEnabled={false}
            style={styles.restaurantsMap}
            showsUserLocation={this.state.showsUserLocation}
            region={this.state.region}
            onRegionChangeComplete={this.onRegionChangeComplete}
            onRegionChange={this.onRegionChange}>
            <MapView.Circle
              center={center}
              radius={this.state.radius}
              fillColor='rgba(0, 0, 0, 0.1)'
              strokeColor='#FE3139' />
          </MapView>
```

**Comment by DennisMG** [comment]
I was having the same issue! Debbuging the component I realized that region needs latitudDelta and longitudDelta. Once you add those props everything will work just fine.. At least that worked for me.

**Comment by Pocket-titan** [comment]
I had this issue too, and doing what @DennisMG did resolved the issue.
Tip: Use the Chrome debugging. It will provide you with a very clear error, in this case, it would've told you that region needs latitudeDelta and longitudeDelta as arguments as well.

**Comment by lucasfeliciano** [comment]
I'm having the same issue, I added the deltas coordinates but I still get this error:

```
            <MapView
              region={{
                latitude: 52.3015493,
                longitude: 4.6939769,
                latitudeDelta: 3,
                longitudeDelta: 4,
              }}
              style={styles.map}
              showsUserLocation
              zoomEnabled={false}
              scrollEnabled={false}
              rotateEnabled={false}
            >
              <MapView.Marker
                coordinate={{latitude:52.3015493,
                  longitude:4.6939769}} />
            </MapView>
```

**Comment by lucasfeliciano** [comment]
Ok, I figured it out what was my problem in this case:

If you use `showsUserLocation` props you need to add the `ACCESS_FINE_LOCATION` permission into your `AndroidManifest.xml`.

```xml
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
```

That worked for me

**Comment by jrichardlai** [comment]
@ghamaide are you still getting the error?

**Comment by jrichardlai** [comment]
Closing this for now, please reopen if that's still an issue

**Comment by lavarajallu** [comment]
Mr@lucasfeliciano    already i added Still getting error.

**Comment by tenhsor1** [comment]
In my case, my issue was that the latitude and longitude passed to `MapView` were `typeof string`, just did a `parseFloat` before.

**Comment by chapeljuice** [comment]
Thanks @tenhsor1 that was my issue too!

**Comment by youngwiseone** [comment]
> In my case, my issue was that the `latitude` and `longitude` props passed to `MapView` were `typeof string`. Fixed doing a `parseFloat` before.

I fixed by changing my first declarations from `latitude: null` to `latitude: 0` as `null` was being read as type string.

**Comment by aesthytik** [comment]
> In my case, my issue was that the `latitude` and `longitude` props passed to `MapView` were `typeof string`. Fixed doing a `parseFloat` before.

you are a life savior !!!!!! @tenhsor1

**Comment by cwilby** [comment]
In my case `latitude` and `longitude` were missing from `camera.center`:

```js
<MapView
  ...
  camera={{
    center: {
      latitude: parseFloat(group?.facility?.latitude),
      longitude: parseFloat(group?.facility?.longitude),
    },
    ...
  }}>
```

**Comment by witodivaro** [comment]
In my case it was a typo:

I used **longTitude** instead of **longitude**

**Comment by JDPrabasha** [comment]
> While everything works fine on iOS, I get this error when running on Android :
> 
> ![screenshot_2016-03-16-14-09-48](https://cloud.githubusercontent.com/assets/6986811/13813619/c7a4764a-eb82-11e5-8d30-7715122a9a8f.png)
> 

I had the same error using yarn add react-native-maps to display a MapView component

Using `expo install react-native-maps` fixed things!

**Comment by mohitm15** [comment]
I am using expo-cli to see the `mapView` component. I installed it and just added the below code 

```
import React, { useState } from "react";
import {  StyleSheet,  Text,  View} from "react-native";
import MapView from "react-native-maps";

const Map = () => {

  return (

    <View style={styles.container}>
        <Text style={styles.text}>
            Maps
        </Text>
        <MapView
           initialRegion={{
           latitude: 37.78825,
           longitude: -122.4324,
           latitudeDelta: 0.0922,
           longitudeDelta: 0.0421,
        }}
       />
      </View>   
  )
}

const styles = StyleSheet.create({
    container: {
        flex:1,
        justifyContent:'center',
        alignItems:'center'
    },
    text:{
        fontSize:40,
        margin:40,
    }
})
export default Map;
```
And I still found this error

![Screenshot_2022-06-09-17-43-44-46_f73b71075b1de7323614b647fe394240](https://user-images.githubusercontent.com/35539313/172845830-a1242c1c-fcdf-4710-849c-4cb015540166.jpg)

#### How to solve this?

**Comment by diassis-paiva** [comment]
Uma solução que achei foi substituir **initialRegion** por **initialCamera** desta forma:

```
      <MapView
        initialCamera={{
          center: { latitude: -4.143009,  longitude: -40.582803 },
          pitch: 0,
          zoom: 18,
          heading: 0,
          altitude: 1000,
        }}
        provider={PROVIDER_GOOGLE}
      >
```

**Comment by VashRogers** [comment]
> Uma solução que achei foi substituir **initialRegion** por **initialCamera** desta forma:
> 
> ```
>       <MapView
>         initialCamera={{
>           center: { latitude: -4.143009,  longitude: -40.582803 },
>           pitch: 0,
>           zoom: 18,
>           heading: 0,
>           altitude: 1000,
>         }}
>         provider={PROVIDER_GOOGLE}
>       >
> ```

The solution I found for this error was to use a previous version of react native maps, using the command expo doctor --fix-dependencies

**Comment by adribalbvena** [comment]
Same problem here, but i realized the warning: "Some dependencies are incompatible with the installed expo package version: react-native-maps - expected version: 0.30.2 - actual version installed: 0.31.1" 
 - So.. I've run: 
```expo doctor --fix-dependencies```
et voilá!

**Comment by amiravisar89** [comment]
you saved my day

**Comment by amiravisar89** [comment]
> > While everything works fine on iOS, I get this error when running on Android :
> > ![screenshot_2016-03-16-14-09-48](https://cloud.githubusercontent.com/assets/6986811/13813619/c7a4764a-eb82-11e5-8d30-7715122a9a8f.png)
> 
> I had the same error using yarn add react-native-maps to display a MapView component
> 
> Using `expo install react-native-maps` fixed things!

you have saved my day

**Comment by suyashvash** [comment]
> I'm having the same issue, I added the deltas coordinates but I still get this error:
> 
> ```
>             <MapView
>               region={{
>                 latitude: 52.3015493,
>                 longitude: 4.6939769,
>                 latitudeDelta: 3,
>                 longitudeDelta: 4,
>               }}
>               style={styles.map}
>               showsUserLocation
>               zoomEnabled={false}
>               scrollEnabled={false}
>               rotateEnabled={false}
>             >
>               <MapView.Marker
>                 coordinate={{latitude:52.3015493,
>                   longitude:4.6939769}} />
>             </MapView>
> ```

Worked for me, Thanks

**Comment by adithkrishnan98** [comment]
> > While everything works fine on iOS, I get this error when running on Android :
> > ![screenshot_2016-03-16-14-09-48](https://cloud.githubusercontent.com/assets/6986811/13813619/c7a4764a-eb82-11e5-8d30-7715122a9a8f.png)
> 
> I had the same error using yarn add react-native-maps to display a MapView component
> 
> Using `expo install react-native-maps` fixed things!

This fixed it for me! Thanks a lot!

**Comment by aathi271991** [comment]
![Screenshot_1667474266](https://user-images.githubusercontent.com/59364385/199707773-262f455e-b291-46cf-bee8-644616563e61.png)


While everything works fine on iOS, I get this error when running on Android previous it working but now not working

**Comment by DevangMstryls** [comment]
> ![Screenshot_1667474266](https://user-images.githubusercontent.com/59364385/199707773-262f455e-b291-46cf-bee8-644616563e61.png)
> 
> While everything works fine on iOS, I get this error when running on Android previous it working but now not working

I'm having the same issue.

**Comment by Saichand13** [comment]
@DevangMstryls Did you find the solution for this issue ?

**Comment by logan0900** [comment]
@Saichand13 @DevangMstryls  guys we are rocking on the same boat, coz I got the same error while using the "map Polyline" if you find any solution then share it. 💯

**Comment by Saichand13** [comment]
@logan0900 found a temporary fix change  googlePlayServicesVersion = "+" to  googlePlayServicesVersion = "17.0.0" in android/build.gradle.
Working for me


![image](https://user-images.githubusercontent.com/98077584/212276781-56ce873b-0bf1-49b0-81c9-e41455cc3687.png)

**Comment by logan0900** [comment]
@Saichand13  Android works fine for me, I got an error in IOS.
here it is.
<img width="1440" alt="Screenshot 2023-01-14 at 1 01 59 AM" src="https://user-images.githubusercontent.com/58814997/212409731-2d0ee4ea-de85-4074-9b2c-33f06850ed06.png">

**Comment by Rana-Usama** [comment]
> expo install react-native-maps

Running this command fixed it for me as well!
Cheers.

**Comment by bzozoo** [comment]
I got this error in EXPO SDK 48 [v1.3.1](https://github.com/react-native-maps/react-native-maps/releases/tag/v1.3.1)

**Comment by brandox02** [comment]
i used to be the same problem, the problem was i was passing a string on latitude and longitude, i solved this parsing to float :)
