### ISSUE TITLE
Update polyline

### ISSUE THREAD

**Issue by maluramichael** [lelandrichardson/react-native-maps#146]
Is it possible to update a polyline?

```
<MapView
	style={styles.map}
	initialRegion={{
	  latitude: parseFloat(User.location.coords.latitude),
	  longitude: parseFloat(User.location.coords.longitude),
	  latitudeDelta: 1,
	  longitudeDelta: 1
	}}>
	{this._renderMarker([...Spots.campsites, ...Spots.parkingSpaces])}
	{polyline}
</MapView>
```

And {polyline} is a dynamic line from Google Directions Api which i generate everytime i change my origin and destination TextInputs.

I call this after i change my TextInputs.
```
const self = this;
Backend.getRouteBetween(origin, destination)
	   .then((route)=> {
		   self.setState({lastRoute: route})
	   });
```

Then the map gets rendered. But no polyline. Only after i move the map a bit. But only for the first time. If i change the Destination and move the map again, the old polyline is still visible.

```
if (this.state.lastRoute) {
	var route = {};
	var directions = {};
	if (this.state.lastRoute.directions) {
		directions = this.state.lastRoute.directions;
		if (directions.routes.length) {
			route = this.state.lastRoute.directions.routes[0];
			var steps = [];
			if (route.legs.length) {
				steps = route.legs[0].steps;
				distance = route.legs[0].distance;
				duration = route.legs[0].duration;

				coordinates = _.chain(steps).map('start_location').value();
				coordinates.push(steps[steps.length - 1].end_location);

				coordinates = _.map(coordinates, (c)=> {
					return {
						latitude: c.lat,
						longitude: c.lng
					}
				});

				polyline = <Polyline coordinates={coordinates}/>
			}
		}
	}
}
```

**Comment by jrichardlai** [comment]
@maluramichael can you try https://github.com/lelandrichardson/react-native-maps/pull/157 and let me know if that fixes it?

**Comment by maluramichael** [comment]
I tried ```npm install https://git@github.com:lelandrichardson/react-native-maps#9aaa9a539fc7f347d8a8e958b798322f2896802d``` restarted the packager with --reset-cache and got the same problem as above described.

**Comment by jrichardlai** [comment]
hmm strange this fix worked for me. Just double checking, did you rebuild the iOS app?

**Comment by maluramichael** [comment]
@jrichardlai awesome. i don't know why it is now working. Thanks for your help.
