### ISSUE TITLE
Initial Position based on markers + user geolocation

### ISSUE THREAD

**Issue by lucasfeliciano** [lelandrichardson/react-native-maps#147]
I have only one marker and the users geolocation enabled.
I want to have both showing in the initial position of the map.

Whats the best approach to do that?

**Comment by bbk1985** [comment]
will this work?

1. userCoord: get user coordinates with navigator.geolocation.getCurrentPosition
2. centerCoord: get center coordinates of user and marker
3. deltasLat/Lng: get delta of user and marker coordinates
4. create MapView with 
    - initialPosition = centerCoord
    - latitude/longitudeDelta = deltasLat/Lng
    - showUserLocation = true
5. create marker with marker coords

**Comment by christopherdro** [comment]
You can set the users location as a marker and use [fitToElements](https://github.com/lelandrichardson/react-native-maps/blob/master/docs/mapview.md#methods)`.

Not sure if `fitToElemnts` will work if your using `showUserLocation`. If not then you would have calculate the region based the your static marker and users current position and update the `region` prop or use the `animateToRegion` method.
