### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by chenchuanjiang** [lelandrichardson/react-native-maps#148]
I did it according to the instructions.But the page display nothing on android device.I installed google-play-service and applied a google-maps-key.
`
'use strict';

var React = require('react-native');

var {
    AppRegistry,
    StyleSheet,
    Component,
    View,
    Alert,
    TouchableHighlight,
    Text
    } = React;
var MapView = require('react-native-maps');
var MapExample = React.createClass({
    getInitialState(){
        return {
            latitude: 37.78825,
            longitude: -122.4324,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        };
    },
    render() {
        return (
            <View>
                <MapView style={styles.map} initialRegion={{
                    latitude: 37.78825,
                    longitude: -122.4324,
                    latitudeDelta: 0.0922,
                    longitudeDelta: 0.0421
                }}/>

            </View>
        );
    }
});

var styles = StyleSheet.create({
    map:{
        position:"absolute",
        top:0,
        left:0,
        right:0,
        bottom:0
    }
});

module.exports = MapExample;`

**Comment by christopherdro** [comment]
Duplicate #118
