### ISSUE TITLE
Invalid directory /Users/node_modules/react-native-maps

### ISSUE THREAD

**Issue by af7** [lelandrichardson/react-native-maps#15]
Hi I get this error when importing the library:

`uncaught error Error: UnableToResolveError: Unable to resolve module react-native-maps from /[path]/index.ios.js: Invalid directory /Users/node_modules/react-native-maps`

It appears that this is a common problem, do you have any remedy?
https://github.com/facebook/react-native/issues/4968

**Comment by christopherdro** [comment]
@af7 Did you already try some of the suggestion solutions?

1. Delete the node_modules folder - rm -rf node_modules && npm install
2. Reset packager cache - rm -fr $TMPDIR/react-* or node_modules/react-native/packager/packager.sh --reset-cache
3. Clear watchman watches - watchman watch-del-all
4 .Restart Packager

**Comment by af7** [comment]
Yes I did try all of them.

**Comment by lelandrichardson** [comment]
what version of node/npm are you using?  I would try switching (if you're on 5, switch to 4... if you're on 4, switch to 5) and then running `rm -rf node_modules && npm install` again.

**Comment by lelandrichardson** [comment]
Closing, since issue not related to this library.
