### ISSUE TITLE
Prevent mapToolbar to show when selecting a marker

### ISSUE THREAD

**Issue by mvaivre** [lelandrichardson/react-native-maps#158]
Strange behaviour related to the selection of a marker: a map toolbar appears... after rotating the screen to landscape mode. Maybe a MapView prop to allow or not the mapToolbar to show would be nice!

![screenshot_20160330-103031](https://cloud.githubusercontent.com/assets/6715943/14136507/693105f6-f663-11e5-99a7-3f9678328cf6.png)

**Comment by heydabop** [comment]
I actually have a patch for this, I just haven't taken the extra time to make it a prop.

```
diff --git a/android/src/main/java/com/AirMaps/AirMapView.java b/android/src/main/java/com/AirMaps/AirMapView.java
index f028f3b..b07f370 100644
--- a/android/src/main/java/com/AirMaps/AirMapView.java
+++ b/android/src/main/java/com/AirMaps/AirMapView.java
@@ -107,6 +107,7 @@ public class AirMapView
         this.map = map;
         this.map.setInfoWindowAdapter(this);
         this.map.setOnMarkerDragListener(this);
+               this.map.getUiSettings().setMapToolbarEnabled(false);
 
         manager.pushEvent(this, "onMapReady", new WritableNativeMap());
```

**Comment by mvaivre** [comment]
@heydabop Ok nice! Someone to add this as a prop? I could try to do it, but I don't have any experience with Java / writing modules for RN.

**Comment by christopherdro** [comment]
@heydabop Any chance of putting a PR together for this?

**Comment by heydabop** [comment]
Sure, I'll look into making it a prop.

**Comment by heydabop** [comment]
PR is up [#316](https://github.com/lelandrichardson/react-native-maps/pull/316)
