### ISSUE TITLE
Warning when trying to set region: latitude with a variable

### ISSUE THREAD

**Issue by guinaldi** [lelandrichardson/react-native-maps#160]
Hi guys!

When trying to set region latitude with a variable, my iOS simulator is showing a warning message saying that the required propType : latitude was not found. But actually the map is working!

Is that ok?

Thanks!

**Comment by jrichardlai** [comment]
What are the params you are using? Do you have a sample code? Is latitude the only missing proptype?

**Comment by guinaldi** [comment]
I have a fetch getting data from a json and set state consulta receiving this json object.

Then in render i have =  

 var consulta = this.state.consulta;

 <MapView
    style = {styles.map}
    region={{
      latitude: consulta.Latitude,
      longitude: consulta.Longitude,
      latitudeDelta: 0.005,
      longitudeDelta:  0.010
    }}
    />

**Comment by guinaldi** [comment]
Actually the message is: Warning: Failed propType: Required prop 'region.latitude' was not specified in 'MapView'. Check render method.

This happens only with region.latitude and initialRegion.latitude so far.

**Comment by guinaldi** [comment]
Just tested here. With MapView.Marker coordinate also is trowing the warning on latitude.

**Comment by jrichardlai** [comment]
should it be `consulta.latitude` instead of `consulta.Latitude` ?

**Comment by guinaldi** [comment]
in our JSON is Latitude.
The Map is working... It's getting the latitude value on console too.
But keeps the warning message.

**Comment by jrichardlai** [comment]
Is it rendered multiple times? Does it has the latitude on the first rendering?

**Comment by guinaldi** [comment]
@jrichardlai You are right. Its rendering twice. The fetch is done on componentDidMount().
Sorry about that and thanks a lot for the attention!
