### ISSUE TITLE
Any way to create paths from Point A - Point B

### ISSUE THREAD

**Issue by joshbedo** [lelandrichardson/react-native-maps#161]
Similar to what google maps has to offer. You can enter to locations and it tells you the best route to get there. Does anyone know if there is any way to do that currently with this plugin or react native? For example something like Uber where it shows you the paths to take from Point A to get to Point B.

**Comment by DennisMG** [comment]
+1

**Comment by davidskaarup** [comment]
+1

**Comment by eMatsiyana** [comment]
+1

**Comment by davidskaarup** [comment]
If this is implemented it would be great if transport type is included as an option - e.g. either car, walking, cycling etc.

**Comment by christopherdro** [comment]
You would have to use a third party API to get that data then plug in into react native maps.
I don't think there are plans to include that functionality into this project since you can use google, mapbox or any other map service API to retrieve proper route data and plug it into this library.

**Comment by christopherdro** [comment]
This might help. https://github.com/lelandrichardson/react-native-maps/issues/52
