### ISSUE TITLE
rnpm link

### ISSUE THREAD

**Issue by arashbi** [lelandrichardson/react-native-maps#166]
When I run this command on a fresh project, after adding dependency, 'rnpm link' doesn't do anything. The process sits there and never terminates.

**Comment by christopherdro** [comment]
@arashbi This could be from some recent changes to rnpm. Could you try manually linking the libraries?

**Comment by grabbou** [comment]
Please upgrade to 1.6.1. That is indeed a bug with 1.6.

<img width="650" alt="screen shot 2016-04-08 at 09 43 02" src="https://cloud.githubusercontent.com/assets/2464966/14377127/5549fdd8-fd6e-11e5-89e8-6a3c06e8585a.png">

**Comment by christopherdro** [comment]
Thanks @grabbou!
