### ISSUE TITLE
Layer problems in android

### ISSUE THREAD

**Issue by octavioturra** [lelandrichardson/react-native-maps#169]
I've got an error with MapView when I put it under some input. 
In my app, there is a TextIput over the map, but, when I press it, it doesn't focus. The same for any other pointer events on any object over the map.
Can someone help me? Is this a bug?

**Comment by jrichardlai** [comment]
Are you putting the TextInput component after the MapView? What is the style you are using for you MapView? You can try to put a backgroundColor on the Component to see how is the component rendering.

**Comment by octavioturra** [comment]
I'm making something like Google maps. My input is insid a view that is
placed above the map with position absolute.

Em ter, 12 de abr de 2016 21:42, Jean-Richard Lai <notifications@github.com>
escreveu:

**Comment by jrichardlai** [comment]
Sorry but my questions was more about the ordering of Components: 
```
<View>
<TextInput/>
<MapView/>
</View>
```
I noticed that would behave differently than 
```
<View>
<MapView/>
<TextInput/>
</View>
```

**Comment by jrichardlai** [comment]
@octavioturra did that work for you?

**Comment by octavioturra** [comment]
I'll test it tonight

Em seg, 18 de abr de 2016 18:24, Jean-Richard Lai <notifications@github.com>
escreveu:

**Comment by octavioturra** [comment]
It worked. Thank you all.
