### ISSUE TITLE
CSS Transparent Border trick doesn't work on Android when embedded in the Map

### ISSUE THREAD

**Issue by lelandrichardson** [lelandrichardson/react-native-maps#17]
Can be seen by comparing these two gifs on the readme:

![](http://i.giphy.com/xT77XNePGnMIIDpbnq.gif) ![](http://i.giphy.com/xT77YdU0HXryvoRqaQ.gif)

The android implementation uses a canvas to draw the views to a bitmap in order to put them on the map. I wonder why the canvas draw isn't accurate with the border transparency???

**Comment by christopherdro** [comment]
I think transparent borders don't work on Android at the moment.
/cc @mkonicek

**Comment by lelandrichardson** [comment]
i'll double check, but I could have sworn these tooltips looked fine when they werent in the mapview...

relevant issues on RN: https://github.com/facebook/react-native/issues/5396 https://github.com/facebook/react-native/issues/3652

**Comment by trave7er** [comment]
not sure if this helps: https://github.com/facebook/react-native/pull/5911

**Comment by lelandrichardson** [comment]
ooOoOoOo.

I think it does! That will be awesome!

**Comment by trave7er** [comment]
great! :smiley:

**Comment by christopherdro** [comment]
@lelandrichardson 
Could this be closed since https://github.com/facebook/react-native/commit/a6a4389bf4a581de5adfe0e5dda4aa4f70438dfc was merged?

**Comment by lelandrichardson** [comment]
Yep!
