### ISSUE TITLE
How to set the Google Map zoom level to show all the markers?

### ISSUE THREAD

**Issue by gathole** [lelandrichardson/react-native-maps#175]
Once all the markers are added to the map, I want to make all the markers visible on the map. How can I set zoom level automatically to make all markers visible on the map all the time, regardless of the distance between markers and no. of markers?

**Comment by christopherdro** [comment]
You can use the `fitToElements` prop on your `<MapView/>` component.
https://github.com/lelandrichardson/react-native-maps/blob/master/docs/mapview.md#methods

**Comment by gathole** [comment]
I am getting error **"no included points"**

Here is my code and markers has 2 points:
```
  componentDidMount() {
    this.refs.map.fitToElements(true);
  }

  render() {
    var markers = this.props.markers || [];
    return (
      <MapView
        ref="map"
        style={[styles.map, this.props.mapStyle]}
        initialRegion={this.getInitialRegion(markers)}>
        {markers.map(marker => (
          <MapView.Marker 
            coordinate={marker.latlng}
            title={marker.title}
            description={marker.description}
            image={marker.image}/>
        ))}
      </MapView>
    );
  }

```

**Comment by miracle2k** [comment]
Me too. But only on Android. The same code works fine on iOS.

**Comment by christopherdro** [comment]
Could be a race condition where `this.props.markers` is not available or empty. 
Are you passing in static data?

**Comment by gathole** [comment]
Yes I am passing static data

**Comment by clarktank** [comment]
I have the same problem. Has this been fixed?

**Comment by sahir** [comment]
I have the same issue with Android. Anyone find the solution? @clarktank @gathole

**Comment by iamir4g** [comment]
Could anyone solve this problem?

**Comment by brulio93** [comment]
I solved the problem using `fitToCoordinates`, I add a `<MapView />` ref to solve the issue. 

```javascript
constructor(props) {
    super(props);
    this.state = {
       coordinates: {},
    };
    this.mapRef = null;
  }
```

Since I'm using `react-native-maps` combined with `react-native-google-places` with search included.
What I did was use a `setTimeOut` to wait for the user input 

```javascript
<MapView
         style={styles.mapStyle}
         ref={(ref) => {
            this.mapRef = ref;
         }}
         showsUserLocation
         provider={PROVIDER_GOOGLE}
         focusable
         region={{
            latitude,
            longitude,
            latitudeDelta,
            longitudeDelta,
         }}
      >
              {predictions.map((marker) => (
                <Marker
                  key={marker.placeID}
                  coordinate={marker.coordinates}
                  title={marker.title}
                  focusable
                />
              ))}
            </MapView>
```

On the search method what I did was:

```javascript
setTimeout(() => {
      const coords = predictions.map((element) => {
        return {
          latitude: element.coordinates.latitude,
          longitude: element.coordinates.longitude,
        };
      });

      this.mapRef.fitToCoordinates(coords, {
        edgePadding: {
          bottom: 200,
          right: 50,
          top: 150,
          left: 50,
        },
        animated: true,
      });
    }, 300);
```

Hope it helps!

**Comment by thuygis** [comment]
> I solved the problem using `fitToCoordinates`, I add a `<MapView />` ref to solve the issue.
> 
> ```js
> constructor(props) {
>     super(props);
>     this.state = {
>        predictions: [],
>        coordinates: {},
>     };
>     this.mapRef = null;
>   }
> ```
> 
> Since I'm using `react-native-maps` combined with `react-native-google-places` with search included.
> What I did was use a `setTimeOut` to wait for the user input
> 
> ```js
> <MapView
>          style={styles.mapStyle}
>          ref={(ref) => {
>             this.mapRef = ref;
>          }}
>          showsUserLocation
>          provider={PROVIDER_GOOGLE}
>          focusable
>          region={{
>             latitude,
>             longitude,
>             latitudeDelta,
>             longitudeDelta,
>          }}
>       >
>               {predictions.map((marker) => (
>                 <Marker
>                   key={marker.placeID}
>                   coordinate={marker.coordinates}
>                   title={marker.title}
>                   focusable
>                 />
>               ))}
>             </MapView>
> ```
> 
> On the search method what I did was:
> 
> ```js
> setTimeout(() => {
>       const coords = predictions.map((element) => {
>         return {
>           latitude: element.coordinates.latitude,
>           longitude: element.coordinates.longitude,
>         };
>       });
> 
>       this.mapRef.fitToCoordinates(coords, {
>         edgePadding: {
>           bottom: 200,
>           right: 50,
>           top: 150,
>           left: 50,
>         },
>         animated: true,
>       });
>     }, 300);
> ```
> 
> Hope it helps!

Thanks so much! I got it

**Comment by snehadange** [comment]
> > I solved the problem using `fitToCoordinates`, I add a `<MapView />` ref to solve the issue.
> > ```js
> > constructor(props) {
> >     super(props);
> >     this.state = {
> >        predictions: [],
> >        coordinates: {},
> >     };
> >     this.mapRef = null;
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Since I'm using `react-native-maps` combined with `react-native-google-places` with search included.
> > What I did was use a `setTimeOut` to wait for the user input
> > ```js
> > <MapView
> >          style={styles.mapStyle}
> >          ref={(ref) => {
> >             this.mapRef = ref;
> >          }}
> >          showsUserLocation
> >          provider={PROVIDER_GOOGLE}
> >          focusable
> >          region={{
> >             latitude,
> >             longitude,
> >             latitudeDelta,
> >             longitudeDelta,
> >          }}
> >       >
> >               {predictions.map((marker) => (
> >                 <Marker
> >                   key={marker.placeID}
> >                   coordinate={marker.coordinates}
> >                   title={marker.title}
> >                   focusable
> >                 />
> >               ))}
> >             </MapView>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > On the search method what I did was:
> > ```js
> > setTimeout(() => {
> >       const coords = predictions.map((element) => {
> >         return {
> >           latitude: element.coordinates.latitude,
> >           longitude: element.coordinates.longitude,
> >         };
> >       });
> > 
> >       this.mapRef.fitToCoordinates(coords, {
> >         edgePadding: {
> >           bottom: 200,
> >           right: 50,
> >           top: 150,
> >           left: 50,
> >         },
> >         animated: true,
> >       });
> >     }, 300);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope it helps!
> 
> Thanks so much! I got it

But its working only on specific marker not all marker?
