### ISSUE TITLE
[Android] Black background on ScrollView

### ISSUE THREAD

**Issue by matiascba** [lelandrichardson/react-native-maps#177]
Hello, first of all, Excellent Work!, 

I have a problem in Android when i put the MapView inside a ScrollView, when the screen scroll
a black background appears.

Here is my code:

```
<ScrollView style={{flex:1}}>
             
            <View style={{height:1500}}>  

              <View style={{ height:200 }} > 
              </View>
             
              <View style={{ height:112 }} > 
                <MapView  style={{ height:112}}   
                          pitchEnabled={false}
                          scrollEnabled={false} 
                          zoomEnabled={false} 
                          rotateEnabled={false}
                          initialRegion={{   
                               latitude: 37.78825,
                                longitude: -122.4324,
                                latitudeDelta: 0.0922,
                                longitudeDelta: 0.0421,
                            }} >  
                  </MapView>  
                </View> 
            </View> 
         </ScrollView>
```
 

This is what i see:

![problemmapgit](https://cloud.githubusercontent.com/assets/4285148/14473462/96bd6d6e-00ce-11e6-9d38-59ef592fa658.gif)

**Comment by jrichardlai** [comment]
this is linked to to https://github.com/lelandrichardson/react-native-maps/pull/91

**Comment by matiascba** [comment]
@jrichardlai Thanks!, 

I will close this issue and follow the evolution of the PR that you mention #91

**Comment by maximedb** [comment]
Is there anyway to make it white instead ?

**Comment by gracevenkat** [comment]
did you solve this problem? please give the solution.

**Comment by jyoo** [comment]
Is this solved now? I still see this when I use react-native-maps with scrollview on Android.

**Comment by sonalvish** [comment]
Hi,

I am still getting this issue with  "react-native-maps": "^0.27.1"
