### ISSUE TITLE
Implement draggable markers

### ISSUE THREAD

**Issue by lelandrichardson** [lelandrichardson/react-native-maps#18]

**Comment by christopherdro** [comment]
@lelandrichardson This might help.
https://github.com/facebook/react-native/commit/b8aac8b77a6b0737c23fd7d68c7b83ff068f5c4c

**Comment by lelandrichardson** [comment]
yah i saw that... :+1:

**Comment by lelandrichardson** [comment]
implemented in 0.2.0
