### ISSUE TITLE
transparency for polygons 

### ISSUE THREAD

**Issue by ZigGreen** [lelandrichardson/react-native-maps#183]
Is there a way I set some transparency level to `MapView.Circle` or `MapView.Polygon`?

**Comment by jrichardlai** [comment]
You can use rgba color `rgba(r,g,b,0.5)` for `fillColor` or `strokeColor`

**Comment by ZigGreen** [comment]
cool!

**Comment by CandyOgre** [comment]
@jrichardlai what If I have color in `#ee82ee` format? How can I set transparency?

**Comment by incarnateTheGreat** [comment]
@jrichardlai  holy crap. such a simple solution! Thank you!

**Comment by mMarcos208** [comment]
It isn't work for IOS.

  ```

         <Polygon
            key={polygon.id}
            coordinates={polygon.paths}
            strokeWidth={2}
            strokeColor={polygon.options.strokeColor}
            fillColor={ hexToRGBA(polygon.options.fillColor, '0.5')}
            tappable
          />

```

![image](https://user-images.githubusercontent.com/14351491/82688680-a858a880-9c2f-11ea-8111-1a64b818d911.png)
