### ISSUE TITLE
Cocoapods pod install throws error

### ISSUE THREAD

**Issue by zachcowell** [lelandrichardson/react-native-maps#184]
```
[ios] > pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.8 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Fetching podspec for `react-native-maps` from `../node_modules/react-native-maps`
[!] No podspec found for `react-native-maps` in `../node_modules/react-native-maps`
```

I installed react-native-maps with npm. When I went inside the `node_modules/react-native-maps` directory, there was no podspec file. I downloaded the file directly from the repo and placed it in the above directory and it seemed to work.

**Comment by jrichardlai** [comment]
Which version of cocoapods are you using? in which folder are you running pod install ?

**Comment by christopherdro** [comment]
@zachcowell  The added podspec hasn't been published on a new version.
You can try pulling from master for now.

/cc @lelandrichardson 
Should we get a minor release of with recent additions?

**Comment by lelandrichardson** [comment]
Done!  

0.3.2 should be on npm
