### ISSUE TITLE
Does the example app work on android?

### ISSUE THREAD

**Issue by npomfret** [lelandrichardson/react-native-maps#185]
I just tried to run the example app on a physical lollipop device and it crashed immediately with this:

    /com.airmapsexplorer E/ReactNativeJS: undefined is not a function (evaluating 'EventPluginHub.injection.injectInstanceHandle(ReactInstanceHandles)')

Any ideas?

**Comment by bosung90** [comment]
I am getting exactly same error on Galaxy S6
Using commit#1004b03

**Comment by KarlosQ** [comment]
Same problem in Redmi Note 3 (5.1.1)

**Comment by kanerogers** [comment]
I'm having this exact same message too, but I'm not using react-native-maps: stumbled on this page via Google. I'd just upgraded my RN project from 0.20 to 0.24 - some issue there?

**Comment by jrichardlai** [comment]
Which version of RN are you using and which version of React is it?

**Comment by kanerogers** [comment]
RN 0.24, React 0.14.8.

I eventually got it working by clearing the npm cache and deleting the
packager's cache.

K

**Comment by felipecsl** [comment]
The example app works fine on android now

**Comment by kanerogers** [comment]
Thanks! 😀
