### ISSUE TITLE
Disable android map marker click auto center

### ISSUE THREAD

**Issue by dwaligora** [lelandrichardson/react-native-maps#199]
Hey guys,

First of all, I love your lib and job you do here!!! Amazing and works like a charm!

I am working on custom callout implementation for my map and I was wondering if it the lib support disabling android map marker auto center on click? I could not make it work and find any option which might allow that, did I miss something or it isn't supported?

Thanks in advance for you help and once again, great lib!

**Comment by jrichardlai** [comment]
Hello @dwaligora unfortunately it is not currently possible to disable the auto centering on click :(. It seems to be possible with this code http://stackoverflow.com/questions/15925319/how-to-disable-android-map-marker-click-auto-center

**Comment by dwaligora** [comment]
thanks @jrichardlai

**Comment by mvaivre** [comment]
@jrichardlai : I try to reproduce something similar to this example: https://github.com/lelandrichardson/react-native-maps/blob/master/example/examples/AnimatedViews.js

The difference is that the animation and the recentering of the map is triggered by a press on a marker.
According to your answer, it's not possible to have a fluid motion after the tap, because the default recentering will be called first?

Thanks for your answer!

**Comment by jasongaare** [comment]
Anyone who is still discovering this issue, there is now a `moveOnMarkerPress` prop that can be set to `false` to disable this.

**Comment by braj008** [comment]
@jasongaare How/Where to use this property?

**Comment by jasongaare** [comment]
Should be very top-level on your map component like so:

```
<MapView
          ref="map"
          style={{ ...StyleSheet.absoluteFillObject }}
          initialRegion={region}
          onRegionChange={() => {
            if (!this.state.hasDraggedMap) {
              this.setState({ hasDraggedMap: true });
            }
          }}
          onRegionChangeComplete={this.onRegionChangeComplete}
          pitchEnabled={false}
          toolbarEnabled={false}
          rotateEnabled={false}
          loadingEnabled
          showsIndoors={false}
          showsTraffic={false}
          showsMyLocationButton={false}
          showsCompass
          mapType={this.state.layer}
          moveOnMarkerPress={false}
          showsUserLocation
          showsPointsOfInterest={false}
        >
```

**Comment by micaelsf** [comment]
> Anyone who is still discovering this issue, there is now a `moveOnMarkerPress` prop that can be set to `false` to disable this.

This does not work for me, got react-native-maps version 0.21. Applied that property at MapView element, just like this:

**Comment by bpred754** [comment]
Anyone know how to get this behavior on iOS? I am trying to lock the map, but when a marker near the edge gets selected, the map moves.

**Comment by roysG** [comment]
any update?

**Comment by SystemBlad** [comment]
Hi @bpred754 , Have you solved de issue in ios?

**Comment by bpred754** [comment]
Nope, I wasn’t able to figure this one out, unfortunately.

**Comment by mohmdalfaha** [comment]
I faced the same issue but I used @jasongaare hint and worked like a charm on both android and iOS. IDK what you guys are facing exactly @bpred754 @roysG @SystemBlad ?

**Comment by KishoreMayank** [comment]
Still does not work on iOS. Would appreciate any help with figuring this out.

**Comment by arwysyah** [comment]
can anyone tell me , how to focus on marker when latitude and longitude moved, 
i am using google autocomplete, so i want when someone press the google location lists, the focus also change on new marker movements

**Comment by tucomel** [comment]
override the clicklistener and return true
 ```java
    @Override
    public boolean onMarkerClick(@NonNull Marker marker) {
     
        return true;
    }
```

**Comment by kafeelkhatri** [comment]
Simple. Add moveOnMarkerPress prop to MapView and set it to false.

<MapView
      moveOnMarkerPress={false}
>

**Comment by diegoandino** [comment]
Solution given is still not working on IOS for me. Unsure what the problem is.
