### ISSUE TITLE
Blank screen on usage

### ISSUE THREAD

**Issue by nillo** [lelandrichardson/react-native-maps#20]
Hi there, first of all thanks for the great work.

A question though: when implementing react-native-apps, and i use rnpm link, the project files are added to my project, but when running the  code, i gives me a blank screen without any error what so ever, not i xcode , not in the chrome debugger. 

(Find the libairmaps.a file) blank screen remains.

Any suggestions?

**Comment by nillo** [comment]
I got it to work after uninstalling and reinstalling the package, and redo the rnpmlink

**Comment by roflmaolol** [comment]
I had to style to the MapView containing its size

```
        <View>
            <MapView
                initialRegion={{
                  latitude: 37.78825,
                  longitude: -122.4324,
                  latitudeDelta: 0.0922,
                  longitudeDelta: 0.0421,
                }}
                style={styles.map}
            />
        </View>

const styles = StyleSheet.create({
  map: {
    flex: 1,
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
});

```
