### ISSUE TITLE
iOS polyline coordinate update Not showing new route

### ISSUE THREAD

**Issue by eMatsiyana** [lelandrichardson/react-native-maps#200]
I have the following for the Polyline inside my MapView.

`<MapView.Polyline` coordinates={this.state.routeCoords} strokeColor={'#55C2DD'} strokeWidth={4}/>

It works perfectly well and updates with the new route for Android.

But when I change the state.routeCoords for iOS... The new route is not rendered. It keeps showing the old route.

How else can I handle this?

**Comment by jrichardlai** [comment]
Hello, which version of react-native-maps are you using? `v0.3.2` should have this fixed, otherwise is it possible to see an example of code?

**Comment by eMatsiyana** [comment]
Hello, 

I was on v0.3.1.

v0.3.2 Works perfectly well for this...

Thank you!
