### ISSUE TITLE
Map not displaying on Android Device

### ISSUE THREAD

**Issue by ManrajGrover** [lelandrichardson/react-native-maps#202]
Not able to display Map on Android Device. I haven't tried it on emulator but will do and update the issue.

Chrome Debugger has this output.
```
ExceptionsManager.js:76Warning: Native component for "AIRMapMarker" does not exist
ExceptionsManager.js:76 Warning: Native component for "AIRMapPolyline" does not exist
ExceptionsManager.js:76 Warning: Native component for "AIRMapPolygon" does not exist
ExceptionsManager.js:76 Warning: Native component for "AIRMapCircle" does not exist
ExceptionsManager.js:76 Warning: Native component for "AIRMapCallout" does not exist
ExceptionsManager.js:76 Warning: Native component for "AIRMap" does not exist
AppRegistry.js:82 Running application "uiexp" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
root.js:33 here!
root.js:43 ListViewDataSource {_dataBlob: null, _dirtyRows: Array[0], _dirtySections: Array[0], _cachedRowCount: 0, rowIdentities: Array[0]…}
root.js:61 Maps
```

Let me know if source code is required.

**Comment by jrichardlai** [comment]
Hello, can you double check that the library is [linked and installed properly](https://github.com/lelandrichardson/react-native-maps/blob/master/docs/installation.md#android)? It seems that it can't find the native components.

**Comment by ManrajGrover** [comment]
My bad! I missed a line, hence resulting to this. Thank you! :)

**Comment by eangfmbs** [comment]
jhjkh

**Comment by Jaafar-abusair** [comment]
which line you missed I have the same problem

**Comment by Denys-Bushulyak** [comment]
Have the same problem and all checked several times but unsuccessful.

**Comment by Jaafar-abusair** [comment]
The solution is simple but not mentioned in the tutorial, you need to return the map package in your main android activity,  same place where you return the react native packages

**Comment by Denys-Bushulyak** [comment]
> The solution is simple but not mentioned in the tutorial, you need to return the map package in your main android activity, same place where you return the react native packages
Please, little bit more about this if you may!

**Comment by Jaafar-abusair** [comment]
Im sorry I don't have the code right now, but in the Android project in the Application.java class there is a method returning Array<reactpackage>, inside this. Method you should return the map package

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage()
      );
    }

**Comment by Denys-Bushulyak** [comment]
@Jaafar-abusair, thank you very much for so far help and you spent time - you helped me!
