### ISSUE TITLE
Cant find google play when building apk

### ISSUE THREAD

**Issue by sammosampson** [lelandrichardson/react-native-maps#205]
Hi, I have installed all of the required android libraries including the play services and repository etc. But I Still get the following when assembling the release. Any ideas?

A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-maps'.
   > Could not resolve all dependencies for configuration ':react-native-maps:_debugCompile'.
      > Could not find com.google.android.gms:play-services-base:8.4.0.
        Searched in the following locations:
            file:/Users/Papa/.m2/repository/com/google/android/gms/play-services-base/8.4.0/play-services-base-8.4.0.pom
            file:/Users/Papa/.m2/repository/com/google/android/gms/play-services-base/8.4.0/play-services-base-8.4.0.jar
            https://jcenter.bintray.com/com/google/android/gms/play-services-base/8.4.0/play-services-base-8.4.0.pom
            https://jcenter.bintray.com/com/google/android/gms/play-services-base/8.4.0/play-services-base-8.4.0.jar
            file:/Users/Papa/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-base/8.4.0/play-services-base-8.4.0.pom
            file:/Users/Papa/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-base/8.4.0/play-services-base-8.4.0.jar
            file:/Users/Papa/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-base/8.4.0/play-services-base-8.4.0.pom
            file:/Users/Papa/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-base/8.4.0/play-services-base-8.4.0.jar
        Required by:
            Mobile:react-native-maps:unspecified
      > Could not find com.google.android.gms:play-services-maps:8.4.0.
        Searched in the following locations:
            file:/Users/Papa/.m2/repository/com/google/android/gms/play-services-maps/8.4.0/play-services-maps-8.4.0.pom
            file:/Users/Papa/.m2/repository/com/google/android/gms/play-services-maps/8.4.0/play-services-maps-8.4.0.jar
            https://jcenter.bintray.com/com/google/android/gms/play-services-maps/8.4.0/play-services-maps-8.4.0.pom
            https://jcenter.bintray.com/com/google/android/gms/play-services-maps/8.4.0/play-services-maps-8.4.0.jar
            file:/Users/Papa/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-maps/8.4.0/play-services-maps-8.4.0.pom
            file:/Users/Papa/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-maps/8.4.0/play-services-maps-8.4.0.jar
            file:/Users/Papa/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-maps/8.4.0/play-services-maps-8.4.0.pom
            file:/Users/Papa/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-maps/8.4.0/play-services-maps-8.4.0.jar
        Required by:
            Mobile:react-native-maps:unspecified

**Comment by jrichardlai** [comment]
Does this works on your simulator? Not sure what is happening here if you installed properly google services, maybe they are not up to date?

**Comment by sammosampson** [comment]
my sdk seems to be located user/local/Cellar/android-sdk/24.4.1 the locations that the build was looking (see above) doesn't match that at all. Any ideas

**Comment by sammosampson** [comment]
If i look in the folders that the build is looking in I can see version 8.3 but not 8.4 that it is asking for. If i run the android package manager there are no updates available for the packages in question. Any ideas y that would be?

**Comment by sammosampson** [comment]
So as it would seem I have two Android SDK's installed it seemed one in usr/local/Cellar/android-sdk/24.4.1 and also in /Users/Papa/Library/Android/sdk/. the former holds all the 8.4 stuff, the latter only 8.3. Copying the 8.4 stuff over into the latter location allows me to build But does anyone know how I got into this situation? And how I remedy it?

**Comment by christopherdro** [comment]
Maybe you had installed the sdk manually and through another source like homebrew?

Closing this for now. Feel free to re-open it if the problem persists.

**Comment by ahmed1490** [comment]
@christopherdro instllaed via homebrew and same error.

is homebrew not recommended
