### ISSUE TITLE
How do I turn a marker around?

### ISSUE THREAD

**Issue by ACCTFORGH** [lelandrichardson/react-native-maps#206]
I would need to turn the marker to different directions. Is there any way I can realize this feature?

**Comment by DennisMG** [comment]
You can use the **transform** property of the view. here's and [example](https://rnplay.org/apps/TTCZcA)

**Comment by christopherdro** [comment]
@DennisMG 👍  Thanks for providing an answer!
Awesome example! 😉

**Comment by ACCTFORGH** [comment]
@DennisMG Thanks!
