### ISSUE TITLE
Deprecation warnings using latest version of React Native

### ISSUE THREAD

**Issue by benhoyt** [lelandrichardson/react-native-maps#208]
We've just upgraded to the latest version of React Native (0.25), and in dev mode we're seeing "yellow box" warnings like 'Warning: ReactNative.createElement is deprecated. Use React.createElement from the "react" package instead.' This deprecation warning was added in version 0.25 -- see [release notes](https://github.com/facebook/react-native/releases/tag/v0.25.0) and the [relevant commit](https://github.com/facebook/react-native/commit/2eafcd45dbd42f750df1ab9aa3770fed5cdf11ae).

As of now, 0.25 is still labelled "pre-release", but it'll be the latest official version any day now, so these warnings will soon affect everyone using react-native-maps with the latest version of React Native.

To fix, you just need to use `createClass` from the "react" package instead of from "react-native". The patch below fixes it for me (but you'd need to do something similar to the other components too):

```
--- MapView.js	Wed May  4 10:03:49 2016
+++ MapView - Copy.js	Wed May  4 09:30:16 2016
@@ -1,6 +1,7 @@
 'use strict';
 
-var React = require('react-native');
+var React = require('react');
+var ReactNative = require('react-native');
 var {
   EdgeInsetsPropType,
   NativeMethodsMixin,
@@ -11,7 +12,7 @@ var {
   requireNativeComponent,
   NativeModules,
   PropTypes,
-} = React;
+} = ReactNative;
 
 var MapMarker = require('./MapMarker');
 var MapPolyline = require('./MapPolyline');
@@ -336,7 +337,7 @@ var MapView = React.createClass({
   },
 
   _getHandle: function() {
-    return React.findNodeHandle(this.refs.map);
+    return ReactNative.findNodeHandle(this.refs.map);
   },
 
   _runCommand: function (name, args) {
```

**Comment by benhoyt** [comment]
Also, I believe you've been able to use react's `createClass` for the last several versions of React Native (not sure exactly how far back), so making these changes won't penalize users on older versions of React Native.

**Comment by jrichardlai** [comment]
Hello, thanks for submitting the issue it seems that someone did a PR for it https://github.com/lelandrichardson/react-native-maps/pull/192 do you know which version minimum supports this?

**Comment by benhoyt** [comment]
Ah yes, PR #192 looks great. No, sorry, I'm not sure exactly what version minimum -- my gut says quite a few versions back, but I don't know.

**Comment by christopherdro** [comment]
Fixed via c86db86ae201c994d0434364d1f791065aa43734

**Comment by benhoyt** [comment]
Thanks, @christopherdro. Care to push out a new npm release now that React Native 0.25 is official?

**Comment by christopherdro** [comment]
@lelandrichardson How do you feel about releasing another version?

**Comment by benhoyt** [comment]
@lelandrichardson Ping on whether you're able to push out a new release to get rid of the yellow box warnings with the latest version of React Native?

**Comment by srhise** [comment]
+1 on new version push. I am debugging my app and keep getting this message :)

**Comment by christopherdro** [comment]
version 0.4.0 was published yesterday

**Comment by benhoyt** [comment]
Oh nice, thanks! Sorry for not checking before commenting.
