### ISSUE TITLE
Get markers of specific region

### ISSUE THREAD

**Issue by DanDance** [lelandrichardson/react-native-maps#210]
Is there an opportunity to get all markers of specific region?

**Comment by christopherdro** [comment]
@DanDance This is not something offered through this library. However, you can achieve this by creating your own region filter and apply it to your array of markers before passing them as a prop to the map view.

**Comment by DanDance** [comment]
but is maybe possible to define does marker belongs to region using longitude and latitude deltas?
For example i have marker with {lat, lng} and region {lat, lng, latdelta, lngdelta}. Is there a formula or something where i can use this data to check if marker belongs to region. I just can't understand how exactly I can do it.

Thank you.
