### ISSUE TITLE
How to insert button in custom marker 

### ISSUE THREAD

**Issue by Squek** [lelandrichardson/react-native-maps#211]
Hi sir

   I Try to insert TouchableOpacity in my custom map marker, I can see the TouchableOpacity in the marker, but button event doesn't work!
where the problem is? thanks

My code as follows
<MapView.Marker  coordinate={{ latitude: LATITUDE, longitude: LONGITUDE,}} >

    <MapView.Callout tooltip>
        <CustomCallout>
           <TouchableOpacity onPress={this.testfunction} style={[styles.bubble, styles.button]}>
              <Text>Button</Text>
           </TouchableOpacity>
        </CustomCallout>
    </MapView.Callout>
</MapView.Marker>

**Comment by jrichardlai** [comment]
Is this for Android or iOS ?

**Comment by jojonarte** [comment]
Having the same issue

**Comment by heydabop** [comment]
Android map callouts don't support buttons inside of them, only an onPress event for the entire callout. This is a limitation of the Google Maps library on Android and react-native-maps can't do anything about it.

**Comment by jrichardlai** [comment]
Thanks for the answer @heydabop, closing the issue.

**Comment by samassango** [comment]
@heydabop Thanks man I had the same challenge.
