### ISSUE TITLE
View size is too small after padding

### ISSUE THREAD

**Issue by jojonarte** [lelandrichardson/react-native-maps#216]
Hey I'm having this weird issue right now. This is my code if it helps.

`
import React, {
  Component,
  StyleSheet,
  Text,
  TouchableHighlight,
  View,
  Image
} from 'react-native';

import images from '../config/constants/images'
import MapView from 'react-native-maps';

class HomePage extends Component {

  constructor(props){
    super(props);
    this.state = {
         region: {
              latitude: 37.78825,
              longitude: -122.4324,
              latitudeDelta: 0.0922,
                  longitudeDelta: 0.0421,
            },
        markers:[
        {
          latlng:{
              latitude: 37.78825,
                longitude: -122.4324,
            },
          title:"TEST",
          description:"TAE"
        }
        ]
      };
    }

      onRegionChange(region) {
        this.setState({ region });
      }

  render(){
    return(
      <Image source={images.BACKGROUND} style={styles.container}>
          <View style={styles.view_container}>
            <MapView 
                  region={this.state.region}
                  onRegionChange={this.onRegionChange}
                >
                  {this.state.markers.map(marker => (
                    <MapView.Marker 
                      coordinate={marker.latlng}
                      title={marker.title}
                      description={marker.description}/>
                  ))}
                </MapView>
          </View>
      </Image>
      );
  }

}

const styles = StyleSheet.create({
    view_container:{
      flex:1,
      flexDirection:'column'

    },
     container: {
        flex: 1,
        width: null,
        height: null,
        justifyContent: 'center',
        alignItems: 'center'
    },
});

module.exports = HomePage;

`

![react-native-mapview](https://cloud.githubusercontent.com/assets/11880365/15098831/f5c05a88-1578-11e6-8fb3-eaeafc2b8503.png)

**Comment by jojonarte** [comment]
fixed it.

**Comment by ShaikhKabeer** [comment]
Hey, we are also facing this. How did you fixed this ?

**Comment by chakrihacker** [comment]
can you refer the pull request where you fixed it??
