### ISSUE TITLE
Duplicate module name: TouchHistoryMath

### ISSUE THREAD

**Issue by warmwater** [lelandrichardson/react-native-maps#222]
Under OS X with node 6.0.0
$ git clone react-native-maps
$ cd react-native-maps/example
$  npm install

when i run example with  "react-native run-ios" or "react-native start" command

it shows error messages:

````
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: TouchHistoryMath
  Paths: /Users/bigdav/Projects/react-native-maps/example/node_modules/react/lib/TouchHistoryMath.js collides with /Users/bigdav/Projects/react-native-maps/example/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: TouchHistoryMath
  Paths: /Users/bigdav/Projects/react-native-maps/example/node_modules/react/lib/TouchHistoryMath.js collides with /Users/bigdav/Projects/react-native-maps/example/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/Users/bigdav/Projects/react-native-maps/example/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:160:15)
    at /Users/bigdav/Projects/react-native-maps/example/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:125:25
    at process._tickCallback (internal/process/next_tick.js:103:7)
~
Process terminated. Press <enter> to close the window

````

**Comment by christopherdro** [comment]
@warmwater I don't think the issue is with this library.

I would try clearing your node modules and re-installing. Sounds like a conflict of having 2 versions of react installed.

**Comment by warmwater** [comment]
> Paths: /Users/bigdav/Projects/react-native-maps/example/node_modules/react/lib/TouchHistoryMath.js collides with /Users/bigdav/Projects/react-native-maps/example/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js

but it seems like the collision happens in the node_modules folder of react-native-maps

I did git clone the brand new react-native-maps folder then mpn install, it still happens

**Comment by mvaivre** [comment]
@warmwater what version of React do you use?

**Comment by warmwater** [comment]
according to package.json of example, it uses latest version of react

in my case:
react v15.0.2
react-native 0.25.1
react-native-maps 0.4.0

**Comment by mvaivre** [comment]
@warmwater Can you just try to see if using React `0.14.5` solves your problem?

**Comment by warmwater** [comment]
@mvaivre <0.14.5> solves the problem, thanks
