### ISSUE TITLE
Android dependency not available

### ISSUE THREAD

**Issue by changchup** [lelandrichardson/react-native-maps#229]
the following dependency is not available

https://jcenter.bintray.com/com/airbnb/android/react-native-maps/0.0.1/react-native-maps-0.0.1.pom
https://jcenter.bintray.com/com/airbnb/android/react-native-maps/0.0.1/react-native-maps-0.0.1.jar

Can you suggest another location?

**Comment by msied** [comment]
Seconding this request. Urgently needed for this to work on Android.

**Comment by felipecsl** [comment]
This has been just uploaded to maven central. it will be available as:
`compile 'com.airbnb.android:react-native-maps:0.4.1`

**Comment by changchup** [comment]
thank you!

**Comment by dslounge** [comment]
Might want to update the installation documentation :)
