### ISSUE TITLE
Android: installation doesn't work following the instructions

### ISSUE THREAD

**Issue by MrMotski** [lelandrichardson/react-native-maps#236]
I followed the installation instructions for android.

When trying to run the app, it fails with the following message:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.airbnb.android:react-native-maps:0.0.1.
     Searched in the following locations:
....

**Comment by felipecsl** [comment]
the correct version is `0.5.0` instead of `0.0.1`. I'm fixing the docs now

**Comment by xphaul** [comment]
@felipecsl im still getting this error even though I have followed all the instructions on your installation guide

**Comment by felipecsl** [comment]
which error are you getting?

**Comment by xphaul** [comment]
Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.facebook.react:react-native:0.25.1.

**Comment by xphaul** [comment]
my react-native version is 0.20.0

**Comment by felipecsl** [comment]
you should change your `package.json` to use `0.25.1`then

**Comment by xphaul** [comment]
sorry . if this is kinda a newbie question . im just starting with react-native . but wont changing that package json will upgrade my react-native package? thanks

**Comment by felipecsl** [comment]
no problem. yes it will

**Comment by xphaul** [comment]
okay thanks

**Comment by xphaul** [comment]
it still prompts the same error .
I have "react-native": "^0.25.1" on my package.json
and 
react-native@0.25.1 on my NPM list

**Comment by devux** [comment]
Have you tried npm install after adding 0.25.1 in package.json
