### ISSUE TITLE
Free draw on map ? 

### ISSUE THREAD

**Issue by tinygipxy** [lelandrichardson/react-native-maps#238]
Hi, are there anyway to lock map and perform free draw by finger on Map screen ?

**Comment by jrichardlai** [comment]
This PR allows it https://github.com/lelandrichardson/react-native-maps/pull/159

**Comment by tinygipxy** [comment]
Thank you Jrichardlai, I'll try it

**Comment by christopherdro** [comment]
Added via 61f43a1ce25bbb642c81610bcbfd53095380033b
