### ISSUE TITLE
Animated.Region undefined constructor

### ISSUE THREAD

**Issue by KelseyRegan** [lelandrichardson/react-native-maps#24]
I may be missing something.  How is Animated.Region supposed to be referenced?  I can't seem to get it bundled at all.  It isn't one of the module.exports.  I see it in the examples, but can't use it in my project.

Any help is appreciated!

**Comment by lelandrichardson** [comment]
See instructions here: https://github.com/lelandrichardson/react-native-maps#using-with-the-animated-api

You need to modify your AnimatedImplementation.js file. Let me know if you need any more help.

**Comment by erickreutz** [comment]
@lelandrichardson  Is there a place with an example of modifying the `AnimatedImplementation.js`? This step doesn't seem to be in the README.

**Comment by erickreutz** [comment]
Never mind. Found it!

**Comment by agumack** [comment]
@erickreutz how fix it? thanks!

**Comment by seasick** [comment]
@erickreutz, use `MapView.AnimatedRegion` instead of `Animated.Region`
