### ISSUE TITLE
Markers don't show on ios device but works on simulator

### ISSUE THREAD

**Issue by damienadermann** [lelandrichardson/react-native-maps#244]
I've just migrated my app to use this package from the built in MapView but I'm hitting an issue when running on the device. All works great in the simulator but when I run on my iPhone 6 no markers appear. 

I'm using 
`
"react-native": "^0.25.1",
"react-native-maps": "^0.4.2",
`

Code looks like
```jsx
<MapView
      style={styles.map}
      initialRegion={mapRegion}
      onRegionChange={updateRegion}
      onRegionChangeComplete={updateRegion}>
      {restaurants.map(r =>
        <Marker
          key={r.id}
          title={r.name}
          description={r.address}
          coordinate={r.location}
          onCalloutPress={() => goToRestaurant(r.restaurant)}>
          <RoundedLogo restaurant={r} radius={20} />
        </Marker>
      )}
    </ MapView>
```

also doesn't work when I use a self closing Marker.

Both work on the simulator

**Comment by jrichardlai** [comment]
Can you use the chrome debugger when running on iOS to see if `restaurants` is not empty?

**Comment by damienadermann** [comment]
Yeah restaurants do exist. I didn't check in chrome but I did an alert in the loop and alerts were being shown. I also have a list view showing the same data and that shows correctly on both simulator and device.

**Comment by damienadermann** [comment]
Problem solved. I was using Immutable Records for the coordinates. Converting to Pojo's fixed it. I don't understand why but for anyone hitting this problem using a plain coording object worked

**Comment by shridharmalagi** [comment]
how you are passing coordinates?
