### ISSUE TITLE
How to turn on Traffic layer on map? 

### ISSUE THREAD

**Issue by Squek** [lelandrichardson/react-native-maps#247]
As title, is it possible on Android / iOS ?

**Comment by christopherdro** [comment]
This feature is only available natively on Android with google maps.

Here is a reference to the documentation.
https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html#public-methods

This should be fairly easy to add. The implementation should be similar to how `pitchEnabled` and `scrollEnabled` are setup.

Want to take a shot at adding this feature and submitting a PR?

**Comment by christopherdro** [comment]
This is actually already implement. Use the 'showsTraffic' prop on MapView.

**Comment by Squek** [comment]
Thanks!

**Comment by WrathChaos** [comment]
Hello, after 2 years how can I use showsTraffic feature on iOS? Is that still unavailable?
Thank you

**Comment by WrathChaos** [comment]
Hello, after 2 years how can I use showsTraffic feature on iOS? Is that still unavailable?
Thank you

**Comment by Tom-Sziler** [comment]
Update from 2021- It looks like showsTraffic does work on iOS now.
