### ISSUE TITLE
npm repo is outdated

### ISSUE THREAD

**Issue by allthetime** [lelandrichardson/react-native-maps#250]
version 0.4.2  is the latest on npm, can we get an update?

**Comment by jrichardlai** [comment]
Sorry probably won't be updated for a few weeks. Best way would be to use the sha you want in package.json:  `git://github.com/lelandrichardson/react-native-maps#faa19067fd59169b1dcd3eea43f3051a6edbee1c`

**Comment by allthetime** [comment]
`npm install lelandrichardson/react-native-maps` works as well :)

I just wanted to report incase you guys weren't aware!
