### ISSUE TITLE
onDrawComplete / onLoad ?

### ISSUE THREAD

**Issue by allthetime** [lelandrichardson/react-native-maps#251]
I'm currently implementing a map and looking through the docs it doesn't look like there is a clear way to accomplish this.

Basically, when you first load a map, it shows the grid in the background and pieces the map together. 

Is there an event (js or native) that fires when the map is finished drawing, so that the map could be hidden until it is drawn properly? The region change events fire too quickly and can't be used.

**Comment by allthetime** [comment]
nevermind, i see there is already an almost identical issue

**Comment by ChrisWphoto** [comment]
Not sure which issue @allthetime is referring to but [this page in the docs](https://github.com/airbnb/react-native-maps/blob/master/docs/mapview.md) does list a `onMapReady` callback, that I couldn't get to work.
