### ISSUE TITLE
memory leak on multiple renders

### ISSUE THREAD

**Issue by allthetime** [lelandrichardson/react-native-maps#253]
Hey, I just implemented a MapView and have run into a very serious memory problem. I have two views right now, connected with a Navigator, and the MapView is on the second view. If I go back and forth a couple of times, memory usage climbs up consistently and then the app crashes. Removing the MapView component stops this from happening. 

I've read that there might be memory issues with Navigator, so I also tried manually rendering components and still experience the same problem (it takes a few more presses to make it happen though)

I have also tested simply re-rendering the MapView without ever switching routes/components and the issue persists.

Has anyone else experienced this? Is there a way to render/cache the MapView that will stop it from piling up the heap?

**Comment by jrichardlai** [comment]
Are you testing in the simulator? The issue appears in the simulator for me but when putting on the phone it seems fine.

For caching there is a PR ongoing https://github.com/lelandrichardson/react-native-maps/pull/91 I have been using it for a while.

**Comment by allthetime** [comment]
No this is on device. I didn't have a problem on simulator strangely enough. I will do a bit more testing though, because I haven't checked simulator since I noticed the issue.

Just for fun, here's a memory graph after rendering the map a few times and then just leaving the app open. You can see the beginning is a little choppy, that is where I was actually doing things, the rest is simply leaving the app open:

![](http://imgur.com/GIUhcvG.jpg)

But, I'll give that PR a shot, thanks!

Out of curiosity, what version of react-native are you using? I'm upgrading from 24 to 26 right now to see if there is any improvement... will report back if anything changes.

**Comment by allthetime** [comment]
Hmm, just went through hell upgrading to newest react-native, but I made it haha. 

Memory use isn't climbing/leaking when idling, but the render issue is still there.

Simply zooming and moving the map around sends usage through the roof. I just made it jump 100MB by zooming out. Is this expected?

**Comment by allthetime** [comment]
I have tested in Android and the problem does not exist, so this seems iOS specific. 

It turns out this problem affects the standard MapView as well. I have left a much clearer and detailed issue on the main react-native repo: https://github.com/facebook/react-native/issues/7763 I believe it is relevant to this project as well. Regardless of using this or the standard module I get about the same results. 

If you go here: https://rnplay.org/apps/HY_p-w you can reproduce the crash. On rnplay it doesn't crash, but after about 10 clicks back and forth the app reloads even though the code hasn't changed and resets to its original state... This is when it crashes on my device. I don't have the same problem in simulator, but that might be because the memory limit seems to be my computer's memory limit (16GB)

Please, if you have a moment, take a look at the rnplay link and let me know if you notice anything. I have made it as simple as possible for my use case.

**Comment by zhbanton** [comment]
@allthetime, did you ever figure out a fix for this?

**Comment by jeffreymendez1993** [comment]
still noticing this.

**Comment by piotrekc** [comment]
We are experiencing the same issue. Any idea how to resolve it?

**Comment by N1ghtly** [comment]
We are experiencing this as well... Makes the lib barely usable for us :(
