### ISSUE TITLE
Unusual behavior updating region 

### ISSUE THREAD

**Issue by KGALLET** [lelandrichardson/react-native-maps#257]
Hi everyone, 

I'm having a unusual issue using react-native-maps on iOS on a real device (iPhone 6S) (React native maps 0.4.0, RN 0.25.1), i'm controlling the region with redux. I just want to set the region where the user is located. To do that, I used a function called when the component is loaded : 
```
navigator.geolocation.getCurrentPosition(
         (region) => {
           const regionMod =
             {
               latitude: region.coords.latitude,
               longitude: region.coords.longitude,
               latitudeDelta: 0.1,
               longitudeDelta: 0.1
             }
           this.props.onRegionChange(regionMod)
         },
         (error) => alert(error.message), // eslint-disable-line
         { enableHighAccuracy: true, timeout: 20000, maximumAge: 1000 }
       )
```

And I connected my component using redux : 

```
<MapView
          region={ this.props.region }
          onRegionChange={ this.onRegionChange }
          showsUserLocation
 />

...

function mapStateToProps(state) {
  console.log(state.region)
  return {
    region: state.region,
  }
}

function mapDispatchToProps(dispatch) {
  return {
    onRegionChange: (region) => dispatch(moveToLocation(region))
  }
}

const MapRender = connect(
  mapStateToProps,
  mapDispatchToProps,
)(Map)

export default MapRender
```
Action.js : 
```
const initialMapInfo = { latitude: 0.0, longitude: 0.0, latitudeDelta: 130.0, longitudeDelta: 130.0 }

export function region(state = initialMapInfo, action) {
  console.log(action.type)
  switch (action.type) {
  case 'MOVE_TO_LOCATION':
    return action.region
  default:
    return state
  }
}
```

When I switch from my "home" tab to my "map" tab, the comportement of the state is really strange : 
![capture d ecran 2016-05-27 a 16 24 36](https://cloud.githubusercontent.com/assets/14168629/15610962/596647ec-2428-11e6-9d5c-6e5158f0c758.png)

So the map change region multiple times at wrong coordinates (and always at the same region coords!) before being at the good coordinates.
Here is a gif to see what happened : 
![](http://i.imgur.com/shq46c1.gif)

If someone know how I can solve my problem..
Thank's :)

**Comment by jrichardlai** [comment]
Is the SF location set anywhere in the code, could this be hardcoded somewhere ? Pretty strange...also do you know why the warning is showing up, it seems you might have a wrong Marker instantiated.

**Comment by KGALLET** [comment]
I managed to solve the warnings, it was because I didn't put the propTypes of my coordinate.latitude in my code.

The SF location coordinates is never use in my code so I really don't know what is the problem here..

**Comment by jrichardlai** [comment]
Can you try without the user location? Then try without markers? See what is the thing that triggers the  map change maybe putting a debugger in the reducer and look at the stacktrace.

**Comment by KGALLET** [comment]
I tried without user location and without markers, the map is directly set to the good location, but it seems that the state still receive wrong location.

![capture d ecran 2016-06-02 a 10 18 59](https://cloud.githubusercontent.com/assets/14168629/15738422/79952614-28ab-11e6-89c1-c6344410d013.png)

**Comment by jrichardlai** [comment]
I can't really help you without seeing your code, but maybe you can log the backtrace too ? 

`console.log((new Error()).stack)`

**Comment by KGALLET** [comment]
I found the error was because I was using an api which return me undefined.

**Comment by deehuey** [comment]
The san francisco bug is happening to me too.

```javascript
  render() {
    const { longitude, latitude } = this.props;
    console.log('Region: ', this.state.region);
    return (
      <View style={styles.fill}>
        <MapView
          ref={r => this.map = r}
          style={styles.fill}
          region={this.state.region}
          onRegionChange={this.onRegionChange}
          showsCompass={false}
          customMapStyle={mapStyle}
        >
```

```javascript
  onRegionChange = region => {
    console.log('Region Changing: ', region);
    if (region.longitudeDelta > 80 && !this.state.iosInitialJumpBugHasHappened) {
      return this.setState({
        iosInitialJumpBugHasHappened: true
      });
    }
    this.setState({
      region
    });
  };
```

This works fine on android, but it's jumping to this exact region (San Francisco) as well on iOS. 

With those console logs my output is as follows, without any touch actions happening on the map.

```

index.ios.bundle:92324 Region:  {latitude: 43.25156385754565, longitude: -79.9405345424435, latitudeDelta: 0.03, longitudeDelta: 0.03}
index.ios.bundle:92272 Region Changing:  {longitudeDelta: 0.03816598513895997, latitudeDelta: 0.048178881346807145, longitude: -122.40971999999998, latitude: 37.787685747888986}
index.ios.bundle:92324 Region:  {longitudeDelta: 0.03816598513895997, latitudeDelta: 0.048178881346807145, longitude: -122.40971999999998, latitude: 37.787685747888986}
index.ios.bundle:92272 Region Changing:  {longitudeDelta: 93.95507800000016, latitudeDelta: 87.41089927136262, longitude: -96.45996100000004, latitude: 56.185986}
index.ios.bundle:92324 Region:  {longitudeDelta: 0.03816598513895997, latitudeDelta: 0.048178881346807145, longitude: -122.40971999999998, latitude: 37.787685747888986}
```

It seems your map is trying to update the region while the map is mounting, to sanfrancisco. My current solution to this is for IOS only, i'm ignoring region changes for the first second the component is mounted. This works, but would like to know why your map loves san francisco so much =) It's the exact same region you're using in all your demo videos on the README.MD.

**Comment by PurnimaNaik** [comment]
@KGALLET Go to simulator menu > Debug > Location. If its set to Custom Location, that's where the coordinates for SF are coming from. Its been hardcoded by apple already as a placeholder location in the simulator.

**Comment by Balasnest** [comment]
Using a MapView while controlling the region as state is rerendered continuously. I want to change the region based on state changes. 

How to stop rerender the region?
