### ISSUE TITLE
how to display multiple polylines

### ISSUE THREAD

**Issue by texas697** [lelandrichardson/react-native-maps#259]
I have created a array of arrays that I would like to use for multiple polylines as I do for markers and polygons. Is this possible? I am not getting any errors so I am not sure what I can do to correct this. Here is a pastebin of the json [http://pastebin.com/Q3UqzpEi](url)

```
let res = _.groupBy(routesById, "isRouteId")
let first = _.first(uniqueRouteIds)
               
// console.log(JSON.stringify(res))
              
       me.setState({
             region: {
                  latitude: res[first][0].latlngObj.latitude,
                  longitude: res[first][0].latlngObj.longitude,
                  latitudeDelta: LATITUDE_DELTA,
                  longitudeDelta: LONGITUDE_DELTA
               }
          })

      me.setState({ polylines: res });
```

```
   <MapView
          style={styles.map}
          region={this.state.region}
          >
          {this.state.polylines.map(polyline => (
              <MapView.Polyline
                    key = {polyline.key}
                    coordinates={polyline.latlngObj}
                    strokeColor={PolylineBlue}
                    strokeWidth={5}
                 />
             )) }

   </MapView>
```

**Comment by allthetime** [comment]
I can't analyze your json right now, but printing multiple polylines definitely works. I just tested myself to confirm. If you are constructing them properly it will work. You should log `polyline.latlngObj` because that's probably where your issue is coming from.

**Comment by texas697** [comment]
trying to figure out how to put a console.log inside that map function.

**Comment by allthetime** [comment]
You need to include another set of curly brackets after the arrow and a return statement, like this!

{this.state.polylines.map(polyline => {
             console.log(polyline.latlngObj)
             return (
              <MapView.Polyline
                    key = {polyline.key}
                    coordinates={polyline.latlngObj}
                    strokeColor={PolylineBlue}
                    strokeWidth={5}
                 />
             )} )}

**Comment by texas697** [comment]
ok so after putting the console.log in place I realized that the problem is with my code. This is probably a stackoverflow question but maybe you can spot what is wrong. 

Here is what the code looks like. 

```
    constructor(props) {
        super(props);

        this.state = {
            selectedTrip: this.props.data.selectedTrip,
            trip: [],
            splitTrip: [],
            region: {
                latitude: 0,
                longitude: -0,
                latitudeDelta: 0,
                longitudeDelta: 0,
            },
            polylines: []
        }
    }

    onSplitTrip() {
        let me = this;
        let uniqueRouteIds = [];

        TripMapService.uniqueRouteIds(this.state.trip)
            .then((result) => {
                if (result)
                    result = result.filter(function (obj) {
                        return obj.isRouteId != null;
                    });

                _.each(result, (item) => {
                    let obj = item.isRouteId;
                    uniqueRouteIds.push(obj)
                });
                console.log(JSON.stringify(uniqueRouteIds))

                let routesById = me.state.trip.filter(function (val) {
                    return uniqueRouteIds.indexOf(val.isRouteId) != -1;
                })
                
                console.log(JSON.stringify(routesById))
                
                let res = _.groupBy(routesById, "isRouteId")
                let first = _.first(uniqueRouteIds)

                console.log(JSON.stringify(res))

                me.setState({
                    region: {
                        latitude: res[first][0].latlngObj.latitude,
                        longitude: res[first][0].latlngObj.longitude,
                        latitudeDelta: LATITUDE_DELTA,
                        longitudeDelta: LONGITUDE_DELTA
                    },
                    polylines: res
                })
                console.log(me.state.polylines)
            })
    }
```

Setting state

> polylines: res

causes the region not to be set.  Without it the region gets set correctly. 

So I think the json is incorrect and that the problem is how I am grouping the data. 

```
console.log(JSON.stringify(uniqueRouteIds))
 [
    "24590392-bdf4-4d66-a63b-5b354e22ab1b",
    "0ce9b213-8224-4037-9242-4f9819fb7ac8",
    "bc2b049f-1c6a-4b57-9aaa-beac1400ad89"
]
```

console.log(JSON.stringify(routesById))
[http://pastebin.com/2L4iXtxf](url)

console.log(JSON.stringify(res))
[http://pastebin.com/PpsYz7b5](url)


appreciate the help

**Comment by allthetime** [comment]
Yeah, this is definitely outside the scope of issues for this repo. 

Regardless, like I said before, and like the error message is telling you, `coordinates` must be an array of latLng objects, that looks like this:
```
[
   {latitude: 40, longitude: 100},
   {latitude: 40, longitude: 100},
   {latitude: 40, longitude: 100}
]
```
nothing else.

For some reason you have two maps, one inside the other, which doesn't make much sense. You need to prepare your data properly before hand and only use a single map.

So, `this.state.polylines` needs to be an array of the type of array I have shown above...

```
this.state.polylines = [
    [  {latitude: 40, longitude: 100},  {latitude: 40, longitude: 100}, {latitude: 40, longitude: 100} ],
    [  {latitude: 40, longitude: 100},  {latitude: 40, longitude: 100}, {latitude: 40, longitude: 100} ],
    [  {latitude: 40, longitude: 100},  {latitude: 40, longitude: 100}, {latitude: 40, longitude: 100} ],
]
```

then you will be able to do:
```
                    { this.state.polylines.map(coordinates => (
                                    <MapView.Polyline
                                        coordinates={coordinates}
                                        strokeColor={PolylineBlue}
                                        strokeWidth={5}
                                        />
                                )
                    }) }
```

Your problem is that you are not properly preparing the data. I can't help you do that, but as long as `this.state.polylines` is just an array of arrays of latLng objects, as detailed above, it will work.

**Comment by texas697** [comment]
outstanding! really appreciate the help. and thanks again for this map package.

**Comment by allthetime** [comment]
hah, don't thank me for the maps :) I'm new here, glad I could help though!
