### ISSUE TITLE
example project issue Android

### ISSUE THREAD

**Issue by shieer** [lelandrichardson/react-native-maps#26]
First, thanks for this MapView component, I really love it!

I tried to run the example project, it's working perfect on iOS, but Android has some issues.

For "Tracking Position", not able to move map and zoom, but working fine on "Arbitary Views as Markers",
"Events" has the same problem.

**Comment by lelandrichardson** [comment]
Do you see any errors getting logged in the console?

Is it responding to pans/zooms at all or is it just static?  A gif might help if possible.

Also, which version of android and google play?

**Comment by graywolf336** [comment]
I think this might be related somehow to my issue, #28. As I experienced this when I first tried out the components, but then I switched to a different example and I didn't think about it. I'll try to replicate the issue and post the code along with the versions.

**Comment by graywolf336** [comment]
Okay, I was able to replicate this but with the `EventListener.js` example. You're unable to move the map around, zoom in, and all that. Using `Genymotion Google Nexus 6 - 5.0.0 - API 21` and the source code was copy and pasted from the repository to ensure it was the same.

**Comment by lelandrichardson** [comment]
@shieer I'm assuming your issue got fixed in version 0.2.3. If not please let me know! Closing this issue now.

**Comment by shieer** [comment]
@lelandrichardson Thanks, 0.2.3 works well :)
