### ISSUE TITLE
[Android] Requiring unknown module "./components/MapView/"

### ISSUE THREAD

**Issue by baso6706144011** [lelandrichardson/react-native-maps#265]
I have followed the instruction of installation, and when i tried to run my project and it success to build, but i found error on my device
![13318822_642385932579956_474999539_n](https://cloud.githubusercontent.com/assets/18097752/15698032/74052c92-27ea-11e6-8ce6-ed1052b188b9.png)

and there is a thing that confuses me,
in MainActivity.java, we have to add one line, but there are 2 versions, new MapsPackage() or new AirPackage(), which one is true?

**Comment by jrichardlai** [comment]
You should use `MapsPackage` with the new react native maps version, how are you requiring the MapView ? You should use `import MapView from 'react-native-maps';`

**Comment by baso6706144011** [comment]
@jrichardlai if i use MapsPackage instead of AirPackage, my project will not be builded and found error like below :+1: 
 error: cannot find symbol
            new MapsPackage()
                ^
  symbol:   class MapsPackage
  location: class MainActivity
1 error
:app:compileDebugJavaWithJavac FAILED

---------------------------------------------------------------

i use the newest react native maps version (0.4.2)

and yes i write `import MapView from 'react-native-maps';` as well

**Comment by jrichardlai** [comment]
did you added `import com.airbnb.android.react.maps.MapsPackage;` in MainActivity?

**Comment by baso6706144011** [comment]
@jrichardlai i was trying to follow your instruction but my project wont build, i'm so new with this framework and i hope you will help me patiently

here is my MainActivity (btw my project name is MyProject)

`package com.myproject;

import com.airbnb.android.react.maps.MapsPackage;
import com.facebook.react.ReactActivity;
import com.AirMaps.AirPackage;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

    @Override
    protected String getMainComponentName() {
        return "MyProject";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new MapsPackage()
        );
    }
}
`

and it says error: package com.airbnb.android.react.maps does not exist

**Comment by AKovtunov** [comment]
Are u building an android version?
Try to go step-by-step from the beginning again
Your MainActivity.java seems to be valid. Are you sure that youve installed and saved package and then linked it using 'rnpm link' ?

**Comment by AKovtunov** [comment]
@lelandrichardson I've noticed that installation guide is missing lines about importing package in java code. I've updated this information in this pull request https://github.com/lelandrichardson/react-native-maps/pull/266

**Comment by christopherdro** [comment]
Docs have been updated. Reopen if issue persists.

**Comment by guillermolpz** [comment]
I have a problem when using MapView the application stops, at first my application worked perfectly and when I wanted to test the application stops but only when I use
mapview
already remove all the code and probe with a text and nothing happens but to the moemento of using MapView for the map me the application is detubo
