### ISSUE TITLE
Issue with image component in custom markers (Android)

### ISSUE THREAD

**Issue by paulondc** [lelandrichardson/react-native-maps#267]
Hi,

I'm facing an issue with custom markers where Image components randomly fail to get rendered in the MapView, following bellow an image about it where each one of the blue boxes represents a custom marker component:

![4c1b16f3-215d-48ef-be4e-3195854aeeb5_small](https://cloud.githubusercontent.com/assets/4304871/15776100/84c2a0d6-293a-11e6-8513-0a3101fc537c.jpg)

The reason why it defines a custom marker to show an image rather than defining it through the "image" property is because I want to add a text overlay in the middle of the marker (perhaps there is another way to achieve the same result ?).

Also, I'm providing a test case which was used to generate the image above, since it's a bit long I've hosted it under pastebin :
http://pastebin.com/LJ6JRzLR

Bellow some additional information about my environment :

| Lib        | Version           |
| ------------- |-------------|
| react-native |  0.26.2 |
| react-native-maps |  0.4.2|
| Android |  5|

Any thoughts ?

Cheers,
Paulo

**Comment by DennisMG** [comment]
Read #100 👍

**Comment by paulondc** [comment]
Hi @DennisMG, thanks for pointing out that to me.

**Comment by paulondc** [comment]
Duplicated issue, closing it
