### ISSUE TITLE
showCallout method usage

### ISSUE THREAD

**Issue by guofoo** [lelandrichardson/react-native-maps#27]
I'm trying programmatically show the callout of a particular marker by using the showCallout method under MapView.Marker but not having luck.

I've set the ref="myMarker" on a marker during render, and then in componentWillMount stage, use this.refs.myMarker.showCallout() but nothing seems to happen on the map. There's no error logged either.

Not sure if my usage is incorrect as I could not find an example usage in the folders. Is there a more detailed description on how to properly use the method?

Thanks

**Comment by lelandrichardson** [comment]
Hey @guofoo , is this on android or ios or both?

**Comment by guofoo** [comment]
this is on IOS, have not tried android

**Comment by ayarulin** [comment]
I'm on 0.2.1 but `showCallout()` still don't working for me, @guofoo could you confirm?

**Comment by jedlau** [comment]
I'm trying to call `hideCallout()` programmatically on a `MapView.Marker.Animated`, and it's not working. I'm on 0.3.0.
```javascript
    return (
      <MapView.Marker.Animated
        ref="mymarker"
      />
    );
```

Then:
```javascript
    this.refs["mymarker"].hideCallout();
```

**Comment by stevematdavies** [comment]
There is hardly any guidance in the docs, nor how it should be used with the useRef hooks
