### ISSUE TITLE
[Android] Error "Requiring unknown module './MapMarker'"

### ISSUE THREAD

**Issue by pchandramouli** [lelandrichardson/react-native-maps#272]
Followed the steps in [Installation instructions](https://github.com/lelandrichardson/react-native-maps/blob/master/docs/installation.md) to setup 'react-native-maps'. After building the app, the output is this:
![image](https://cloud.githubusercontent.com/assets/478508/15819801/00520c62-2c03-11e6-8bfc-bd9fff4daaf1.png)

Looks like the `var MapMarker = require('./MapMarker');` in MapView.js (line 19) is unable to load it.

**Comment by DennisMG** [comment]
is not necesary to require de MapMarker, you should use it like this 
`<MapView.Marker> </MapView.Marker>`

**Comment by speyburn** [comment]
Are you still having the issue @pchandramouli ? I ran into the same issue just now.

**Comment by AKovtunov** [comment]
@pchandramouli @speyburn maybe you tried to add some marker from examples? Or just a basic install?

**Comment by pchandramouli** [comment]
@speyburn I still do.

**Comment by speyburn** [comment]
@pchandramouli i think i got rid of my problem. I just created a new blank project and went trough the installation instructions again. I realized that you pretty much only need to do: 
`npm install react-native-maps --save`
`rnpm link`
and add your api key. I think I over did some of the configurations and that caused the error. Give it a shot and let me know how it went :)

**Comment by pchandramouli** [comment]
@speyburn Did as you said and the error is gone now. Though, I'm just seeing a blank map. Different issue anyway, will check that. Thanks for the help! :+1:

**Comment by speyburn** [comment]
@pchandramouli Glad to hear its working for you too! I had the blank map thing as well after fixing the last issue. I got it solved by inserting a correct API key to the AndroidManifest.xml. I can give some more detailed information if you are having problems with it :)
