### ISSUE TITLE
onPress and onPanDrag triggered when changing region state

### ISSUE THREAD

**Issue by perkola** [lelandrichardson/react-native-maps#277]
Given a map with `region={this.state.region}`, setting the region state with 
```
this.setState({
  region: {
    latitude: newLatitude,
    longitude: newLongitude,
  }
});
```
the `onPress` and `onPanDrag` events are triggered even when there are no user interaction since the region was changed programatically. Is this the way it should be?

**I would like to distinguish between the user changing the region** (by panning or dragging the map) **and by programmatically changing the region** (with `this.setState`). How can I do this?

**Comment by jrichardlai** [comment]
It is strange that the onPress and onPanDrag will be triggered, is this for iOS or Android?

**Comment by perkola** [comment]
This is for Android.

**Comment by jrichardlai** [comment]
Can you show an example of code? It should not call onPress or onPanDrag if you are not touching the map.

**Comment by perkola** [comment]
It's very similar to the example code of the readme:
```
getInitialState() {
  return {
    region: {
      latitude: 37.78825,
      longitude: -122.4324,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
    },
  };
}

onRegionChange(region) {
  this.setState({ region });
}

updateRegion(region) {
    console.log('updating region programatically');
    this.setState({
      region: {
        latitude: region.latitude,
        longitude: region.longitude
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
      }
    })
}

render() {
  return (
    <MapView
      region={this.state.region}
      onRegionChange={this.onRegionChange}
      onPress={console.log('triggering onPress')}
      onPanDrag={console.log('triggering onPanDrag')}
    />
  );
}
```

Everything works as expected: the map can be moved by calling the `updateRegion` method and the user can pan the map as well. The weird thing is that 
```
triggering onPress
triggering onPanDrag
```
shows up in either case.

**Comment by raubas** [comment]
having the same issue on iOS, very similar code, although i'm calling animateToRegion..!

**Comment by panw** [comment]
My scenario is to detect when a user interacts with the MapView through a pan gesture, so I could stop the region from updating if the user's current region changes.

At the moment, I am experiencing the issues mentioned above. 

Did anyone figure out a work around to this?

**Comment by egold** [comment]
@perkola 

Try changing your code from:

```
      onPress={console.log('triggering onPress')}
      onPanDrag={console.log('triggering onPanDrag')}
```

to: 

```
      onPress={() => {console.log('triggering onPress')}}
      onPanDrag={() => {console.log('triggering onPanDrag')}}
```

**Comment by perkola** [comment]
This now works with react-native-maps `v.0.7.1` and react-native `v.0.30.0`. Programatically changing the region does **not** trigger `onPress` or `onPanDrag` any more.

**Comment by esaminu** [comment]
`animateToCoordinate` still triggers `onRegionChange`, should this be the case? if yes then is there a way to distinguish between the user changing the region and changing it programatically? otherwise, is there a way to change region programmatically without mapping the region prop to state?

**Comment by rexlow** [comment]
@esaminu Wanted to do the same but seems like no one cares. Issued here #1038
