### ISSUE TITLE
Android onRegionChange Issue

### ISSUE THREAD

**Issue by graywolf336** [lelandrichardson/react-native-maps#28]
I'm having an issue with Android (doesn't happen on iOS). Whenever I add `onRegionChange` to the MapView and set the state's region to the region passed (like the `DisplayLatLng.js` example), the view maps gets "laggy" or "grabby" like something is fighting the display region to be displayed. That's not very descriptive, so here's a video which hopefully shows what I'm talking about:

https://www.youtube.com/watch?v=IAXM2LQFmIw

Thanks again for making this!

**Comment by graywolf336** [comment]
I have removed the `region` prop from the MapView and replaced it with `initialRegion` yet the "grabbing" is still happening with listening and using the `onRegionChange`.

**Comment by lelandrichardson** [comment]
can you try removing the `onRegionChangeComplete` handler?  (and also change the `initialRegion` prop back to `region`)

**Comment by graywolf336** [comment]
Doing that yields the same results. :disappointed:

**Comment by lelandrichardson** [comment]
@graywolf336 does this happen with the examples?  If not, perhaps you can post the code you are using?

**Comment by graywolf336** [comment]
I'm using es6 and babel, but that's the only real difference I can tell between your code and mine.

**Comment by graywolf336** [comment]
As an update, I just copied the source and pasted it directly from the `DisplayLatLng.js` example and I'm still experiencing the issue. I'm using `Genymotion Google Nexus 6 - 5.0.0 - API 21`.

**Comment by lelandrichardson** [comment]
@graywolf336 thanks. Going to try downloading the same emulator and seeing what happens. We've had some issues with 5.0.0 before, but they were a bit different.

**Comment by lelandrichardson** [comment]
@graywolf336 should be available in 0.2.3

**Comment by graywolf336** [comment]
Can confirm it is fixed and with #26 being fixed. :+1: Thanks!
