### ISSUE TITLE
AirMapsExplorer has stopped

### ISSUE THREAD

**Issue by clearmirror** [lelandrichardson/react-native-maps#285]
Hi I cloned the repo and go to example folder. I ran npm install and then turn on android virtual device. Then I ran react-native run-android in the example folder. The virtual device seems to connect to the javascript server but it gives me a popup saying "AirMapsExplorer has stopped". Anyone else encounters the same thing?

Edit: The example works fine on IOS despite some warnings... the issue only occurs on Android.

**Comment by jrichardlai** [comment]
Hello @clearmirror did you follow the instruction step by step? is there logs in adb logcat?

**Comment by clearmirror** [comment]
@jrichardlai thanks for your reply. it turns out that on the android virtual device I need to give the app access to location and data storage then the error disappears. But it gives me a blank map for all examples.

I think in the example folder everything has already bee setup no? To run the example I only need to npm install and react-native run-android. Or is there any other thing I need to do?

**Comment by clearmirror** [comment]
I finally figured why. When we create a device we have to choose Google APIs Intel Atom (x86) instead of Intel Atom (x86) for CPU/ABI. Some of us may follow what is on Facebook's React-native getting started tutorial and set it 'Intel Atom (x86)' because that's what they have on screenshot.

Hopefully this will help other people with the same issues :)
