### ISSUE TITLE
How would one mark out specific streets

### ISSUE THREAD

**Issue by ippa** [lelandrichardson/react-native-maps#29]
This plugin looks impressive. I've been fiddling with a app-idea that's centered around a map, I need to 'mark out streets'. So not setting a marker but rather color whole streets making them stand out on the map. Is this something that can be done with react-native-maps? Maybe with the Polyline? I couldn't find the answer while checking out the readme and docs.

**Comment by lelandrichardson** [comment]
@ippa polylines could be used to cover streets. It might not look super pretty... but probably worth a try to see if it will suit your needs.

To be clear, this is not a react native limitation or a limitation of this plugin... I dont think there's any better way. If you find one and this library doesn't support it though, let me know.

**Comment by ippa** [comment]
Thanks for the quick reply. I'll fiddle around as see what I come up with :).
