### ISSUE TITLE
Question: how to choose a suitable region

### ISSUE THREAD

**Issue by npomfret** [lelandrichardson/react-native-maps#297]
I want to render a map region that's zoomed in based on the accuracy of my gps position, but I don't know how to choose the values for the deltas.

What units are `longitudeDelta` and `latidueDelta`  in? 

What units is the `accuracy` field in a gps coordinate?

**Comment by christopherdro** [comment]
@npomfret You could try determined the location of your gps position by meters. The delta values are building a radius around your center position.
1 degree is equal to roughly 110,000 meters.
You could try setting something like 0.02 as your delta values and start from there.

**Comment by npomfret** [comment]
Thanks for your reply.  What I'm really after is a formula in order to avoid magic numbers.  I agree that it looks like the GPS `accuracy` number is meters.  Can anyone confirm though, are there any docs out there??

And what about the _delta_ value?  What does 1, or 0.02 translate to?  How many meters? Or miles?

**Comment by jrichardlai** [comment]
For iOS from what I can find from this link: https://developer.apple.com/library/ios/documentation/MapKit/Reference/MapKitDataTypesReference/#//apple_ref/c/tdef/MKCoordinateSpan it seems that 
```
Fields
latitudeDelta
The amount of north-to-south distance (measured in degrees) to display on the map. Unlike longitudinal distances, which vary based on the latitude, one degree of latitude is always approximately 111 kilometers (69 miles).

longitudeDelta
The amount of east-to-west distance (measured in degrees) to display for the map region. The number of kilometers spanned by a longitude range varies based on the current latitude. For example, one degree of longitude spans a distance of approximately 111 kilometers (69 miles) at the equator but shrinks to 0 kilometers at the poles.
```

so 1 delta value is one degree.

**Comment by npomfret** [comment]
Many thanks.
