### ISSUE TITLE
MapsPackage wrong argument 

### ISSUE THREAD

**Issue by LiquidWicked** [lelandrichardson/react-native-maps#305]
This is error output from command "react-native run-android":

``` /MainActivity.java:42: error: constructor MapsPackage in class MapsPackage cannot be applied to given types;
            new MapsPackage(this)
            ^
  required: no arguments
  found: MainActivity
  reason: actual and formal argument lists differ in length
1 error :app:compileDebugJavaWithJavac FAILED ```

MapsPackage.java file is there along with constructor that receives argument of type Activity. I am not sure if this has something to do with it, but first I installed npm package react-native-maps but realized that it is not updated so I installed from github using npm. 

Also, I am using react native version 0.27.

**Comment by srygg** [comment]
did you fix that?

**Comment by gkmbinh** [comment]
got the same error.
anyone can help ?

**Comment by DennisMG** [comment]
Just delete the `this` that should work... 👍

**Comment by gkmbinh** [comment]
@DennisMG 
 It just build as well, but when app run you get the error
null is ...

**Comment by DennisMG** [comment]
Weird.. It worked for me.. I don't get any null error... I'm using React Native  0.26.3

**Comment by morrigan** [comment]
@DennisMG depends on the device according to this [PR](https://github.com/lelandrichardson/react-native-maps/pull/276). Maybe problem with the Maven repository ``'com.airbnb.android:react-native-maps:0.5.0'`` ?

**Comment by cjbutcher** [comment]
@DennisMG solution worked for me. Thank you.

**Comment by lalitmohan001** [comment]
I am getting the same error and I use the both `new MapsPackage(this)` and `new MapsPackage()`. But nothing works for me 

MainApplication.java 

`package com.awesomeiam;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.airbnb.android.react.maps.MapsPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.airbnb.android.react.maps.MapsPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new MapsPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
`
