### ISSUE TITLE
Constant White-Screen

### ISSUE THREAD

**Issue by BigPun86** [lelandrichardson/react-native-maps#31]
Hey there. I tried this module on Android RN .17 but unfortunately the only thing i see is a white-screen. Any ideas?

     var MapTest = React.createClass({
            getInitialState() {
                return {
                    latitude: 37.78825,
                    longitude: -122.4324,
                    latitudeDelta: 0.0922,
                    longitudeDelta: 0.0421
                };
            },
            onRegionChange(region) {
                this.setState({region});
            },
            render: function () {
                return (
                    <View style={{flex: 1, padding: 10}}>
                        <Text style={{alignSelf: 'center'}}>TEST</Text>
                        <View style={{flex: 1, borderWidth: 1}}>
                            <MapView
                                region={this.state.region}
                                onRegionChange={this.onRegionChange}
                            />
                        </View>
                    </View>
                );
            }
        });

**Comment by lelandrichardson** [comment]
@BigPun86 you might have to apply some styles to the mapview itself in order for it to fill it's container.

I might change the default styles of it to be `flex: 1` in order to make this work a little more intuitively...

**Comment by BigPun86** [comment]
Oh man, should of thought that my self :D Thanks, works great !!

**Comment by lelandrichardson** [comment]
:+1:

**Comment by vishadpatel22** [comment]
how to set map to constant animated map
