### ISSUE TITLE
Multiple Markers

### ISSUE THREAD

**Issue by richyzhu** [lelandrichardson/react-native-maps#312]
Hello everyone,

I'm very new to js and react native. I'm wondering how can i set an array of markers?
Currently I'm trying to do this and nothing is happening
                        <MapView.Marker
	              			coordinate={{
	              			latitude: 41.343210, 
	                        longitude: -87.355086},{latitude: 41.93 
	                        longitude: -87.64}}
	                    />
any suggestions/resources are welcome. Thanks!

**Comment by juand89** [comment]
like this:
 const markers = [
      {
        id: 0,
        amount: 99,
        coordinate: {
          latitude: LATITUDE,
          longitude: LONGITUDE,
        },
      },
      {
        id: 1,
        amount: 199,
        coordinate: {
          latitude: LATITUDE + 0.004,
          longitude: LONGITUDE - 0.004,
        },
      },
      {
        id: 2,
        amount: 285,
        coordinate: {
            latitude: LATITUDE - 0.004,
            longitude: LONGITUDE - 0.004,
          },
       },
    ];

**Comment by sakshityagi** [comment]
I am facing the same issue. I tried something like this. 

```javascript
 {
        this.state.myList.map((item, idx) => {
              return (
                   <MapView.Marker key={idx}
                                coordinate={item.coordinates}
                          />
                        )
              })
       } 
```

The above code just display one marker, the first one. Any help would be appreciated.

**Comment by sakshityagi** [comment]
The above code actually worked. Thanks.
