### ISSUE TITLE
Android: maps blank in release apk

### ISSUE THREAD

**Issue by allthetime** [lelandrichardson/react-native-maps#327]
Hey, I just packaged my app up for release, and for some reason maps are not loading. They work fine in debug mode, but are just grey in the release version, with the google logo in the bottom left corner.

Anyone know what's going on?

**Comment by texas697** [comment]
your google map api key?

**Comment by allthetime** [comment]
ya definitely. the key I was using wasn't signed with my release key.

**Comment by wkw** [comment]
@allthetime Can you elaborate? I'm having same problem. Fine in debug, but in release api, I see all white screen, and a little Google logo at bottom left. Not clear what steps I need to take. thanks!

**Comment by mistryhiren94** [comment]
I'm facing same problem,
map work on debug but it's not working on Google Play Store
please help
thanks

**Comment by mistryhiren94** [comment]
Hi
solved by replacing SHA1 key from Google play store

**Comment by twinkleSiya** [comment]
Debug apk  install and  app work properly and google map show, too
but  release generated apk  install when map not showing in please solution 
All process are done, but i'm facing same problem
Could you please guide me for the same on how to resolve it asap? I really need to get this done. Help me.

**Comment by jakeOliv** [comment]
same problem here, done adding SHA 1 key using keytool, but not working. app works in debug build but not in release.. please help

**Comment by stevebaros** [comment]
My simple insight on those still struggling with this.  use the solution given by @wkw  it will work ,

the secret is here https://cloud.githubusercontent.com/assets/1691220/23273776/5418ae8e-f9ce-11e6-8bb2-d0ef5b13dc5b.png

**Comment by AizenSousuke** [comment]
is this the keystore that is in the /android/app folder?
