### ISSUE TITLE
Dashed Polyline Support

### ISSUE THREAD

**Issue by af7** [lelandrichardson/react-native-maps#33]
Can we have dashed polylines somehow? I understand that this is not possible at the moment but could that be possible?

![image](https://cloud.githubusercontent.com/assets/7850073/12533425/251eae40-c238-11e5-8789-6c3cb8ac395a.png)

**Comment by lelandrichardson** [comment]
@af7 this is currently possible with this library for ios only (see docs). Google maps does not yet support line types for their polygon/polyline implementation.  It's been a longstanding issue here (https://code.google.com/p/gmaps-api-issues/issues/detail?id=4633).

It sounds like they might add it in google maps v3, at which point this library will add support for it. Until then, I'd consider accepting a PR if someone wants to attempt to implement it in android with api v2...

**Comment by af7** [comment]
@lelandrichardson Thanks for the info.

I looked at the docs here and could not find something to create a dashed polyline:
https://github.com/lelandrichardson/react-native-maps/blob/master/docs/polyline.md

Maybe I do not understand something there?

**Comment by lelandrichardson** [comment]
@af7 you're right! Sorry. I could have sworn that I had implemented this.  We can implement this on iOS...

https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKOverlayPathRenderer_class/index.html#//apple_ref/occ/instp/MKOverlayPathRenderer/lineDashPattern

**Comment by af7** [comment]
Nice! So, it **can** be done, thanks!

**Comment by lelandrichardson** [comment]
@af7 this is now in 0.2.2

**Comment by af7** [comment]
Great, thanks!

**Comment by markmssd** [comment]
It's now possible to make dotted/dashed polylones on Google Maps as well. It could be a great addition!

**Comment by aindeev** [comment]
@markmssd @lelandrichardson Would love to see dashed polylines for google maps as well :)

**Comment by MoOx** [comment]
@lelandrichardson It seems the blocking issue as been fixed and Google Map seems to support dashed Polylines now!

> We have added the ability to customize the stroke type to Polylines and the outline of Polygons and Circles in the Feb 2017 release of the Android Maps API. 

> See information about Stroke Type in the Shapes Guide here: 
> https://developers.google.com/maps/documentation/android-api/shapes#stroke_pattern 

> See the release notes here: 
> https://developers.google.com/maps/documentation/android-api/releases#february_15_2017 

> See the blog post here: 
> https://maps-apis.googleblog.com/2017/02/styling-and-custom-data-for-polylines.html

Source: https://issuetracker.google.com/issues/35822260#comment14

I am new to react-native and use it to not have to do specific iOS or Android code so I am really not comfortable with Java but if you don't have time or if it's not on Airbnb priority at all (which I guess it's not since this feature should be possibly implemented for a few month now) , I can try to implement lineDashPhase/lineDashPattern for Android. I would just wait for a feedback from your side!

**Comment by thiphariel** [comment]
An Android working example of dashed polyline : 

```java
Dash dash = new Dash(20);
Gap gap = new Gap(10); 
List<PatternItem> dashed_pattern = Arrays.asList(dash, gap);

polyline.setPattern(dashed_pattern);
```

Any chance to have this feature on Android too in a next version @lelandrichardson ?
Thanks

**Comment by filipef101** [comment]
Hey, I have made it working, with same exact behavior for ios and android google maps. https://github.com/react-community/react-native-maps/pull/2257
It seems to have some conflict, can someone take a look at it?

**Comment by filipef101** [comment]
solved them! all good! :)
