### ISSUE TITLE
Map locked and stay in screen

### ISSUE THREAD

**Issue by zerob4wl** [lelandrichardson/react-native-maps#338]
I use react-native-router-flux. I show map in a scene  and when I change scenc map stateid in screen like an image, front of other component!!
how can I fix this propblem?

**Comment by symmetriccurve** [comment]
May be you need to check the Prop :

cacheEnabled = {false} should fix this issue

**Comment by jeveloper** [comment]
@symmetriccurve  cacheEnabled is defaulted to false 

@zerob4wl  im having the same issue ( RN 30, flux 3.32, latest map lib)
It appears as if only mapview is protruding above all views currently on the stack , which is insanely weird bug.

**Comment by veedeo** [comment]
Hey @jeveloper have you found a solution to this issue?

**Comment by symmetriccurve** [comment]
@zerob4wl. Can you please share some snippets of your code

**Comment by fdnhkj** [comment]
@zerob4wl Do you also render a MapView in the next scene ? 
If so, this issue may be linked to https://github.com/lelandrichardson/react-native-maps/issues/453.

**Comment by jeveloper** [comment]
Same issue as 453, can you close this one 

thanks
