### ISSUE TITLE
Error:Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by riten7** [lelandrichardson/react-native-maps#345]
In android studio I m getting this error after linking react-native-maps. Settings.gradle looks like this
    `include ':app'
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android')
`

**Comment by sayedatif** [comment]
change it to like this
include ':app', ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android')

also check your android/app/build.gradle file . Comment the error you are getting.

**Comment by riten7** [comment]
no same error still exists.no success.

**Comment by sayedatif** [comment]
hey riten7 follow this link http://stackoverflow.com/questions/38095524/cannot-evaluate-module-react-native-maps-configuration-with-name-default-n
here you will get the answer i also faced the same. Got my query solved here.

**Comment by riten7** [comment]
thanks @sayedatif .. it helped me..

**Comment by mozillo** [comment]
Thanks for answering
