### ISSUE TITLE
How to add gps tracking in maps

### ISSUE THREAD

**Issue by sayedatif** [lelandrichardson/react-native-maps#346]

**Comment by sayedatif** [comment]
I want add automatic location detector using gps how can i do it @lelandrichardson 
please help.

**Comment by jeveloper** [comment]
@sayedatif You should see docs prior, there is enough documentation.

On mapview use property followsUserLocation={true}

this will place a person's location on a map. on IOS you need to have additional settings since it'll request  a location from a user.

**Comment by iiitmahesh** [comment]
@jeveloper how to implement live tracking on phone from other GPS device using react-native-maps

**Comment by jeveloper** [comment]
@iiitmahesh would you like professional consulting services? 
I can provide that.
