### ISSUE TITLE
Could not find com.facebook.react:react-native:0.27.2.

### ISSUE THREAD

**Issue by dslounge** [lelandrichardson/react-native-maps#359]
I'm having an issue building (`react-native run-android`), and I don't understand what's going on. It looks like the `react-native-maps` `build.gradle` wants to compile `react-native:0.27.2` but it's not finding it.

I've followed the latest installation instructions exactly (using `compile project(':react-native-maps')`) and double checked everything, but I'm still stuck with this error. I've even installed RN 0.27.2 in my project. Where is `react-native-maps` supposed to find `com.facebook.react:react-native:0.27.2` and what steps do I need to take to get that set up? 

Should I just switch to using `compile 'com.airbnb.android:react-native-maps:0.6.0'` in build.gradle instead?

I'm using npm `3.7.3` if that makes any difference.

Here's the error log.
```
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-maps'.
   > Failed to notify project evaluation listener.
      > Could not resolve all dependencies for configuration ':react-native-maps:_debugCompile'.
         > Could not find com.facebook.react:react-native:0.27.2.
           Searched in the following locations:
               file:/Users/rmendiola/.m2/repository/com/facebook/react/react-native/0.27.2/react-native-0.27.2.pom
               file:/Users/rmendiola/.m2/repository/com/facebook/react/react-native/0.27.2/react-native-0.27.2.jar
               https://jcenter.bintray.com/com/facebook/react/react-native/0.27.2/react-native-0.27.2.pom
               https://jcenter.bintray.com/com/facebook/react/react-native/0.27.2/react-native-0.27.2.jar
               file:/Users/rmendiola/code/evertrue/givingtree-android/node_modules/react-native-maps/node_modules/react-native/android/com/facebook/react/react-native/0.27.2/react-native-0.27.2.pom
               file:/Users/rmendiola/code/evertrue/givingtree-android/node_modules/react-native-maps/node_modules/react-native/android/com/facebook/react/react-native/0.27.2/react-native-0.27.2.jar
               file:/usr/local/opt/android-sdk/extras/android/m2repository/com/facebook/react/react-native/0.27.2/react-native-0.27.2.pom
               file:/usr/local/opt/android-sdk/extras/android/m2repository/com/facebook/react/react-native/0.27.2/react-native-0.27.2.jar
               file:/usr/local/opt/android-sdk/extras/google/m2repository/com/facebook/react/react-native/0.27.2/react-native-0.27.2.pom
               file:/usr/local/opt/android-sdk/extras/google/m2repository/com/facebook/react/react-native/0.27.2/react-native-0.27.2.jar
           Required by:
               GivingTreeAndroid:react-native-maps:unspecified
      > No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.113 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

**Comment by dslounge** [comment]
After more investigation there are 2 problems happening:
1. `Could not find com.facebook.react:react-native:0.27.2.`
2. `No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer`

I had to go into `node_modules/react-native-maps/android/lib/build.gradle` to fix both issues. I had to comment out `apply from: 'gradle-maven-push.gradle'` to fix problem 2, and I had to change dependencies to use `compile 'com.facebook.react:react-native:+'` instead of `compile 'com.facebook.react:react-native:0.27.2'.  That file now looks like:

```
apply plugin: 'com.android.library'
//apply from: 'gradle-maven-push.gradle'

android {
  compileSdkVersion 23
  buildToolsVersion "23.0.3"

  defaultConfig {
    minSdkVersion 16
    targetSdkVersion 23
  }

  lintOptions {
    disable 'InvalidPackage'
  }
}

dependencies {
  compile 'com.facebook.react:react-native:+'
  compile "com.google.android.gms:play-services-base:8.4.0"
  compile 'com.google.android.gms:play-services-maps:8.4.0'
}
```

Obviously this isn't a great fix since I now have a dirty `node_modules`. I think this `build.gradle` assumes we have `gradle-mvn-push` set up, which I think a lot of people don't. So it'd be great to add language to the instructions saying how to do this (I still don't know). 

This also doesn't technically work on the latest version (`0.29.0` now) of React Native, making this statement invalid:  "we are not officially going to support this module on anything but the latest version of React Native". Does this package have to be hardcoded to `0.27.2`? Can't it just use `compile 'com.facebook.react:react-native:+'` to use whatever's in the user's project?

Related issues: #331, #288

**Comment by dslounge** [comment]
@skellock 's branch is the best temporary fix: https://github.com/lelandrichardson/react-native-maps/issues/331#issuecomment-229066704

**Comment by skellock** [comment]
I've also tested the changes to the Java source to bring it up to speed with the new RN Java interface, but I didn't want to pack them into that branch just yet.

@lelandrichardson - anything we could do to help speed this up?  RN 29 is now out and many of us are caught up in the pursuit of shiny.  <3

**Comment by srinathvsp** [comment]
Could not find com.facebook.react:react-native:0.29.0 same issue when added gradle for android

**Comment by felipecsl** [comment]
the latest code on master is now compatible with RN 29.
