### ISSUE TITLE
markers re-render on marker press

### ISSUE THREAD

**Issue by texas697** [lelandrichardson/react-native-maps#376]
"react-native": "0.27.2",
"react-native-maps": "^0.6.0"

trying to solve another issue I am having I realized the map is re-rendering the markers when ever i click on a marker. Is this normal? Does the map re-render on any event?

**Comment by texas697** [comment]
any ideas?

**Comment by texas697** [comment]
so doing some troubleshooting I put a console.log
 ```
  {this.state.routePolylines.map(coordinates => {
                            console.log('coordinates', coordinates)
                            return (
                                <MapView.Polyline
                                    key={counter++}
                                    coordinates={coordinates}
                                    strokeColor={colors.blue}
                                    strokeWidth={5}/>
                            )
                        }) }
```

and what I realized is it is for some reason it is continually looping over and over? Any ideas on why it is doing this?

**Comment by texas697** [comment]
It seems like this should not be happening?

**Comment by symmetriccurve** [comment]
I have the same Issue

**Comment by texas697** [comment]
ok, so its a coding issue. very knew to react-native and just realized the component re-renders every time you call setState!
