### ISSUE TITLE
Build error after updating to 0.7.1

### ISSUE THREAD

**Issue by 123ndy** [lelandrichardson/react-native-maps#387]
After updating from `react-native-maps` 0.6.0 to 0.7.1 I get this error:

```
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/something/Documents/react-native-apps/something2/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapCallout.o AirMaps/AIRMapCallout.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

**I use:**
react 15.2.1
react-native 0.29.0

Any idea how to fix this?

**Comment by yazgazan** [comment]
I'm having the same error when I build my app in circleci (except for i386). Builds work fine on my machine though.

node: 6.2
react 0.14.5
react-native: 0.25.1
react-native-maps: 0.7.1

**Comment by yazgazan** [comment]
It turns out I forgot to commit some files that were added by `pod install`.

@123ndy This might be a solution to your problem, although in my case this error wasn't due to an update.

**Comment by michaelAndersonCampingWorld** [comment]
I'm getting the same error as @123ndy, and I have the exact same versions of both react and react-native.

**Comment by michaelAndersonCampingWorld** [comment]
@123ndy I think I found a solution, https://github.com/lelandrichardson/react-native-maps/issues/371#issuecomment-231585153 suggests some changes to some headers. It worked for me. When I tried to build in XCode the failures showed up in the places where this comment suggests changes.

**Comment by 123ndy** [comment]
@michaelAndersonCampingWorld Great! Thanks. That was it. 0.7 here I come.
@yazgazan: Sorry for not replying, please forgive me :)
