### ISSUE TITLE
Compatibility with 0.29

### ISSUE THREAD

**Issue by VinceBT** [lelandrichardson/react-native-maps#399]
On RN 0.29.1 after linking with rnpm successfully, happens after ```react-native run-android```
```
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-maps : Configuration with name 'default' not found.
```

**Comment by lcustodio** [comment]
I'm using the same version, same problem.

```
    "react": "15.2.1",
    "react-native": "0.29.1",
    "react-native-maps": "^0.7.1"
```

**Comment by felipecsl** [comment]
I assume this has something to do with `rnpm`, I'm not familiar with how that works, maybe @lelandrichardson has ideas

**Comment by lcustodio** [comment]
I read in thread #21 about the `rnpm` issue. At that point the problem was with `settings.gradle`.

Mine is the following:
```
rootProject.name = 'TheProj'

include ':app'
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android')

```

**Comment by felipecsl** [comment]
The installation instructions have been changed recently, you don't need to include react-native-maps as a project anymore: https://github.com/lelandrichardson/react-native-maps/blob/master/docs/installation.md

**Comment by lcustodio** [comment]
I guess I found the problem, @VinceBT can you try changing the `build.gradle`?

`compile project(':react-native-maps')` by:
`compile 'com.airbnb.android:react-native-maps:0.7.1'`

**Comment by felipecsl** [comment]
Yep, that should do it!

**Comment by lcustodio** [comment]
In addtion there is a confusion problem at `MainActivity.java` and `MainApplication.java`.

There reference to the library `import com.airbnb.android.react.maps.MapsPackage;` is made at Activity instead of Application.

**Comment by VinceBT** [comment]
After trying your solution I had this : 
![](https://i.gyazo.com/31cd0bda736903a605b355a6442ab65b.png)

**Comment by cande1gut** [comment]
I had the same problem and what @lcustodio sugested did the trick, @VinceBT seems like rnpm links com.airbnb.android.react.maps.MapsPackage to the wrong file, if you add this to your MainApplication and follow all updated instructions GoogleMaps should work.
