### ISSUE TITLE
How to set the Google API Key for iOS Simulator?

### ISSUE THREAD

**Issue by asafratzon** [lelandrichardson/react-native-maps#402]
This question is basic enough, however I'm not sure why it's mentioned nowhere in the docs.
While for Android there are several guides on how to set the API Key (with regards to Genymotion _and_ physical devices).

When I googled this question I saw some saying that one should install Google Maps SDK for iOS and then configure the API Key in the AppDelegate.m file of the iOS project - is this true?

If so, why is the [AppDelegate.m](https://github.com/lelandrichardson/react-native-maps/blob/master/example/ios/AirMapsExplorer/AppDelegate.m)  from the example project doesn't contain it?
If not, how the heck does the simulator know what API Key to use for the tile fetching of the map?

I came up with this question after following all the instructions in the docs and getting a blank map on iOS simulator, and it didn't make sense to me that I didn't have to set my API Key nowhere.

Am I just missing something here?
Any clarifications will be much appreciated.

**Comment by solodream** [comment]
Why Google API  key? There is only Apple Maps on iOS...

**Comment by asafratzon** [comment]
Thanks @solodream... so I _was_ missing something basic here.
I don't have an apple device and I thought we use Google Maps for iOS as well.
