### ISSUE TITLE
Custom markers and position absolute

### ISSUE THREAD

**Issue by nazywamsiepawel** [lelandrichardson/react-native-maps#403]
Hey,

I'm trying to create a marker which will have touchable elements around its center. I use position:'absolute' to get the items positioned properly.

Unfortunately, whenever I add position absolute to any view it becomes unclickable. It makes creating fancy markers very hard and reminds me of a certain MC Hammer song.

A simplified example (which works without position absolute) :

```
<MapView.Marker coordinate={marker.loc} onPress={() => alert("yo")}>
    <View style={{position:'absolute', height:40, width:40, backgroundColor:'red'}} />
</MapView.Marker>
```

Interestingly, touchable events become blocked if the view is a TouchableOpacity too :

```
<MapView.Marker coordinate={marker.loc} onPress={() => alert("yo")}>
    <TouchableOpacity onPress={() => alert("yo")} style={{position:'absolute', height:40, width:40, backgroundColor:'red'}} />
</MapView.Marker>
```

I'm using the latest version available from npm, 0.7.1

Is this issue a bug?
If yes, could you please give me a hint how to fix it?
If not, what's a reasonable way to get it done?

**Comment by zelll** [comment]
You should set width/height for MapView.Marker if it has an "absolute" child view, otherwise you'll get a 0x0 marker (try "View Hierarchy" in Xcode).

```jsx
<MapView style={{flex: 1}} initialRegion={{
      latitude: 37.78825,
      longitude: -122.4324,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
    }}>
  <MapView.Marker coordinate={{latitude: 37.78825, longitude: -122.4324}} onPress={() => console.log("yo")} style={{height:40, width:40}}>
    <View style={{position:'absolute', height:40, width:40, backgroundColor:'red'}} />
  </MapView.Marker>
</MapView>
```

**Comment by DmsChrisPena** [comment]
Completely unrelated but, is the 'onPress' action working for you on IOS?

**Comment by KGALLET** [comment]
I would like to know what @DmsChrisPena asked too, thx :)

**Comment by nazywamsiepawel** [comment]
Hey @zelll, your suggestion combined with `centerOffset` solved the issue. Thanks!
