### ISSUE TITLE
Load markers dynamically

### ISSUE THREAD

**Issue by andfs** [lelandrichardson/react-native-maps#412]
Hi guys,
I need to load markers in my map, but I want to load just those who are in the shown area of the app.
To do this I'd need the most northeast and the most southwest coordinates shown in the map. So I could find the markers using the $geoWithin and $box operator from MongoDB.

How I could get the map bounds? The coordinate more southwest and northeast of the shwon area of the map?

**Comment by texas697** [comment]
Code for bounds is in here. Search for bounds or delta

**Comment by andfs** [comment]
@texas697 the region gives me an object with the following fields:
timestamp
coords: { speed, heading, accuracy, longitude, altitude, latitude}

do you have a sample code?
Thanks

**Comment by texas697** [comment]
https://github.com/lelandrichardson/react-native-maps/issues/356

**Comment by andfs** [comment]
Thanks @texas697 :D
