### ISSUE TITLE
hey i am trying to fetch markers nearby user location 

### ISSUE THREAD

**Issue by sayedatif** [lelandrichardson/react-native-maps#422]
Hey guys i am trying to fetch markers nearby user location. I have used haversine formula and stored markers as an object in a selectedMarker array . I can see markers in the array when i console log it but when i am passing it as an MapView.Marker i get warnings can any body help me out 

here is the function which calculate distance and stores marker in an array

```
getWithinDistance: function(){
    var selectedMarker = [];
    var lat1 = this.state.region.latitude;
    var lon1 = this.state.region.longitude;
    for(var i = 0 ; i <= 3 ; i++)
      {
      var lat2 = this.state.a[i].latitude;
      var lon2 = this.state.a[i].longitude;
      var R = 6371;
      var dLat = (lat2-lat1) * (Math.PI/180);
      var dLon = (lon2-lon1) * (Math.PI/180);
      var a = Math.sin(dLat/2) * Math.sin(dLat/2) + Math.cos((lat1) * (Math.PI/180)) * Math.cos((lat2) * (Math.PI/180)) * Math.sin(dLon/2) * Math.sin(dLon/2);
      var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
      var d = R * c;
      if(d <= 2.00){
        var latlng = {
          latitude: lat2,
          longitude: lon2
        }
        selectedMarker.push(latlng);
      }
      }
      console.log(selectedMarker);
      var at = selectedMarker.map(marker => {
        return(
          <MapView.Marker coordinate={marker.latlng} />
        );
      })

  },
```
and here is the snap what i can see after running the app
![selected](https://cloud.githubusercontent.com/assets/6937774/17091833/a21209ca-525b-11e6-82f7-0ec42267b5ea.PNG)

**Comment by NomadGraphix** [comment]
You are incorrectly referencing `marker.latlng` instead
`var at = selectedMarker.map(marker => {
        return(
          <MapView.Marker coordinate={marker} />
        );
      })`
