### ISSUE TITLE
Initial Postion bases on geolocation

### ISSUE THREAD

**Issue by shieer** [lelandrichardson/react-native-maps#43]
Hi, Everyone, 
I'm not sure if I should write this question on here.

On my app, I did this on render:  
```
<MapView 
          style = {styles.mapView}
          initialRegion={this.state.currentRegion}
          showsUserLocation = {true}
          ))}
```

and I have this to get user's current position:

```
componentDidMount: function() {
    navigator.geolocation.getCurrentPosition(
      (position) => {
       console.log(position);
        this.setState({currentRegion: {
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          latitudeDelta: LATITUDE_DELTA,
          longitudeDelta: LONGITUDE_DELTA,
        }});
      },
      (error) => alert(error.message),
      {enableHighAccuracy: true, timeout: 20000, maximumAge: 1000}
    );
    this.watchID = navigator.geolocation.watchPosition((position) => {
       console.log(position);
      this.setState({currentRegion: {
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          latitudeDelta: LATITUDE_DELTA,
          longitudeDelta: LONGITUDE_DELTA,
        }});

    })
```

But with this, It's didn't auto move to current region on Android, but on iOS it'll move to current region when open that page. 

Thanks.

**Comment by graywolf336** [comment]
Sounds like that's async on android and sync on ios, but I could be wrong. Might be best to use `region` instead of `initialRegion`? That's just a guess though..

**Comment by lelandrichardson** [comment]
@shieer I suspect this is an issue where `onMapReady` has not been called yet when you're setting state. This would only end up being an issue on android.

When I get a sec I can try and get this code working on my machine...

**Comment by shieer** [comment]
@lelandrichardson Yes, it's only happen on Android. Thanks for your reply, I appreciate

**Comment by christopherdro** [comment]
@shieer Are you receiving coordinates at all?
Also, have you added `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
` to `AndroidManifest.xml` already?

**Comment by christopherdro** [comment]
@shieer Things are working fine for me. 
Closing this for now since we haven't heard back in a while. 
Feel free to re-open it again if the problem persists. Thanks!

**Comment by npomfret** [comment]
Do _navigator.geolocation.getCurrentPosition_ work and _navigator.geolocation.watchPosition_ work on android?  I'm just getting a timeout error.  I've got `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" /> `in my manifest file, and I can see the users current position (the blue dot) on a map, but I can't programatically get the position.

**Comment by ockka** [comment]
I’m having a similar issue. I can’t receive the initial position on Android via _navigator.geolocation.getCurrentPosition_ because it will timeout. But I can receive the position from _navigator.geolocation.watchPosition_ with Android. Currently I need to wait for the position before my component can be launched.

**Comment by npomfret** [comment]
I've debugged the java code and found that my device is not updating its GPS location very often.  The last update was over 12 hours ago.  So if I change my js code to allow _navigator.geolocation.getCurrentPosition_ to return a very old value it at least returns something now.  

I've no idea why the device is not updating the location.  I can see a blue dot on a MapView so I'm sure the GPS is working.  It's a new device, maybe I need to do something to it in order to make it work.

**Comment by jrichardlai** [comment]
@npomfret this is more a react-native question in the comments it says
```
 /**
   * Get the current position. This can return almost immediately if the location is cached or
   * request an update, which might take a while.
   *
   * @param options map containing optional arguments: timeout (millis), maximumAge (millis) and
   *        highAccuracy (boolean)
   */
 ```
Its possible you have to move around to update the location.

**Comment by npomfret** [comment]
Thanks. Looks like there's something wrong with the device, its only updating the gps very rarely, so yes a very large value for max age works around the issue.

**Comment by christopherdro** [comment]
Use distance filter option on the watchPosition method.

**Comment by tab1293** [comment]
Can confirm that I get a `Location request timed out` error on a S6 with this code:

```
componentWillMount() {
    this._setPosition();
}

_setPosition() {
    navigator.geolocation.getCurrentPosition((position) => {
        this.setState({
            position: position
        });
    }, (error) => {
        alert(error)
    }, {enableHighAccuracy: true, timeout: 20000, maximumAge: 1000});
}
```

Android manifest has proper permission:
 `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`

Is this an error with navigator.geolocation? Is there another library I can use for geolocation on Android devices?

**Comment by xvalentino** [comment]
Just a note, if you're on an emulator make sure you always have set your location.

**Comment by 42void** [comment]
Problem is solved if you remove enableHighAccuracy: true

**Comment by AugustoAleGonZhipCode** [comment]
@tab1293 Probably a newbie question. But how can I get access to the position? I am just starting on React Native enviroment. I hope you can answer me.

**Comment by koz** [comment]
@AugustoAleGonZhipCode Check this section of the React Native docs https://facebook.github.io/react-native/docs/geolocation.html

**Comment by ababba15** [comment]
Could we guys somehow get the `blue dot` coords? It would be a perfect solution for tons of user location tracking problems. Because `navigator.geolocation` is not cool at all..

**Comment by petrovakd** [comment]
really, it would be great! it's quite strange that we can see this dot but don't have access to its coords

**Comment by hoboman313** [comment]
Not sure what ppl's problem is with 42void's solution of removing `enableHighAccuracy: true`. It seems very counter-intuitive, but somehow it's been the only solution to get my map to center on the blue dot coords. Surprisingly my geolocation is much more precise without it (just luck?).

**Comment by ababba15** [comment]
@hoboman313 oh really??
Need to be checked : )

**Comment by joelGarcia93** [comment]
this code work perfectly in the cellphone (Im not using emulator)


import React, { Component } from 'react';
import {
  Text,
  View
} from 'react-native';

export default class App extends Component<{}> {

  constructor(props) {
    super(props);
    this.state = {
      initialPosition: 'unknown'
    };
  }

  componentDidMount() {
    navigator.geolocation.getCurrentPosition(
      (position) => {
        var positionCoordinates = JSON.stringify(position);
        this.setState({initialPosition: positionCoordinates});
      },
      (error) => alert(error.message),
      {enableHighAccuracy: true, timeout: 20000, maximumAge: 1000}
    );

  }

  render() {
    return (
      <View>
        <Text>initial: { this.state.initialPosition }</Text>
      </View>
    );
  }
}

**Comment by amit13091992** [comment]
```
  state = {
    focusedLocation: {
      latitude: 18.7934829,
      longitude: 98.9867401,
      latitudeDelta: 0.0122,
      longitudeDelta: Dimensions.get("window").width / Dimensions.get("window").height * 0.0122,
      locationChosen: false
    }
  }  

getLocationHandler = () => {
    Geolocation.getCurrentPosition(pos => {
      console.log('lat', pos.coords.latitude);
      console.log('lng', pos.coords.longitude);
      const coordsEvent = {
        nativeEvent: {
          coordinate: {
            latitude: pos.coords.latitude,
            longitude: pos.coords.longitude
          }
        }
      };
      console.log(" co-ordinates " + JSON.stringify(coordsEvent));
      this.pickLocationHandler(coordsEvent);
    },
      err => {
        console.log(err);
        alert("Fetching the Position failed, please pick one manually!");
      })
  }
  pickLocationHandler = event => {
    const coords = event.nativeEvent.coordinate;
    console.log("pickLocationHandler Co-Ordinates: " + JSON.stringify(event.nativeEvent.coordinate));
    this.map.animateToRegion({
      ...this.state.focusedLocation,
      latitude: coords.latitude,
      longitude: coords.longitude
    });
    this.setState(prevState => {
      return {
        focusedLocation: {
          ...prevState.focusedLocation,
          latitude: coords.latitude,
          longitude: coords.longitude
        },
        locationChosen: true
      };
    });
  };

render() {
    return (
<MapView
          initialRegion={this.state.focusedLocation}
          onMapReady={this.getLocationHandler}
</MapView>
);
}
```

by using onMapReady() method you can set the map region automatically based on your current region and location.
