### ISSUE TITLE
'Cannot evaluate module' react-native-maps [0.7.1] on react-native [0.30.0]

### ISSUE THREAD

**Issue by perkola** [lelandrichardson/react-native-maps#433]
Installing react-native-maps on a blank react-native project results in the following error message upon running `react-native run-android`:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-maps : Configuration with name 'default' not found.
```

According to an example there should be an import statement in the `MainApplication.java`
```
import com.airbnb.android.react.maps.MapsPackage;
```
However that module does not exist in the namespace. Any ideas?

`rnpm link` works and everything is done according to [the instructions](https://github.com/lelandrichardson/react-native-maps/blob/master/docs/installation.md#android).

**Comment by sarovin** [comment]
#411 #426

**Comment by gferreyra91** [comment]
@perkola can you fix the problem?

**Comment by perkola** [comment]
@gferreyra91 solved it by installing everything from scratch, then copied over my project specific code.
