### ISSUE TITLE
Android map view calls onLayout when adding a new child

### ISSUE THREAD

**Issue by jrichardlai** [lelandrichardson/react-native-maps#44]
It seems that `MapView._onLayout` is called multiple times when updating the markers. It does not happen for iOS only for Android.

This cause an issue that it repositions the map to the `initialRegion` everytime, not sure in Android what triggers the `onLayout` call.

I have currently a workaround in the component that uses MapView which is that after the first load to not return the `initialRegion` prop anymore.

The best would be to fix this in Android but it's also possible to fix this in JS ( set a boolean on componentDidMount and set it / check it in `_onLayout`, unless you think of other issues this could cause ) I could do a PR for that if you want.

**Comment by lelandrichardson** [comment]
@jrichardlai can you upgrade to the latest version of the lib?  I believe this should be fixed.

**Comment by jrichardlai** [comment]
Yep works well! Good job! Sorry didn't looked at the fix history, you going too fast ;) ! Also any idea why it triggers multiple times? Is it supposed to happen with Android ?

**Comment by lelandrichardson** [comment]
@jrichardlai it seems to fire a lot more in android 5.0 versus other versions. It's not clear to me why. :/
