### ISSUE TITLE
RCTImageLoader Deprecation

### ISSUE THREAD

**Issue by JaysonMandani** [lelandrichardson/react-native-maps#442]
[
![simulator screen shot 1 aug 2016 15 56 16](https://cloud.githubusercontent.com/assets/1963153/17287194/b9741b1c-5800-11e6-9f90-20db26ed5f24.png)
](url)

**Comment by terminull** [comment]
I solved this warning like so:

```javascript
<MapView.Marker
  coordinate={location}
>
  <Image
    source={require('image.png')}
    style={{width: 80, height: 60}}
  />
</MapView.Marker>

```

**Comment by JaysonMandani** [comment]
It works! but there's a latency on showing the image on the map.. anyways I will close this issue thanks!
