### ISSUE TITLE
[ Android ][ Marker ][ Error ] No position in marker options

### ISSUE THREAD

**Issue by ParamveerSisodia** [lelandrichardson/react-native-maps#451]
I am trying to run the example at https://github.com/lelandrichardson/react-native-maps/blob/master/example/examples/DefaultMarkers.js and tried others also , 
but getting following error when i try to set a marker on map.

![device-2016-08-09-113125](https://cloud.githubusercontent.com/assets/1322807/17510991/e2c369de-5e3e-11e6-9eff-a682a418b1e9.png)

My gradle file :
compile 'com.google.android.gms:play-services-maps:8.4.0'
 compile 'com.facebook.react:react-native:0.30.0'
compile 'com.airbnb.android:react-native-maps:0.7.1'I can see the map loading .

can anybody help with the suggesting what is it that i am doing wrong?

following is my code :
var React = require('react');
var ReactNative = require('react-native');
var {
  StyleSheet,
  PropTypes,
  View,
  Text,
  Dimensions,
  TouchableOpacity,
  AppRegistry
} = ReactNative;

var MapView = require('react-native-maps');

var { width, height } = Dimensions.get('window');

const ASPECT_RATIO = width / height;
const LATITUDE = 37.78825;
const LONGITUDE = -122.4324;
const LATITUDE_DELTA = 0.0922;
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;
let id = 0;

function randomColor() {
  return '#'+Math.floor(Math.random()*16777215).toString(16);
}

var maps= React.createClass({
  getInitialState() {
    return {
      region: {
        latitude: LATITUDE,
        longitude: LONGITUDE,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
      },
      markers: [],
    };
  },

  onMapPress(e) {
    this.setState({
      markers: [
        ...this.state.markers,
        {
          coordinate: e.nativeEvent.coordinate,
          key: id++,
          color: randomColor(),
        },
      ],
    });
  },

  render() {
    return (
      <View style={styles.container}>
        <MapView
          style={styles.map}
          initialRegion={this.state.region}
          onPress={this.onMapPress}
        >
          {this.state.markers.map(marker => (
            <MapView.Marker
              key={marker.key}
              coordinate={marker.coordinate}
              pinColor={marker.color}
            />
          ))}
        </MapView>
        <View style={styles.buttonContainer}>
          <View style={styles.bubble}>
            <Text>Tap to create a marker of random color</Text>
          </View>
        </View>
      </View>
    );
  },
});

var styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  bubble: {
    backgroundColor: 'rgba(255,255,255,0.7)',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 20,
  },
  latlng: {
    width: 200,
    alignItems: 'stretch',
  },
  button: {
    width: 80,
    paddingHorizontal: 12,
    alignItems: 'center',
    marginHorizontal: 10,
  },
  buttonContainer: {
    flexDirection: 'row',
    marginVertical: 20,
    backgroundColor: 'transparent',
  },
});

AppRegistry.registerComponent('maps', () => maps);

**Comment by kakbeya** [comment]
Maybe try to console.log(e) inside onMapPress(e) {} and see what are you getting back?

**Comment by ParamveerSisodia** [comment]
Thanks , I do get correct coordinates . I have validated that by putting
break point in the code.

**Comment by ParamveerSisodia** [comment]
Ping !

**Comment by ParamveerSisodia** [comment]
found the issue, 
1) Google playservice maps version was not latest in my gradle file
2) Proguard rules were not set properly .

Closing it .
Thanks
