### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by maxs15** [lelandrichardson/react-native-maps#454]
Hi,

Would it be possible to push a new version to NPM ?
It looks like there is some major fixes like the fix on the includes.

Thanks

**Comment by alexHlebnikov** [comment]
@lelandrichardson is there a chance for release of new version?

**Comment by jeveloper** [comment]
AirBnb and Facebook has long forgotten about this lib, just use direct githublink guys 
its sad

**Comment by maxs15** [comment]
The lib is still maintained, we just need someone kind enough to type ``npm publish``:)

**Comment by spikebrehm** [comment]
I just released [0.8.0](https://github.com/lelandrichardson/react-native-maps/releases/tag/v0.8.0).
