### ISSUE TITLE
Markers animation don't work on Android

### ISSUE THREAD

**Issue by alexHlebnikov** [lelandrichardson/react-native-maps#455]
I'l trying to make my markers animatable. So, I've done everything like it's written in the instruction [here] (https://github.com/lelandrichardson/react-native-maps#using-with-the-animated-api). 

And it works great, but unfortunately only on iOS. 
There is absolutely no animation of my markers on Android.
Btw, the MapView animation works great both on Android and on iOS.

Tested on RN 0.29.0, 0.30.0, 0.31.0.
I'll try to make an example code for this issue.

**Comment by perkola** [comment]
Are you running on an emulated or a physical device?
If on an emulated device, make sure that you have installed the appropriate Google packages via the SDK Manager in Android Studio.
If on a physical device, make sure that you have installed the latest Google Play services.

**Comment by alexHlebnikov** [comment]
I'm running on Genymotion, with latest version on Google packages:
```
compile 'com.android.support:appcompat-v7:24.1.1'
compile 'com.facebook.react:react-native:+'
compile 'com.google.maps.android:android-maps-utils:0.4.3'
compile 'com.google.android.gms:play-services-base:9.4.0'
compile 'com.google.android.gms:play-services-maps:9.4.0'
compile 'com.google.android.gms:play-services-ads:9.4.0'
```

```
compileSdkVersion 23
buildToolsVersion "23.0.3"
minSdkVersion 16
targetSdkVersion 23
```

**Comment by perkola** [comment]
I have no experience in Genymotion, but the packages i have install (via the SDK Tools in Android Studio) are:
```
Android SDK Build Tools
Android SDK Platform-Tools 23.1
Android SDK Tools 25.1.6
Google Repository
Intel x86 Emulator Accelerator (HAXM installer)
```

**Comment by alexHlebnikov** [comment]
Yep, I have all these tools & extras installed too, except some version of them are newer than yours: 
```
Android SDK Build Tools 19.1-24.0.1
Android SDK Platform-Tools 24.0.1
Android SDK Tools 25.2
Google Repository
Intel x86 Emulator Accelerator (HAXM installer)
and so on
```

**Comment by alexHlebnikov** [comment]
Another thing I figured out. 

My markers have two states (and styles accordingly): *default* and *active* (when you click on them). The styles are different and the styles transition is animated. 
So, if Hot Reloading and Live Reload are enabled, if I click on marker (nothing happens with it styles), when I updating the Marker component with any text (just to make hot reloading to trigger), after hot reloading the clicked marker styles are changed to "active"! 

It's pretty odd behaviour. So maybe it helps to figure out there the problem lies.

**Comment by alexHlebnikov** [comment]
Also, today I've got this error: 
![screenshot 2016-08-10 19 38 45](https://cloud.githubusercontent.com/assets/1951398/17554036/29c80a66-5f33-11e6-987b-f839c38df0c6.png)

And here are my animated styles: 
```
image: {
    transform: [
        {
            scale: this.animated.size.interpolate({
                inputRange: [0, 1],
                outputRange: [.1, 1]
            })
        }
    ],
    top: this.animated.size.interpolate({
        inputRange: [0, 1],
        outputRange: [24, 0]
    }),
    opacity: this.animated.size.interpolate({
        inputRange: [.15, .3, 1],
        outputRange: [0, 1, 1]
    })
},
```

So, maybe the there is a problem with animation of  ```transform``` property?

**Comment by alexHlebnikov** [comment]
*Update*: I find out what animation don't work only _on marker click event_. 
On other events animation is working. 

But how should I correctly handle click event? 
Now I'm usdng ```onPress``` and it works correctly on iOS.
```onMarkerPress``` don't work on iOS and on Android.

**Comment by alexHlebnikov** [comment]
So, finally I find out why I can't animate markers on Android. 
It's because Google Maps API don't have such possibility. Markers in Google Maps are bitmaps, and they don't meant to be animated by design. 
So, there is no way to animate markers on Android now.
