### ISSUE TITLE
'React/RCTComponent.h' file not found in AIRMap.h

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [lelandrichardson/react-native-maps#458]
```
#import <MapKit/MapKit.h>
#import <UIKit/UIKit.h>
#import <React/RCTComponent.h>
 		 ^
```

Replacing `#import <React/RCTComponent.h>` by `#import <RCTComponent.h>` every time in 'node_modules' is not the correct way.

**Comment by nazywamsiepawel** [comment]
+1, I'm having the same issue after updating to 0.7.1 + RN 0.31

**Comment by nabn** [comment]
see [#371](https://github.com/lelandrichardson/react-native-maps/issues/371)

**Comment by SupriyaKalghatgi** [comment]
@nabn Manually updating the `import` statements is not that i want to do

**Comment by steinhartalex** [comment]
+1. Still having the same issue !

**Comment by spikebrehm** [comment]
I just released [0.8.0](https://github.com/lelandrichardson/react-native-maps/releases/tag/v0.8.0), which fixes this issue.

**Comment by olegserov** [comment]
For those who ends up here from google, if you still experiencing same issue, try this solution: https://github.com/react-community/react-native-maps/issues/2324

**Comment by parnekov** [comment]
> ```
> #import <MapKit/MapKit.h>
> #import <UIKit/UIKit.h>
> #import <React/RCTComponent.h>
>          ^
> ```
> Replacing `#import <React/RCTComponent.h>` by `#import <RCTComponent.h>` every time in 'node_modules' is not the correct way.

replacing "<>" to doublequotes - "" ""
