### ISSUE TITLE
Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by nbastoWM** [lelandrichardson/react-native-maps#46]
The example project runs OK but when I apply the module to a fresh new project or an existing RN 0.17 project I get this error when compiling for Android:

```
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-maps : Configuration with name 'default' not found.
```

**Comment by nbastoWM** [comment]
OK; found the solution: it's due to installing dependencies with ```rnpm link ```.

It creates links with absolute paths in ```settings.gradle``` and somehow the error occurs.

I installed manually and I got it working!

**Comment by trinhvanhuy** [comment]
Hello
I have same problem with yours, 
I've tried installing manually, but it doesn't help :(

**Comment by sagar-kiwi** [comment]
module is not found in node module.. please check and re-install
