### ISSUE TITLE
Marker image

### ISSUE THREAD

**Issue by yedeba** [lelandrichardson/react-native-maps#47]
Hi,
Is it possible to assign a new image to a marker onSelect event?
Thanks!! :)

**Comment by lelandrichardson** [comment]
Hi Yedaba,

It sounds to me like that should work. Keep in mind that the `onSelect` event is not currently implemented on android, though.

**Comment by yedeba** [comment]
With this code don't work:

makeEvent(e,markerid, latlng) {
    this.refs.map.animateToRegion(latlng);
    this.refs.markerid.image = require('./img/iconselect@2x.png');
 },

Error: Attempted to assign to readonly property.

**Comment by lelandrichardson** [comment]
Why are you trying to set the image in a mutable way? You will want to do this through `state` and passing it through to `<Marker />` as props:

```jsx
<Marker image={this.state.markerImage} />
```

**Comment by yedeba** [comment]
Sorry, perhaps I have not explained well.
Yes i do.
makeEvent function is only for onSelect event marker.
First, the marker has an image,
when you select the marker, this image should be changed to another.
It would be possible with a new marker method?
Thanks

**Comment by lelandrichardson** [comment]
Just do this?
```
this.setState({ markerImage: require('./img/iconselect@2x.png') })
```

Sorry, am I missing something?

**Comment by yedeba** [comment]
Thanks,
that works for all markers,
but only need to change the image of the one selected marker.

**Comment by lelandrichardson** [comment]
@yedeba you're going to have to figure out how to handle this using state in your application. You could have an array of marker objects and just set it for that specific one...

Going to close this for now since this is not an issue with the library.

**Comment by yedeba** [comment]
Ok, perfect I will do it
thanks!!
