### ISSUE TITLE
cannot find symbol new MapsPackage() in MainApplication

### ISSUE THREAD

**Issue by wnqnguo** [lelandrichardson/react-native-maps#471]
I followed the installation guide but the build fails when I run react-native run-android, and the command line gives me this error:
![image](https://cloud.githubusercontent.com/assets/6914629/17725588/64687642-6401-11e6-8dde-d2f725d758ba.png)

**Comment by JonoH** [comment]
You need to add `import com.airbnb.android.react.maps.MapsPackage;` to your MainApplication.java file. It isn't mentioned in the documentation so the manual installation of the module will fail if this import line isn't present.

**Comment by wnqnguo** [comment]
Thank you! it solved the cannot find symbol problem.

**Comment by spikebrehm** [comment]
Documentation updated in #439.
