### ISSUE TITLE
Load markers, old ios versions.

### ISSUE THREAD

**Issue by gplopes** [lelandrichardson/react-native-maps#48]
Hi All,

I'm wondering if there is some reason for the markers are not being loaded on the map for old ios versions, I'm testing on 7.1.2 iPhone4 the map loads ok, but somehow not the markers. I have antoher iPhone5s with the latest version and everything load fine.

Thanks.

**Comment by lelandrichardson** [comment]
Hi @gplopes ,

Thanks for submitting this issue. What actually ends up getting rendered? Are the markers just not shown on the map at all?

I have not had much chance to make sure this library is working well with iOS < 9, but I would like to have compatibility wherever i can.

**Comment by gplopes** [comment]
Hi @lelandrichardson,

No problems at all, great plugin btw. It looks like the default markers are not getting rendered. I installed the examples from the master repo to be sure and they still not being rendered however the image based markers works fine.

**Comment by christopherdro** [comment]
I haven't had a chance to dig in too deep, but it appears that the issue is coming from https://github.com/lelandrichardson/react-native-maps/blob/master/ios/AirMaps/AIRMapMarker.m#L71-L72

**Comment by christopherdro** [comment]
@gplopes You can give this another shot.
