### ISSUE TITLE
search place in react-native-maps

### ISSUE THREAD

**Issue by luyuan11233** [lelandrichardson/react-native-maps#481]
i need search place in react-native-maps,but in the api,i can't see it ~~~

**Comment by jeveloper** [comment]
It doesnt exist, you can make a component (just an input box) and use google to reverse address to location and update this component.

**Comment by spikebrehm** [comment]
Indeed, such a feature would exist outside of the scope of `react-native-maps`.

**Comment by luyuan11233** [comment]
thanks,it worked
