### ISSUE TITLE
Could not resolve com.android.tools.build:gradle:2.1.0.

### ISSUE THREAD

**Issue by 2rajpx** [lelandrichardson/react-native-maps#484]
Why do I get this error???
![image](https://cloud.githubusercontent.com/assets/19687157/17884713/003f098c-692f-11e6-9c84-4ace8aae68b0.png)

SDK extra
![image](https://cloud.githubusercontent.com/assets/19687157/17884977/545f5426-6930-11e6-8fe5-2a100a041a95.png)

build.gradle
![image](https://cloud.githubusercontent.com/assets/19687157/17885020/802db70a-6930-11e6-9a4c-adc6717defc1.png)

AndroidManifest.xml
![image](https://cloud.githubusercontent.com/assets/19687157/17885093/de08bf00-6930-11e6-806b-eeb96b775d01.png)

MainApplication.java
![image](https://cloud.githubusercontent.com/assets/19687157/17885131/16e4f3ac-6931-11e6-8ef7-6a4a23a67a3e.png)

Can anybody help me?

**Comment by alexHlebnikov** [comment]
@2rajpx check your `build.gradle`, there must be something like this: 
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.google.gms:google-services:3.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

**Comment by 2rajpx** [comment]
@alexHlebnikov Thanks, But now I get another error
`
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-maps : Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
`

**Comment by alexHlebnikov** [comment]
Check what react-native-maps correctly added in build.gradle and in settings.gradle and what there are no equal repeating lines there (f.e. `compile project(':react-native-maps')` `compile project(':react-native-maps')`)

**Comment by alexHlebnikov** [comment]
Also try to update to `com.android.tools.build:gradle:2.1.3`

**Comment by felipecsl** [comment]
Also make sure you `npm install`
