### ISSUE TITLE
TouchableOpacity in Custom Marker doesn't work on Android

### ISSUE THREAD

**Issue by shieer** [lelandrichardson/react-native-maps#49]
I created a custom marker view with a button in it, it works well on iOS, but it's no touch event triggers on Android. 

![screen shot 2016-01-26 at 11 19 08 am](https://cloud.githubusercontent.com/assets/1696788/12591860/af67b528-c41e-11e5-819a-000acbe7b846.png)

**Comment by lelandrichardson** [comment]
@shieer android will have limitations here. Android renders the markers and the callout as bitmaps directly, and they don't have interactivity.

The best you can really do here is capture the onPress event and use the `position` property of the event to calculate where the user pressed. 

Unfortunate, I know... but currently there are no maps implementations on android that don't implement markers and callouts as bitmaps.

It *might* be possible though to implement callouts ourselves and not use the gmaps implementation. I'd love some help for this, but if there is enough demand I might take a crack at it myself.

**Comment by shieer** [comment]
@lelandrichardson  Thanks for your answer, that helps.

**Comment by gunters63** [comment]
MapView.Marker onCalloutPress works with the native built-in Android map callout

````
   <MapView.Marker key={m.id} coordinate={m.coordinate} title={m.title} description={m.description} 
      onCalloutPress={() => {this._onAnnotationPress(m.id)}}>
    </MapView.Marker>
````

Wouldn't it be possible to support that for custom callouts too? So that at least we can have click events on the whole callout?

**Comment by lelandrichardson** [comment]
@gunters63 yes, we could potentially have click events on the entire rendered view, just not on specific components, and handling `<Touchable*>` properly is probably never going to be possible (without additional support from the maps library itself).

The `onMarkerPress` event should work for you here. That works right now on android IIRC.

**Comment by tonygriv** [comment]
@yuoppp, same here

**Comment by Drienn** [comment]
This had the equivalent effect on user interaction through android and ios. You just need to put the onPress on the `<Map.Marker>`  and put whatever you want that marker to look like inside of the Marker. 
```
  return Platform.OS === 'ios' ? (
        <MapView.Marker
          key={ `${location.id}${Date.now()}` }
          coordinate={{latitude, longitude }}>
            <View >
            <TouchableOpacity
            style={ activeId === locationId ? Styles.markerPressed : Styles.marker }
            >
              <SearchMapCallout
                setChosen={this.props.setChosen}
                navigate={navigate}
                location={location}
                locations={this.props.locations}
                onPress={this.calloutPress} />
              </TouchableOpacity>
            </View>
        </MapView.Marker>
    ) :

    <MapView.Marker
      onPress={this.calloutPress.bind(this, location)}
      style={{zIndex: 10}}
      // onPress={() => this.forceUpdate()}
      key={ `${location.id}${Date.now()}` }
      coordinate={{latitude, longitude }}>
        <View style={[activeId === locationId ? Styles.markerPressed : Styles.marker]}>
          <Text style={Styles.price}>${location.price_with_extent}</Text>
        </View>
      </MapView.Marker>
  }
```
Hope that helps!

**Comment by lfoliveir4** [comment]
@shieer The MapView component contains a property called onMarkerPress. This property works on both platforms.

Ex: <MapView onMarkerPress={() => function } />

**Comment by chriswilsondev910** [comment]
onMarkerPress is wokring fine for me

**Comment by csulit** [comment]
> @SHIEER The MapView component contains a property called onMarkerPress. This property works on both platforms.
> 
> Ex: <MapView onMarkerPress={() => function } />

This solves my issue. Thanks!
