### ISSUE TITLE
0.7.1 incompatible with RN0.32.0

### ISSUE THREAD

**Issue by kfiroo** [lelandrichardson/react-native-maps#490]
Hey,
`react-native-maps` on `iOS` does not compile with RN0.32.0 as the `RCTImageLoader` interface no longer has `loadImageWithTag`.
It is already fixed on master, I think we only need to publish a new version :)

**Comment by kcfgl** [comment]
+1 on this.  Thanks!

**Comment by kfiroo** [comment]
Another thing I notice after upgrading to RN32 is that 
`MapMarker`
`MapPolyline`
`MapPolygon` 
`MapCircle`
`MapCallout`
`MapView` 
Are all requiring `NativeMethodsMixin` from `react-native` but it is not exposed anywhere so it resolves to `undefined` and react-native gives the following warning:
`ExceptionsManager.js:78Warning: ReactClass: You're attempting to include a mixin that is either null or not an object. Check the mixins included by the component, as well as any mixins they include themselves. Expected object but got undefined.`

From what I could see `NativeMethodsMixin` is not used in the code at all.
@lelandrichardson Am I right?

Anyway I think we should remove this

**Comment by kcfgl** [comment]
While you guys are working on publishing a new version, is there a workaround so I can get my project to build?  I can't roll back React-Native or I would.

**Comment by kfiroo** [comment]
@kcfgl I'm currently using my fork, you can use it too
in your `package.json` change:
`"react-native-maps": "0.7.1"` -> 
`"react-native-maps": "https://github.com/kfiroo/react-native-maps.git#1d1758fbf95c91e5b6e57d4dcac12344c2fc60a5"`

**Comment by spikebrehm** [comment]
The `loadImageWithTag` issue was fixed here: https://github.com/lelandrichardson/react-native-maps/pull/456

The `NativeMethodsMixin` issue was fixed here: https://github.com/lelandrichardson/react-native-maps/pull/511

I'll be releasing 0.8.0 soon.
