### ISSUE TITLE
RCTImageLoader error 

### ISSUE THREAD

**Issue by sirgalleto** [lelandrichardson/react-native-maps#494]
When I load a image marker a yellow box display the error `[RCTImageLoader loadImageWithTag:size:scale:resize Mode:progressBlock:completionBlock:] is deprecated. Instead use [RCTImageLoader loadImageWithURLRequest:size:scale:clipped:resizeMode:progressBlock:completionBlock:]`

Whats the best way to update the library? I can update and create a pr but I dont find where is happening the bug.

**Comment by sirgalleto** [comment]
Ohh cool, the PR isnt merged, whats the plan?

**Comment by alexHlebnikov** [comment]
I recommend you to fork the repo and manually merge this pr. 
It will be much faster then waiting for maintainer to merge it into this repo.

**Comment by sirgalleto** [comment]
So what are you planning for the update?

**Comment by alexHlebnikov** [comment]
I really don't know. There are a lot of open PR's and nobody merges them or even reviews.

**Comment by esutton** [comment]
Does anyone have a stable react-native-map fork to share that works with both iOS and Android and a recent RN version? 

Or can recommend the latest version of react-native that is stable with a version of react-native-maps?  

I have spent days trying to find a solution.  I wish I would have stayed with react-native-maps 0.4.2.  Or started with Xamarin months ago.

After much effort upgrading from:
```
    "react": "15.0.2",
    "react-native": "0.26.2",
    "react-native-maps": "^0.4.2",
```
to:
```
    "react": "^15.3.1",
    "react-native": "^0.32.0",
    "react-native-maps": "^0.7.1",
```
The result is:

- Now map callouts no longer display correctly anymore on Android.
- On iOS rendering map just red-box crashes with:
```
2016-08-30 11:43:16.361 [error][tid:main][RCTConvert.m:57] Error setting property 'source' of RCTImageView with tag #369: JSON value '<null>' of type NSNull cannot be converted to NSString
dyld_image_header_containing_address(0x1019f6201)
```

**Comment by sirgalleto** [comment]
Oh yes, Im revert the change becouse the solution have a collision bug bilding for ios.

I dont know how repare this bug, bit its a warning and my app build without problems.

**Comment by spikebrehm** [comment]
The fix for this has already been merged: https://github.com/lelandrichardson/react-native-maps/pull/456

I'll be releasing 0.8.0 soon.
