### ISSUE TITLE
Detecting user drag event

### ISSUE THREAD

**Issue by johnryan** [lelandrichardson/react-native-maps#498]
I'm trying to add a "Search this area" button when the region change is a result of the user dragging the map but i'm having problems because onRegionChangeComplete can be triggered by general animation of the map. also onPanDrag requires disabling scroll of the map which sort of creates a catch-22. Thanks!

**Comment by athaeryn** [comment]
I had to do the same thing, and implemented it this way:

```jsx
<View
  onMoveShouldSetResponder={(evt) => {
    this.onPanDragStart()
    return true
  }}
  onResponderRelease={this.onPanDragStop}
>
  <MapView />
</View>
```

Hope it helps!

**Comment by johnryan** [comment]
Awesome solution! thanks.

**Comment by morrislaptop** [comment]
@athaeryn this is great! If a user double taps to zoom, is there anyway to detect that?

**Comment by johnryan** [comment]
@morrislaptop I think you'd probably have to build your own logic on top of the "onPress" callback..something like https://gist.github.com/mrzmyr/9ac94ca4622c1602a2a3

**Comment by sam17896** [comment]
> ```js-jsx
>  onMoveShouldSetResponder={() => {
>     this.onPanDragStart()
>     return true
>   }}
>   onResponderRelease={this.onPanDragStop}
> ```

Not working on IOS

**Comment by davidfarinha** [comment]
The `onTouchStart` prop is what you're looking for here:

```<Map
	onTouchStart={() => {
	   // Code here
	}}
        />```
