### ISSUE TITLE
How to run the project example?

### ISSUE THREAD

**Issue by nbastoWM** [lelandrichardson/react-native-maps#5]
I'm anxiously waiting for this to get to npm!

Meanwhile I've copied the project files, run npm install and when I run the project in iOS I get an error:
'Image' has no propType for native prop RCTImageView.defaultImageSrc of native type UIImage.
![image](https://cloud.githubusercontent.com/assets/15138821/12331385/2ed629b2-bae1-11e5-9e5f-4849d07a9162.png)

In Android, when I run "react-native run-android" I get an error:
"   > Could not find com.google.android.gms:play-services-base:8.3.0."
"   > Could not find com.google.android.gms:play-services-maps:8.3.0."

What am I doing wrong?

**Comment by lelandrichardson** [comment]
Hi nbasto!

Thanks for your questions.

Couple of things:

1. the `image` prop will not work for android. I just merged in the code to make it work for ios last night. I suspect the code you have downloaded is trying to run the example that uses that prop (my fault).
2. You need to have google play services installed on your device. There are several guides for this, but it's surprisingly difficult (at least it was for me). I believe I followed this guide: http://stackoverflow.com/questions/20121883/how-to-install-google-play-services-in-a-genymotion-vm-with-no-drag-and-drop-su
3. After you do this, remember to specify a Google Maps API key in the AndroidManifest.xml
4. If you want to use the examples using `Animated` stuff, you will need to change your implementation of `AnimatedImplementation.js` inside react-native. You can replace it with this: https://gist.github.com/lelandrichardson/c0d938e02301f9294465

I'm working on getting some of this into the readme. thanks for your patience!

**Comment by nbastoWM** [comment]
Shouldn't my Android device (Note 3 Neo) have that installed? 
I tryed to run the example with 2 different devices but the same error happens. 

Meanwhile, in iOS it keeps showing me the "Image has no propType for native prop RCTImageView.defaultImageSrc" error.

Is there any update on the example so we can run it as is?

Thanks!

**Comment by lelandrichardson** [comment]
I'm closing this issue now. The project is now published on NPM, documented examples are in the readme. Enjoy!
