### ISSUE TITLE
Warning: ReactClass: You're attempting to include a mixin that is either null or not an object. Check the mixins included by the component, as well as any mixins they include themselves. Expected object but got undefined.

### ISSUE THREAD

**Issue by uriklar** [lelandrichardson/react-native-maps#512]
I'm getting this error from several react-native-maps components using RN0.32
I'd be happy to provide any additional required information

Thanks!
Uri

**Comment by ryankask** [comment]
Have you upgraded to 0.8.0?

**Comment by uriklar** [comment]
Did now, and it solved the problem indeed. Thanks!

**Comment by zxc19890923** [comment]
excuse me
is it solved?
