### ISSUE TITLE
failed to find Build Tools revision 23.0.3 / [RN 0.32 maps 0.8.0]

### ISSUE THREAD

**Issue by mike866** [lelandrichardson/react-native-maps#513]
Hey guys - i'm getting following error while using your package on android.

![image](https://cloud.githubusercontent.com/assets/7837457/18138737/78643d80-6fae-11e6-8cc4-008e4f01d13d.png)

I've tried searching other issues and found something similar but solution leads nowhere since it requires old gradle setup.

Anyway - i've read https://github.com/lelandrichardson/react-native-maps/pull/502 and didn't managed to find a solution there. any ideas?

**Comment by alexHlebnikov** [comment]
Is build tools revision 23.0.3 installed?

**Comment by mike866** [comment]
Yeah - i think so.

![image](https://cloud.githubusercontent.com/assets/7837457/18148218/a229e348-6fd8-11e6-94f8-65c682343156.png)

Is this a right SDK?

**Comment by alexHlebnikov** [comment]
Yep, seems ok.  But recommend you to install all available SDK build-tools and check again.

**Comment by mike866** [comment]
I did but i'm still getting same error - any other ideas?

**Comment by mike866** [comment]
Rebuilding stuff in android studio, and cleaning gradle cache helped me solve this issue. Thanks.
