### ISSUE TITLE
libAirMaps.a is not being built and shown as red in XCode/Libraries/AirMaps.xcodeproj/Products/

### ISSUE THREAD

**Issue by pchengsf** [lelandrichardson/react-native-maps#523]
Thanks for the great library! I've followed the installation instructions for iOS but got stuck in step 2 (Add libAIRMaps.a to `Build Phases -> Link Binary With Libraries`.) as the `libAirMaps.a` is shown as red (meaning it's missing) by Xcode after I added the `AirMaps.xcodeproj` library. 

I tried `Product -> Clean` then `Product -> Build`. In my `Debug-iphonesimulator` folder, I see all the `libRCT*.a` files being wiped out and built but `libAirMaps.a` never showed up. 

Please advise. Thanks in advance.

**Comment by timurridjanovic** [comment]
I have the same issue. Anybody found out what was going on?

**Comment by wvicioso** [comment]
Same issue. Can  I see you closed this issue @pchengsf. Can you share your solution?

**Comment by pchengsf** [comment]
It's been a while, I think I just started over and it worked the second
time. It was just a toy project so I didn't dig too deep into it.

On Mon, Apr 3, 2017 at 8:43 AM, Wellington Vicioso <notifications@github.com

**Comment by jnrepo** [comment]
had to do the old fashioned workaround.

1. Close Xcode
2. ReOpen Xcode
3. Clean
4. Build

I hate Xcode
