### ISSUE TITLE
[Android] The first Map cover the second Map

### ISSUE THREAD

**Issue by sarovin** [lelandrichardson/react-native-maps#525]
### Version
- react-native-router-flux v3.31.2
- react-native v0.30.0
- react-native-maps v0.7.1

Hi,
i have a screen with a not draggable map and another screen with a draggable map where the user can set the marker.

![map issue](https://cloud.githubusercontent.com/assets/5980398/18173602/874f2550-706a-11e6-9498-062609ac60df.gif)

But the first map cover the second map...have you idea?

**Comment by jeveloper** [comment]
Hey, please upgrade to 0.8 , should be resolved

but you need to upgrade to RN 32 too

**Comment by sarovin** [comment]
Now i have:

react-native-router-flux v3.31.2
react-native v0.32.0
react-native-maps v0.8.0

but i have the same issue

**Comment by yasheshkt** [comment]
Well, I ran into the same issue. See my flow of components below

First I opened - MapComponent from Drawer Layout,
Second I opened - OtherComponent from Drawer Layout,
Third I opened - MapComponent from Drawer Layout,

When I opened MapComponent in third step, I get the same issue with one map being static and other above it.

**Comment by sarovin** [comment]
aksonov/react-native-router-flux#1149

**Comment by yozi-developer** [comment]
Same 
react-native v0.32.0
react-native-maps v0.8.0

**Comment by spikebrehm** [comment]
Tracking this in #207 and #453. Closing this now for keep track in those issues.
