### ISSUE TITLE
<MapView.Circle /> does not update its position when changing its center

### ISSUE THREAD

**Issue by ghamaide** [lelandrichardson/react-native-maps#54]
I'm trying to put a circle in the center of my map. I have the following : 
```
<MapView.Circle
    center={{latitude: this.state.region.latitude, longitude: this.state.region.longitude}}
    radius=1000
    fillColor="rgba(0, 0, 0, 0.2)"
    strokeColor="rgba(0, 0, 0, 0.2)"/>
```
but the circle doesn't change when I change region while my MapView has a onRegionChange method that sets the new region 
```
onRegionChange = (region) => {
    this.setState({region: region});
}
```

**Comment by lelandrichardson** [comment]
I need to try this out. If I understand your example as given, it seems to me like this should work.

**Comment by keeganmccallum** [comment]
+1, also experiencing this issue

**Comment by KevinWade** [comment]
I was having this issue on iOS.

It looks like instances of AIRMapCircle are never getting a reference to the AIRMap.  Adding  `((AIRMapCircle *)subview).map = self;` to line 90 of AIRMap.m fixed this.

**Comment by joshblour** [comment]
+1 with this problem. I think I remember this being the native behaviour on iOS. (not being able to change the position of an MKOverlay) I think you'll need to remove it and re-add it at the new position.

**Comment by lelandrichardson** [comment]
Sorry for the wait on this. I will get this fixed as soon as I get time. It sounds like @KevinWade had a fix... perhaps you're willing to PR?

I'm going to be heads down on ReactConf + Work for next week at least... but will get back to work on this some time after that.

Thanks for your patience!

**Comment by micksabox** [comment]
+1 experience this issue, fixed it using @KevinWade method

**Comment by fabiosussetto** [comment]
I confirm that Kevin's snippet above fixes the issue for me, and it also makes the radius property of the circle working on change.
