### ISSUE TITLE
Maps Got Blank, Pls Help

### ISSUE THREAD

**Issue by shindol** [lelandrichardson/react-native-maps#543]
Hi i'm just strat learning react netive, i got this problem on maps, the maps not shown .. already try to solve this but still the same, pls help

[![Problem.png](https://s16.postimg.org/yxe2i155x/Problem.png)](https://postimg.org/image/4fy7qhhsx/)

**Comment by attila135786** [comment]
I had the same issue on Android only. I had the same issue. I followed issue #497 and added 
    compile 'com.google.android.gms:play-services-auth:9.4.0' // should be at least 9.0.0
    compile 'com.google.android.gms:play-services-maps:9.4.0'
to my build.gradle file and it fixed the issue. I believe there were other suggestions in there as well.

**Comment by shindol** [comment]
@attila135786 thx i will try it ..
