### ISSUE TITLE
App Crashed with No such method message.

### ISSUE THREAD

**Issue by MuruganDurai** [lelandrichardson/react-native-maps#555]
My Android app getting crashed with below error message. Already tried with change 'com.google.android.gms:play-services-base:8.3.0' to 'com.google.android.gms:play-services-base:**8.4.0**' but didn't get it worked. RN version is 0.32 in windows environment.

Fatal Exception: java.lang.NoSuchMethodError
No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzx; or its super classes (declaration of 'com.google.android.gms.common.internal.zzx' appears in /data/app/com.ssssss-1/base.apk)

**Comment by mauron85** [comment]
You're probably on version 0.7.x of react-native-maps. Had same problem. Upgrade to version 0.8.2 of react-native-maps.

**Comment by felipecsl** [comment]
You should be using google play services `9.4.0`, which is the default for react-native-maps `0.8.2`

**Comment by MuruganDurai** [comment]
Hi @mauron85 @felipecsl , I have changed my code as suggested, app din't crashed, but there is a message saying that the app won't work unless update Google play services. Could not expect all the users to upgrade their play service version? How to make the app compatible with older versions of google play?

**Comment by mauron85** [comment]
I would say, they'll be eventually forced to update anyway (by google maps or other google app that will stop working). But you can stay on version 0.7.x and google play services 0.8.4. I did it this for https://github.com/mauron85/react-native-background-geolocation-example

But keep in mind, if any of react-native module also uses play services, you'll end up with multidex errrors. 

In my case it was module I'm developing myself, so fix was easy.

> **Module react-native-maps v0.7.1 requires Google Play Services library version 8.4.0 (issue #420), we need to change node_modules/react-native-mauron85-background-geolocation/android/lib/build.gradle
```
dependencies {
    ...
    compile 'com.google.android.gms:play-services-location:8.4.0'
    ...
}
```

**Comment by MuruganDurai** [comment]
@mauron85 Thanks a ton for detailed explanation. I am updating for play 9.4.

**Comment by felipecsl** [comment]
when an app requests a version of google play services newer than the one that the user has installed, it should automatically update in the background

**Comment by MuruganDurai** [comment]
App loaded after adding the following items at app/build.gradle. compile "com.google.android.gms:play-services-base:8.4.0" compile 'com.google.android.gms:play-services-auth:9.4.0' compile 'com.google.android.gms:play-services-maps:9.4.0' Now the app shows UPDATE button with message "this app won't run unless you update google play services"

**Comment by ammichael** [comment]
Anyone fixed the message "this app won't run unless you update google play services"? Can't find a solution. Runs fine on device, but not in simulator
