### ISSUE TITLE
Error trying to run the AnimatedViews example

### ISSUE THREAD

**Issue by ghamaide** [lelandrichardson/react-native-maps#56]
When trying to run the example on iOS, I get the following error : 
undefined is not a constructor (evaluating 'new Animated.Region({latitude: ....})'), that is thrown line 196 of the AnimatedViews example... I can't figure what I'm doing wrongly..

**Comment by lelandrichardson** [comment]
Please see the section of the readme that describes what you need to do: https://github.com/lelandrichardson/react-native-maps#using-with-the-animated-api

You will need to replace a file in react native.

**Comment by ghamaide** [comment]
OK, but I don't see which RN file needs to be replaced...

**Comment by lelandrichardson** [comment]
@ghamaide `AnimatedImplementation.js` needs to be replaced with the one in the linked gist

**Comment by ghamaide** [comment]
Ok thanks !
