### ISSUE TITLE
Issue with react-native 0.19

### ISSUE THREAD

**Issue by jrichardlai** [lelandrichardson/react-native-maps#59]
Not sure if I'm doing something wrong but with RN 0.19 props does not seems to be passed into the native components in Android.

I tried to render a MapMarker and it raised an error, I removed it and noticed that even my Map region was not set properly, I tried to debug it and it seem to not call the ReactProps setters.

Might be related to https://github.com/facebook/react-native/issues/5649? Tried to change the imports but it didn't resolved it.

Does it work fine with you ?

<img width="453" alt="screen shot 2016-01-31 at 2 22 22 pm" src="https://cloud.githubusercontent.com/assets/159813/12705466/44bd2f20-c827-11e5-9475-68b4c40ad41b.png">

**Comment by jrichardlai** [comment]
Update actually updating to `import com.facebook.react.uimanager.annotations.ReactProp` worked, I also had to update to `com.facebook.react:react-native:0.19.+` the react-native-maps `build.gradle`

**Comment by ahmed1490** [comment]
Can you try reversing the manual change and see if re-running `rnpm link` solves the problem?

**Comment by jrichardlai** [comment]
It didn't fixed it, does it work for you and RN 0.19 ?

**Comment by jrichardlai** [comment]
Made a branch if that helps https://github.com/jrichardlai/react-native-maps/tree/react-native-0.19 but it would only work for 0.19 version

**Comment by lelandrichardson** [comment]
hmm. this is a bummer. We can try to keep 2 branches? Or just move to only supporting 0.19+ in future versions?

**Comment by jrichardlai** [comment]
Yeah bummer. Seems that its due to this commit https://github.com/facebook/react-native/commit/c1b7a369af7ca457819d682b15f47fae7e2732fc . Up to you for what to do here, but RN is moving fast, there might be more things in the future that becomes incompatible, having master / latest release be compatible to the latest version of RN and having other branches for other versions would be better I think ( might be a nightmare to keep them all up to date though ).

**Comment by lelandrichardson** [comment]
@jrichardlai if you want to PR your branch, I will likely accept it. I'll do a minor version bump (ie, semver major because we are still 0.x) and increase the peer dep to 0.19

**Comment by jrichardlai** [comment]
https://github.com/lelandrichardson/react-native-maps/pull/60

**Comment by lelandrichardson** [comment]
The fix should be available now on 0.3.0
