### ISSUE TITLE
Can't seem to get this working on Android, just get a white background

### ISSUE THREAD

**Issue by sammosampson** [lelandrichardson/react-native-maps#61]
I've tried it by copying all code from the example\app.js down into a new react native app with react-native-maps setup as per the application instructions. I also have put the api key in the app.manifest and followed the instructions to install google play. I am using genymotion free with a custom phone 5.1.0 -api 22 image. 

It maybe due to the fact that the Google Apps zip would not flash. can you confirm this as the problem and what I can do about it.

**Comment by sammosampson** [comment]
after logcatting i get 'Google Play services is missing' going to retry the flash

**Comment by sammosampson** [comment]
everytime i try to to flash the google play zip to my genymotion device it just says failed to flash. ANy ideas?

**Comment by lelandrichardson** [comment]
@sammosampson usually you have to go through a couple of cycles of updating "Google Play Services" in the app store in order to get it to finally work. I think the error you are seeing is normal, you just need to keep going.

**Comment by sammosampson** [comment]
I got it working finally with your api key, but it doesn't seem to work
with mine

**Comment by BigPun86** [comment]
Had the same issue until i checked my developer console. I forgot to enable the Google Maps Api...Now it works great

**Comment by christopherdro** [comment]
@sammosampson Closing this since it appears resolved by providing a valid key.
