### ISSUE TITLE
Is there an interface to request access and get user location?

### ISSUE THREAD

**Issue by ahmed1490** [lelandrichardson/react-native-maps#63]

**Comment by EricPKerr** [comment]
https://facebook.github.io/react-native/docs/geolocation.html

**Comment by lelandrichardson** [comment]
Please use the provided geolocation APIs from RN. I think we've decided that we will not be adding it to the component directly. 

Thanks!

**Comment by petrovakd** [comment]
@lelandrichardson Can you explain why? It seem to be strange that we can see user position, but do not have an access to its coords. The main problem is that RNs navigator does not work properly, and RNs coords are different from coords of this dot. I just want to understand why it is impossible. I think that it is very common case - to open the map on region with user location. Thank you!
