### ISSUE TITLE
Do components provide JavaScript APIs or SDK APIs?

### ISSUE THREAD

**Issue by efkan** [lelandrichardson/react-native-maps#66]
Hello,
First of all, thanks for these awesome components.

Could you please tell me whether the components use native SDK parts or not? 

This is important because of payment issues. [Google specifies](https://developers.google.com/maps/pricing-and-plans/#details) the price of Google Maps API's usage as "Unlimited free usage" for Google Maps Android API. But JavaScript API usage is not free.

If only I could figure out from source code or [Installation Instructions](https://github.com/lelandrichardson/react-native-maps/blob/master/docs/installation.md) the answer of this question. Unfortunately I'm new in Native applications.

**Comment by lelandrichardson** [comment]
Hi @efkan ,

This only uses the Google Maps Android API. The JavaScript API is not used.

Thanks!
