### ISSUE TITLE
Ensure that the following Android Key exists

### ISSUE THREAD

**Issue by DanDance** [lelandrichardson/react-native-maps#69]
I ran into this [issue](https://github.com/lelandrichardson/react-native-maps/issues/45). I run my application on an android device, but the map is blank. `adb logcat | grep Google` says the following when i start my application:
`E/Google Maps Android API( 9266): Ensure that the "Google Maps Android API v2" is enabled.
E/Google Maps Android API( 9266): Ensure that the following Android Key exists:
E/Google Maps Android API( 9266): 	API Key: *here goes my Android API key*
E/Google Maps Android API( 9266): 	Android Application (<cert_fingerprint>;<package_name>): *here goes my cert finger print*;*here goes my package name*`

I've created an android api key using cert fingerprint and package name that match cert fingerprint and package name posted in this log. But somehow application says that there is no such api key. Seems that the problem is about the api key. Did anyone face this issue?

**Comment by DanDance** [comment]
Finally i made it.
Steps to fix were: 
1)I've uninstalled application from my device
2)Deleted app-debug.apk, app-debug-unaligned.apk from android/app/build/outputs/apk
3)Deleted Api Key from Google Developer Console
4)Generated new Api key
5)Added new Key to <meta-data> in AndroidManifest.xml
6)Built my app on device
Im not sure, but it seems like google cached my application data when i tried to authorize with invalid fingerprint.

Helpful links:
http://stackoverflow.com/questions/20106988/authorization-failure-with-google-map-api-key
https://code.google.com/p/gmaps-api-issues/issues/detail?id=6048

**Comment by mohamedpsx** [comment]
Had same issue, solved just by uninstalling and adding a new Key to in AndroidManifest.xml

Thanks!
