### ISSUE TITLE
Can't see anything

### ISSUE THREAD

**Issue by ericmuyser** [lelandrichardson/react-native-maps#76]
I know it's strange, but I followed the instructions and I just don't say anything. There's no errors. I've tried making it my root element. I've verified it's making it into the JS code using alerts. I suspect it's just failing to render to the view. I'm not sure what to try to figure out the root issue.

**Comment by lelandrichardson** [comment]
This is likely from either:

1. component isn't styled correctly. try applying `flex: 1` or something to the container. see example app.
2. google play services not being properly installed.
3. google maps API key not specified

Please provide more information if it is none of these issues. Closing in the interim.

**Comment by ericmuyser** [comment]
Applying `flex: 1` to the mapview element worked! Thanks mate!
