### ISSUE TITLE
Released unknown imageData reference

### ISSUE THREAD

**Issue by ghamaide** [lelandrichardson/react-native-maps#77]
I get this error on Android only when I try to update markers.
Here is my markers code : 

```
<MapView.Marker
  ref={restaurant.id}
  key={restaurant.id}
  coordinate={coordinates}
  onSelect={this.onSelect}
  pinColor={myRestaurant ? 'green' : 'red'}>
  <PriceMarker budget={restaurant.price_range} />
  <MapView.Callout>
    <TouchableHighlight underlayColor='rgba(0, 0, 0, 0)' onPress={() => this.props.navigator.push(Restaurant.route({id: restaurant.id}, restaurant.name))}>
      <View style={{flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start'}}>
        <Image source={{uri: restaurant.pictures[0]}} style={{height: 50, width: 50, marginRight: 5}} />
        <View>
          <Text style={{color: '#333333', fontSize: (Platform.OS === 'ios' ? 15 : 14), fontWeight: '500', marginBottom: 5}}>{restaurant.name}</Text>
          <Text style={{color: '#333333', fontSize: 13}}>{restaurant.food[1]}</Text>
        </View>
      </View>
    </TouchableHighlight>
  </MapView.Callout>
</MapView.Marker>
```

And here is the error : 

![screenshot_2016-02-12-15-51-49](https://cloud.githubusercontent.com/assets/6986811/13010242/1ad465c4-d1a1-11e5-8747-a5f0eae1c48f.png)

**Comment by badasve** [comment]
I have the same error, it seems to be related to garbage collection of markers not  on the map anymore, any idea how to solve it ?

**Comment by heydabop** [comment]
I was experiencing a similar error when I had an array of markers being rendered via a .map() operation, very similar to what happens in [DefaultMarkers.js#L60](https://github.com/lelandrichardson/react-native-maps/blob/master/example/examples/DefaultMarkers.js#L60). If I cleared the array, on the next render pass I would get this error.
I noticed that if I added `marker = null;` right after `marker.remove();` in [AirMapMarker.java#241](https://github.com/lelandrichardson/react-native-maps/blob/master/android/src/main/java/com/AirMaps/AirMapMarker.java#L241), it would prevent this error. I haven't tested other side effects to this, but setting the marker to null after removing it from the map prevents the manager from attempting to update it any further. Not sure if there's a situation where the same marker is removed and then added to the map again.

**Comment by badaz** [comment]
I'll try this right now, thanks !

**Comment by badasve** [comment]
It works thanks !

**Comment by badasve** [comment]
Hmmm after some testing it seems that markers are not removed from the map anymore when doing this

**Comment by badasve** [comment]
Oh I think I didn't do it correctly : I completely replaced the marker.remove() with marker = null, I will try leaving both

**Comment by heydabop** [comment]
Oh, weird. How so? They get removed for me but what I'm doing is pretty basic.

**Comment by heydabop** [comment]
Oh nvm, just saw your follow-up. Yea the call to remove() still needs to be there.

**Comment by badasve** [comment]
Working like a charm now, tx again
