### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by incrediblebutterfly** [lelandrichardson/react-native-maps#85]
I'm trying to create a simple "weather" app using react-native-maps on Android.

I have followed the installation steps but I get following errors when I run `react-native run-android`

**JS server already running. Building and installing the app on the device (cd android && ./gradlew installDebug)...
**
**FAILURE: Build failed with an exception.**

* What went wrong: A problem occurred configuring project ':app'.

A problem occurred configuring project ':react-native-maps'. Could not resolve all dependencies for configuration ':react-native-maps:_debugCompile'. Could not find com.google.android.gms:play-services-base:8.3.0. Searched in the following locations: file:/home/mihir/.m2/repository/com/google/android/gms/play-services-base/8.3.0/play-services-base-8.3.0.pom file:/home/mihir/.m2/repository/com/google/android/gms/play-services-base/8.3.0/play-services-base-8.3.0.jar https:// jcenter.bintray.com/com/google/android/gms/play-services-base/8.3.0/play-services-base-8.3.0.pom https:// jcenter.bintray.com/com/google/android/gms/play-services-base/8.3.0/play-services-base-8.3.0.jar file:/home/mihir/android-sdk-linux/extras/android/m2repository/com/google/android/gms/play-services-base/8.3.0/play-services-base-8.3.0.pom file:/home/mihir/android-sdk-linux/extras/android/m2repository/com/google/android/gms/play-services-base/8.3.0/play-services-base-8.3.0.jar Required by: weather:react-native-maps:unspecified Could not find com.google.android.gms:play-services-maps:8.3.0. Searched in the following locations: file:/home/mihir/.m2/repository/com/google/android/gms/play-services-maps/8.3.0/play-services-maps-8.3.0.pom file:/home/mihir/.m2/repository/com/google/android/gms/play-services-maps/8.3.0/play-services-maps-8.3.0.jar https:// jcenter.bintray.com/com/google/android/gms/play-services-maps/8.3.0/play-services-maps-8.3.0.pom https:// jcenter.bintray.com/com/google/android/gms/play-services-maps/8.3.0/play-services-maps-8.3.0.jar file:/home/mihir/android-sdk-linux/extras/android/m2repository/com/google/android/gms/play-services-maps/8.3.0/play-services-maps-8.3.0.pom file:/home/mihir/android-sdk-linux/extras/android/m2repository/com/google/android/gms/play-services-maps/8.3.0/play-services-maps-8.3.0.jar Required by: weather:react-native-maps:unspecified
* Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 20.584 secs Could not install the app on the device, rea

**Comment by DanDance** [comment]
Do you have Google Play Services installed?

**Comment by incrediblebutterfly** [comment]
Hi, thank you for reponding. Yes. I have just installed Google Play Services. I am now getting a new issue. It goes as follows - 

JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-maps:compileLint
:react-native-maps:copyReleaseLint UP-TO-DATE
:react-native-maps:preBuild UP-TO-DATE
:react-native-maps:preReleaseBuild UP-TO-DATE
:react-native-maps:checkReleaseManifest
:react-native-maps:preDebugAndroidTestBuild UP-TO-DATE
:react-native-maps:preDebugBuild UP-TO-DATE
:react-native-maps:preDebugUnitTestBuild UP-TO-DATE
:react-native-maps:preReleaseUnitTestBuild UP-TO-DATE
:react-native-maps:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-maps:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-maps:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
:react-native-maps:prepareComFacebookReactReactNative0191Library UP-TO-DATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesBase830Library UP-TO-DATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesBasement830Library UP-TO-DATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesMaps830Library UP-TO-DATE
:react-native-maps:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-maps:prepareReleaseDependencies
:react-native-maps:compileReleaseAidl UP-TO-DATE
:react-native-maps:compileReleaseRenderscript UP-TO-DATE
:react-native-maps:generateReleaseBuildConfig UP-TO-DATE
:react-native-maps:generateReleaseAssets UP-TO-DATE
:react-native-maps:mergeReleaseAssets UP-TO-DATE
:react-native-maps:generateReleaseResValues UP-TO-DATE
:react-native-maps:generateReleaseResources UP-TO-DATE
:react-native-maps:mergeReleaseResources UP-TO-DATE
:react-native-maps:processReleaseManifest UP-TO-DATE
:react-native-maps:processReleaseResources UP-TO-DATE
:react-native-maps:generateReleaseSources UP-TO-DATE
:react-native-maps:processReleaseJavaRes UP-TO-DATE
:react-native-maps:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-maps:extractReleaseAnnotations UP-TO-DATE
:react-native-maps:mergeReleaseProguardFiles UP-TO-DATE
:react-native-maps:packageReleaseJar UP-TO-DATE
:react-native-maps:compileReleaseNdk UP-TO-DATE
:react-native-maps:packageReleaseJniLibs UP-TO-DATE
:react-native-maps:packageReleaseLocalJar UP-TO-DATE
:react-native-maps:packageReleaseRenderscript UP-TO-DATE
:react-native-maps:packageReleaseResources UP-TO-DATE
:react-native-maps:bundleRelease UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0201Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBase830Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBasement830Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesMaps830Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareWeatherReactNativeMapsUnspecifiedLibrary UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac FAILED
/home/mihir/weather/android/app/src/main/java/com/weather/MainActivity.java:43: error: cannot find symbol
    protected void onCreate(Bundle savedInstanceState) {
                            ^
  symbol:   class Bundle
  location: class MainActivity
/home/mihir/weather/android/app/src/main/java/com/weather/MainActivity.java:45: error: cannot find symbol
      mReactRootView = new ReactRootView(this);
      ^
  symbol:   variable mReactRootView
  location: class MainActivity
/home/mihir/weather/android/app/src/main/java/com/weather/MainActivity.java:45: error: cannot find symbol
      mReactRootView = new ReactRootView(this);
                           ^
  symbol:   class ReactRootView
  location: class MainActivity
/home/mihir/weather/android/app/src/main/java/com/weather/MainActivity.java:47: error: mReactInstanceManager has private access in ReactActivity
      mReactInstanceManager = ReactInstanceManager.builder()
      ^
/home/mihir/weather/android/app/src/main/java/com/weather/MainActivity.java:54: error: cannot find symbol
           .setInitialLifecycleState(LifecycleState.RESUMED)
                                     ^
  symbol:   variable LifecycleState
  location: class MainActivity
/home/mihir/weather/android/app/src/main/java/com/weather/MainActivity.java:47: error: cannot find symbol
      mReactInstanceManager = ReactInstanceManager.builder()
                              ^
  symbol:   variable ReactInstanceManager
  location: class MainActivity
/home/mihir/weather/android/app/src/main/java/com/weather/MainActivity.java:57: error: mReactInstanceManager has private access in ReactActivity
      mReactRootView.startReactApplication(mReactInstanceManager, "MyApp", null);
                                           ^
/home/mihir/weather/android/app/src/main/java/com/weather/MainActivity.java:57: error: cannot find symbol
      mReactRootView.startReactApplication(mReactInstanceManager, "MyApp", null);
      ^
  symbol:   variable mReactRootView
  location: class MainActivity
/home/mihir/weather/android/app/src/main/java/com/weather/MainActivity.java:59: error: cannot find symbol
      setContentView(mReactRootView);
                     ^
  symbol:   variable mReactRootView
  location: class MainActivity
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.719 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by DanDance** [comment]
Can you please provide your MainActivity.jar code?

**Comment by incrediblebutterfly** [comment]
Do you mean MainActivity.java? I'm sorry, I'm new to Android development.

```
package com.weather;

import com.facebook.react.ReactActivity;
import com.AirMaps.AirPackage;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "weather";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

   /**
   * A list of packages used by the app. If the app uses additional views
   * or modules besides the default ones, add more packages here.
   */
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new AirPackage()
      );
    }
    @Override
    protected void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      mReactRootView = new ReactRootView(this);

      mReactInstanceManager = ReactInstanceManager.builder()
           .setApplication(getApplication())
           .setBundleAssetName("index.android.bundle")
           .setJSMainModuleName("index.android")
           .addPackage(new MainReactPackage())
           .addPackage(new AirPackage()) // <---- and This!
           .setUseDeveloperSupport(BuildConfig.DEBUG)
           .setInitialLifecycleState(LifecycleState.RESUMED)
           .build();

      mReactRootView.startReactApplication(mReactInstanceManager, "MyApp", null);

      setContentView(mReactRootView);
    }    
}

```

**Comment by DanDance** [comment]
Yeah, sure. Did you set up plugin manually or with `rnpm link`?

**Comment by incrediblebutterfly** [comment]
I did it with `rnpm link` and then manually checked every affected file against the ones that are mentioned in [Installation Guide](https://github.com/lelandrichardson/react-native-maps/blob/master/docs/installation.md)
After that, I added my google maps API key in AndroidManifest.xml manually.

**Comment by incrediblebutterfly** [comment]
Hey! I think I just solved the issue. I removed `onCreate()` method from MainActivity.java and everything worked like a charm. That being said, I'd like to know why is `onCreate()` method is mentioned in the installation guide?

**Comment by DanDance** [comment]
I did it with `rnpm link` and saw that there is no `onCreate()` method. Glad you solved it!

**Comment by incrediblebutterfly** [comment]
Yeah! Thank you!

**Comment by mahesh963** [comment]
hello, i have a same issue ,

any one Help me...


```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-maps'.
   > Could not resolve all dependencies for configuration ':react-native-maps:_debugCompile'.
      > Could not find com.google.android.gms:play-services-base:9.8.0.
        Searched in the following locations:
            file:/Users/stellent/.m2/repository/com/google/android/gms/play-services-base/9.8.0/play-services-base-9.8.0.pom
            file:/Users/stellent/.m2/repository/com/google/android/gms/play-services-base/9.8.0/play-services-base-9.8.0.jar
            https://jcenter.bintray.com/com/google/android/gms/play-services-base/9.8.0/play-services-base-9.8.0.pom
            https://jcenter.bintray.com/com/google/android/gms/play-services-base/9.8.0/play-services-base-9.8.0.jar
            file:/Users/stellent/Desktop/TravelStore/node_modules/react-native/android/com/google/android/gms/play-services-base/9.8.0/play-services-base-9.8.0.pom
            file:/Users/stellent/Desktop/TravelStore/node_modules/react-native/android/com/google/android/gms/play-services-base/9.8.0/play-services-base-9.8.0.jar
            file:/Users/stellent/Desktop/TravelStore/node_modules/react-native-maps/node_modules/react-native/android/com/google/android/gms/play-services-base/9.8.0/play-services-base-9.8.0.pom
            file:/Users/stellent/Desktop/TravelStore/node_modules/react-native-maps/node_modules/react-native/android/com/google/android/gms/play-services-base/9.8.0/play-services-base-9.8.0.jar
            file:/Users/stellent/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-base/9.8.0/play-services-base-9.8.0.pom
            file:/Users/stellent/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-base/9.8.0/play-services-base-9.8.0.jar
        Required by:
            TravelStore:react-native-maps:unspecified
      > Could not find com.google.android.gms:play-services-maps:9.8.0.
        Searched in the following locations:
            file:/Users/stellent/.m2/repository/com/google/android/gms/play-services-maps/9.8.0/play-services-maps-9.8.0.pom
            file:/Users/stellent/.m2/repository/com/google/android/gms/play-services-maps/9.8.0/play-services-maps-9.8.0.jar
            https://jcenter.bintray.com/com/google/android/gms/play-services-maps/9.8.0/play-services-maps-9.8.0.pom
            https://jcenter.bintray.com/com/google/android/gms/play-services-maps/9.8.0/play-services-maps-9.8.0.jar
            file:/Users/stellent/Desktop/TravelStore/node_modules/react-native/android/com/google/android/gms/play-services-maps/9.8.0/play-services-maps-9.8.0.pom
            file:/Users/stellent/Desktop/TravelStore/node_modules/react-native/android/com/google/android/gms/play-services-maps/9.8.0/play-services-maps-9.8.0.jar
            file:/Users/stellent/Desktop/TravelStore/node_modules/react-native-maps/node_modules/react-native/android/com/google/android/gms/play-services-maps/9.8.0/play-services-maps-9.8.0.pom
            file:/Users/stellent/Desktop/TravelStore/node_modules/react-native-maps/node_modules/react-native/android/com/google/android/gms/play-services-maps/9.8.0/play-services-maps-9.8.0.jar
            file:/Users/stellent/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-maps/9.8.0/play-services-maps-9.8.0.pom
            file:/Users/stellent/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-maps/9.8.0/play-services-maps-9.8.0.jar
        Required by:
            TravelStore:react-native-maps:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

**Comment by ycpatel813** [comment]
@mahesh963 Install `Google Repositories` using SDK manager and then try to build app.

**Comment by mahesh963** [comment]
Hi @ycpatel813 
I Installed Google Repositories to revision(44) in SDK manager.But, I am facing the same Error.
Can any one suggest me to solve this issue.Any best solutions are appreciated.
