### ISSUE TITLE
can't find libAIRMaps.a

### ISSUE THREAD

**Issue by swimjo** [lelandrichardson/react-native-maps#90]
Hi,

I am having some issues and haven't been able to figure them out. When I attempt to install and link the react-native-maps package using rnpm link, it only links the Android project, and doesn't mention the iOS project. When I go in to do the linking manually, I can't find the libAIRMaps.a binary file to link to the AirMaps.xcodeproj. 

I've been uninstalling, reinstalling, and trying various methods but can't seem to get the binary file linked and as a result the map doesn't show up.

Can someone please help either point me in the right direction on how to fix rnpm so that it automatically links the iOS project, or where I can find the binary file. 

Thanks.

**Comment by christopherdro** [comment]
@swimjo Could you try adding the library manually?

**Comment by christopherdro** [comment]
@swimjo Any updates?

**Comment by swimjo** [comment]
Hey sorry- I had to take a break from this and only am now getting back into it- I just had to restart and reinstall everything, there seemed to be something going wrong. It seems to be a little iffy for me whether the set-up works or not but eventually it does.

Thanks.
