### ISSUE TITLE
Possible to have a button in a callout?

### ISSUE THREAD

**Issue by heydabop** [lelandrichardson/react-native-maps#92]
Is it possible to have a button (or two) in a marker callout?
I'm aware callout has its own onPress, but I have two buttons I'd like in the callout, and as of right now either the map or the callout is catching presses and so the buttons in the callout never see them. Alternatively, the information present in the press on the callout isn't enough to determine where it's being pressed.
Just wondering if anyone has a method of doing this or if I need to find another way to do what I'm doing.

**Comment by machard** [comment]
On iOS it works, on Android not.
On Android it comes from Google Maps : https://developers.google.com/maps/documentation/android-api/infowindows (see the note)

> The info window that is drawn is not a live view. The view is rendered as an image (using View.draw(Canvas)) at the time it is returned. This means that any subsequent changes to the view will not be reflected by the info window on the map. To update the info window later (for example, after an image has loaded), call showInfoWindow(). Furthermore, the info window will not respect any of the interactivity typical for a normal view such as touch or gesture events. However you can listen to a generic click event on the whole info window as described in the section below.

**Comment by heydabop** [comment]
Ahh, thank you for the assistance.

**Comment by cristian9804** [comment]
i'm having the same issue with IOS. I have 2 buttons in the mapview and when I press none of them work 
.
