### ISSUE TITLE
accuracy in location tracker

### ISSUE THREAD

**Issue by texas697** [lelandrichardson/react-native-maps#94]
would a native swift project have more accuracy when tracking a users movement? I have created app that does this and the points are not as accurate when compared to native swift template i bought that does the same thing. this is the template i purchased.
http://zappdesigntemplates.com/product/corelocation-coredata-swift-ios-app-source-code-psd/

**Comment by lelandrichardson** [comment]
@texas697 i don't know much about this, but I think @christopherdro does. There was some accuracy stuff that he recently merged into RN

**Comment by christopherdro** [comment]
@texas697 You can see the commit here: https://github.com/facebook/react-native/commit/109036b4c4b530c04c394c48e43319ca91ca2d53

Previous, the default distance filter on iOS was set to 100 meters. Now, you should be able to set any value you'd like. Try setting the distance filter to `10` and see if you end up getting more accurate results.

**Comment by christopherdro** [comment]
@texas697
Any updates on this issue?
