### ISSUE TITLE
Possibility of fixed marker and draggable map

### ISSUE THREAD

**Issue by ahmed1490** [lelandrichardson/react-native-maps#99]
This is pretty similar to how Uber behaves.
Instead of dragging the map marker (which is not necessarily a good ux), uber allows to drag the map while the pin is fixed in the middle of the screen.

**Comment by heydabop** [comment]
Assuming your MapView is filling whatever view it's in, you can just put another view with only your marker in the center of it over the MapView. I'm doing this right now by putting the following right after my MapView. Then you can just use the MapView methods to get its current location.

```
<View pointerEvents="none" style={{position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, alignItems: 'center', justifyContent: 'center', backgroundColor: 'transparent'}}>
    <Image pointerEvents="none" source={markerImage}/>
</View>
```

**Comment by ahmed1490** [comment]
sounds like a solution, although Ideally it would be nice to have something passed to marker to make it static on the screen instead of the map.

In your case, do you use screen resolutions, map width/height to get the lat/long value or is there a better way?

**Comment by heydabop** [comment]
If you pass it to a marker it will be static with respect to the map, that's the point of a marker. It's a child of the map, so as you drag the map the marker gets dragged too. What you want is something completely independent of the map.

Use the MapView method `onRegionChange` and update a state variable that you can then use to figure out where the center of the map and thus your marker is.

**Comment by christopherdro** [comment]
@ahmed1490 
@heydabop Is right that want you are looking for is something independent. I would also suggest using `onRegionChange` to achieve what your looking for.

**Comment by b4lk0n** [comment]
But what if you need to have draggable map? View with your marker icon will cover MapView, so I won't respond to dragging events.

**Comment by derman232** [comment]
@b4lk0n as in the example above, using the 'pointerEvents="none"' prop fixes that issue

**Comment by ArifSanaullah** [comment]
> Assuming your MapView is filling whatever view it's in, you can just put another view with only your marker in the center of it over the MapView. I'm doing this right now by putting the following right after my MapView. Then you can just use the MapView methods to get its current location.
> 
> ```
> <View pointerEvents="none" style={{position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, alignItems: 'center', justifyContent: 'center', backgroundColor: 'transparent'}}>
>     <Image pointerEvents="none" source={markerImage}/>
> </View>
> ```

Using this approach I can no longer drag map.
